Update auto-retry docs for version 2.0 of the plugin
grammyjs/website pull request #1006
Opened 2024-03-16 15:23 UTC by KnorpelSenf

Version 2.0 is not released yet. When this PQ is ready to be merged, we first need to release the plugin and then we can merge it.

Migrating to 2.0 will be absolutely trivial, since only a single option was renamed. A short note will be included in the news channel post. There is no need for a migration guide.

> Note that in contrast to this, comprehensive migration guides will be published if the core library will receive a major version upgrade.

2024-03-18 08:00 UTC, KnorpelSenf commented
@roj1512 ping

2024-03-18 12:55 UTC, roj1512 commented on site/docs/plugins/auto-retry.md
> +- Reference: <https://deno.land/x/grammy_auto_retry/mod.ts>
Should this link to the new ref?

2024-03-18 16:55 UTC, KnorpelSenf commented on site/docs/plugins/auto-retry.md
> +- Reference: <https://deno.land/x/grammy_auto_retry/mod.ts>
Oops. Yes.

2024-03-18 17:00 UTC, KnorpelSenf commented on site/docs/plugins/auto-retry.md
> +- Reference: <https://deno.land/x/grammy_auto_retry/mod.ts>
Fixed

2024-03-18 17:09 UTC, roj1512 approved these changes

2024-03-20 12:59 UTC, LWJerri requested changes
Resolve all comments from @deptyped and I will approve the PQ.

2024-03-21 14:27 UTC, LWJerri approved these changes

2024-03-31 04:45 UTC, quadratz requested changes
@roj1512

2024-03-31 04:45 UTC, quadratz commented on site/docs/plugins/auto-retry.md
> +Networking errors (those that [throw an `HttpError`](../guide/errors.md#the-httperror-object) in grammY) will cause a retry, too.
```suggestion
Networking errors (those that [throw an `HttpError`](../guide/errors#the-httperror-object) in grammY) will cause a retry, too.
```

2024-03-31 04:45 UTC, quadratz commented on site/docs/plugins/auto-retry.md
> +If enabled, the thrown [`HttpError`](../guide/errors.md#the-httperror-object) instances are passed on, failing the request.
```suggestion
If enabled, the thrown [`HttpError`](../guide/errors#the-httperror-object) instances are passed on, failing the request.
```

2024-03-31 04:45 UTC, quadratz commented on site/docs/uk/plugins/auto-retry.md
> +Мережеві помилки (ті, що [викидають `HttpError`](../guide/errors.md#обʼєкт-httperror) в grammY) також призведуть до повторної спроби.
```suggestion
Мережеві помилки (ті, що [викидають `HttpError`](../guide/errors#обʼєкт-httperror) в grammY) також призведуть до повторної спроби.
```

2024-03-31 04:45 UTC, quadratz commented on site/docs/uk/plugins/auto-retry.md
> +Якщо цей параметр увімкнено, екземпляри [`HttpError`](../guide/errors.md#обʼєкт-httperror) передаватимуться далі, якщо запит не вдасться виконати.
```suggestion
Якщо цей параметр увімкнено, екземпляри [`HttpError`](../guide/errors#обʼєкт-httperror) передаватимуться далі, якщо запит не вдасться виконати.
```

2024-03-31 05:01 UTC, dzikrl requested changes

2024-03-31 05:28 UTC, quadratz commented on site/docs/id/plugins/auto-retry.md
> +Ia bisa diterapkan ke semua bot selama pengoperasian normal, dan akan sangat membantu terutama selama[proses penyiaran (broadcasting)](../advanced/flood#cara-menyebarkan-pesan) berlangsung.
Also simplify a bit?
```suggestion
Ia bisa diterapkan ke semua bot selama pengoperasian normal, terutama saat [proses penyiaran (broadcasting)](../advanced/flood#cara-menyebarkan-pesan) berlangsung.
```

2024-04-05 08:03 UTC, quadratz approved these changes

2024-04-06 23:58 UTC, KnorpelSenf commented
I will do a release on Monday or Tuesday

2024-04-20 06:39 UTC, merged