Update docs about API ref
grammyjs/website pull request #1008
Opened 2024-03-17 22:09 UTC by KnorpelSenf

Since #532 was merged, we need to update our description of how the docs are structured

2024-03-17 22:09 UTC, roj1512 approved these changes

2024-03-18 01:00 UTC, LWJerri approved these changes
:shipit:

2024-03-18 04:40 UTC, niusia-ua requested changes

2024-03-18 10:09 UTC, KnorpelSenf commented
#1014 will fix CI

2024-03-18 10:45 UTC, niusia-ua approved these changes

2024-03-23 13:42 UTC, quadratz approved these changes

2024-04-06 15:28 UTC, merged