Explain plugin refs in overview
grammyjs/website pull request #1017
Opened 2024-03-20 17:58 UTC by KnorpelSenf

This was done in #950 but forgotten in #1008 that partially superseded #950.

2024-03-23 00:39 UTC, roj1512 approved these changes

2024-03-23 14:29 UTC, LWJerri commented on site/docs/uk/guide/README.md
> +**Друга частина** --- це [довідка API grammY](/ref/), посилання на яке знаходиться у верхній частині сторінки.
```suggestion
**Друга частина** --- це [довідка API grammY](/ref/), яка знаходиться у верхній частині сторінки.
```

2024-03-23 14:30 UTC, LWJerri commented on site/docs/uk/guide/README.md
> +Окрім того, що плагіни зʼявляються в [огляді довідки API](/ref/), посилання на їхню довідку API містяться в короткому описі внизу сторінки кожного плагіна.
```suggestion
Окрім того, що плагіни зʼявляються в [огляді довідки API](/ref/), посилання на довідку містяться в короткому описі внизу сторінки кожного плагіна.
```

2024-03-23 14:30 UTC, LWJerri approved these changes
You can accept or reject these suggestions, they don't make much difference, but readability seems to me to be getting better. :shipit:

2024-03-26 05:45 UTC, quadratz requested changes

2024-03-26 05:45 UTC, quadratz commented on site/docs/id/guide/README.md
> +Kamu bisa memulai dari bab _Belajar_ di tab navigasi yang ada di bagian atas halaman ini, disana dijelaskan semua konsep intinya.
```suggestion
Untuk memahami konsep dasar secara keseluruhan, kamu bisa memulai dari bab _Belajar_ yang berada di tab navigasi bagian atas halaman ini.
```

2024-03-26 05:45 UTC, quadratz commented on site/docs/id/guide/README.md
> +Hal yang sama juga berlaku pada setiap plugin pada ekosistem grammY.
Pengulangan `pada`
```suggestion
Hal yang sama juga berlaku untuk setiap plugin di ekosistem grammY.
```

2024-03-26 05:45 UTC, quadratz commented on site/docs/id/guide/README.md
> +Selain menampilkan [gambaran referensi API](/ref/), tiap plugin juga memiliki referensi API-nya sendiri yang tertaut di ringkasan plugin pada bagian bawah halaman.
```suggestion
Selain menampilkan [gambaran referensi API](/ref/), setiap plugin juga memiliki referensi API-nya sendiri yang tertaut di ringkasan plugin pada bagian bawah halaman.
```

2024-03-26 06:22 UTC, quadratz requested changes
@dzikrl

2024-03-26 06:22 UTC, quadratz commented on site/docs/id/guide/README.md
> +Selain menampilkan [gambaran referensi API](/ref/), setiap plugin juga memiliki referensi API-nya sendiri yang tertaut di ringkasan plugin pada bagian bawah halaman.
> In addition to appearing in the [overview of API references](/ref/), plugins have their API reference linked in the plugin summary at the bottom of each plugin page.

Based on that context, I think this one is more appropriate

```suggestion
Selain tercantum di [referensi utama API](/ref/), setiap plugin juga mencantumkan referensi API-nya masing-masing di ringkasan plugin pada bagian bawah halaman.
```

2024-03-27 10:07 UTC, deptyped commented on site/docs/uk/guide/README.md
> +Окрім того, що плагіни зʼявляються в [огляді довідки API](/ref/), посилання на їхню довідку API містяться в короткому описі внизу сторінки кожного плагіна.
```suggestion
Окрім того, що плагіни представлені в [огляді довідки API](/ref/), посилання на їхню довідку містяться в короткому описі внизу сторінки кожного плагіна.
```

2024-03-27 10:08 UTC, deptyped commented on site/docs/uk/guide/README.md
> +**Друга частина** --- це [довідка API grammY](/ref/), посилання на яке знаходиться у верхній частині сторінки.
```suggestion
**Друга частина** --- це [довідка API grammY](/ref/), посилання на яку знаходиться у верхній частині сторінки.
```

2024-03-27 10:10 UTC, deptyped commented on site/docs/uk/guide/README.md
> +Окрім того, що плагіни зʼявляються в [огляді довідки API](/ref/), посилання на їхню довідку API містяться в короткому описі внизу сторінки кожного плагіна.
```suggestion
Окрім того, що плагіни представлені в [огляді довідки API](/ref/), посилання на їхню довідку містяться в короткому описі внизу сторінки кожного плагіна.
```

2024-04-04 13:21 UTC, deptyped approved these changes

2024-04-06 15:24 UTC, merged