fix my chat member update comment
grammyjs/website pull request #1054
Opened 2024-05-17 13:50 UTC by KnorpelSenf

These updates aren't sent when the bot is started the first time. They're only sent when the bot is blocked and when it's unblocked again. The comment is misleading. This fixes that.

2024-05-29 16:22 UTC, roj1512 approved these changes

2024-05-30 01:38 UTC, quadratz requested changes

2024-05-30 01:38 UTC, quadratz commented on site/docs/guide/filter-queries.md
>  In private chats, this triggers when the bot is started or stopped.
```suggestion
In private chats, this triggers when the bot is blocked or unblocked.
```

2024-05-30 11:51 UTC, KnorpelSenf commented on site/docs/guide/filter-queries.md
>  In private chats, this triggers when the bot is started or stopped.
Excellent catch, thanks

2024-05-31 12:38 UTC, quadratz approved these changes

2024-06-01 16:59 UTC, merged