Translations for Zeabur hosting (#1059)
grammyjs/website pull request #1071
Opened 2024-06-04 15:36 UTC by KnorpelSenf

Supersedes #1059.

2024-06-05 02:54 UTC, niusia-ua commented on site/docs/hosting/zeabur-deno.md
> +> Note: Get your bot token with [@BotFather](https://t.me/BotFather) on Telegram, and set is as an environment variable `TELEGRAM_BOT_TELEGRAM` in Zeabur.
```suggestion
> Note: Get your bot token with [@BotFather](https://t.me/BotFather) on Telegram, and set is as an environment variable `TELEGRAM_BOT_TOKEN` in Zeabur.
```

2024-06-05 03:06 UTC, niusia-ua commented on site/docs/hosting/zeabur-nodejs.md
> +Then, cd into `src/`, and create a file named `bot.ts`.
```suggestion
Then, `cd` into `src/`, and create a file named `bot.ts`.
```

2024-06-05 03:13 UTC, niusia-ua commented on site/docs/hosting/zeabur-deno.md
> +4. Your service will be deployed automatically.
```suggestion
3. Click on the `New Project` button, and click on the `Deploy New Service` button, choose `GitHub` as the source and select your repository.
4. Go to Variables tab to add your environment variables like `BOT_TOKEN`.
5. Your service will be deployed automatically.
```

Why is the point about environment variables missing here? It is present in the Node.js version.

2024-06-05 03:14 UTC, niusia-ua commented on site/docs/hosting/zeabur-nodejs.md
> +4. Go to Variables tab to add your environment variables like `BOT_TOKEN`.
```suggestion
4. Go to Variables tab to add your environment variables like `TELEGRAM_BOT_TOKEN`.
```

2024-06-05 06:20 UTC, niusia-ua approved these changes

2024-06-05 07:42 UTC, LWJerri commented on site/docs/uk/hosting/zeabur-deno.md
> +У цьому посібнику ви дізнаєтеся, як розгорнути своїх ботів grammY за допомогою Deno на [Zeabur](https://zeabur.com/).
```suggestion
У цьому посібнику ви дізнаєтеся, як розгорнути своїх ботів grammY за допомогою Deno на [Zeabur](https://zeabur.com).
```

2024-06-05 07:42 UTC, LWJerri commented on site/docs/hosting/zeabur-deno.md
> +This tutorial will guide you how to deploy your grammY bots with Deno to [Zeabur](https://zeabur.com/).
```suggestion
This tutorial will guide you how to deploy your grammY bots with Deno to [Zeabur](https://zeabur.com).
```

2024-06-05 07:42 UTC, LWJerri commented on site/docs/hosting/zeabur-deno.md
> +To follow along, you need to have [Github](https://github.com) and [Zeabur](https://zeabur.com/) accounts.
```suggestion
To follow along, you need to have [Github](https://github.com) and [Zeabur](https://zeabur.com) accounts.
```

2024-06-05 07:43 UTC, LWJerri commented on site/docs/hosting/zeabur-nodejs.md
> +This tutorial will guide you how to deploy your grammY bots with Node.js to [Zeabur](https://zeabur.com/).
```suggestion
This tutorial will guide you how to deploy your grammY bots with Node.js to [Zeabur](https://zeabur.com).
```

2024-06-05 07:43 UTC, LWJerri commented on site/docs/uk/hosting/zeabur-deno.md
> +Щоб слідувати посібнику, вам потрібно мати облікові записи [Github](https://github.com) та [Zeabur](https://zeabur.com/).
```suggestion
Щоб слідувати посібнику, вам потрібно мати облікові записи [Github](https://github.com) та [Zeabur](https://zeabur.com).
```

2024-06-05 07:43 UTC, LWJerri commented on site/docs/uk/hosting/zeabur-nodejs.md
> +У цьому посібнику ви дізнаєтеся, як розгорнути своїх ботів grammY за допомогою Node.js на [Zeabur](https://zeabur.com/).
```suggestion
У цьому посібнику ви дізнаєтеся, як розгорнути своїх ботів grammY за допомогою Node.js на [Zeabur](https://zeabur.com).
```

2024-06-05 07:44 UTC, LWJerri commented on site/docs/uk/hosting/zeabur-nodejs.md
> +Щоб слідувати посібнику, вам потрібно мати облікові записи [Github](https://github.com) та [Zeabur](https://zeabur.com/).
```suggestion
Щоб слідувати посібнику, вам потрібно мати облікові записи [Github](https://github.com) та [Zeabur](https://zeabur.com).
```

2024-06-05 07:46 UTC, LWJerri commented on site/docs/uk/hosting/zeabur-deno.md
> +### Спосіб 2: використання шаблону Zeabur
```suggestion
### Спосіб 2: Використання шаблону Zeabur
```

2024-06-05 07:46 UTC, LWJerri commented on site/docs/uk/hosting/zeabur-deno.md
> +### Спосіб 1: розгортання з GitHub на інформаційній панелі Zeabur
```suggestion
### Спосіб 1: Розгортання з GitHub на інформаційній панелі Zeabur
```

2024-06-05 07:47 UTC, LWJerri commented on site/docs/uk/hosting/zeabur-deno.md
> +### Спосіб 2: розгортання за допомогою Zeabur CLI
```suggestion
### Спосіб 2: Розгортання за допомогою Zeabur CLI
```

2024-06-05 07:48 UTC, LWJerri commented on site/docs/uk/hosting/zeabur-nodejs.md
> +### Спосіб 1: створення нового проєкту з нуля
```suggestion
### Спосіб 1: Створення нового проєкту з нуля
```

2024-06-05 07:52 UTC, LWJerri commented on site/docs/uk/hosting/zeabur-nodejs.md
> +### Спосіб 2: використання шаблону Zeabur
```suggestion
### Спосіб 2: Використання шаблону Zeabur
```

2024-06-05 07:53 UTC, LWJerri commented on site/docs/uk/hosting/zeabur-nodejs.md
> +### Спосіб 1: розгортання з GitHub на інформаційній панелі Zeabur
```suggestion
### Спосіб 1: Розгортання з GitHub на інформаційній панелі Zeabur
```

2024-06-05 07:53 UTC, LWJerri requested changes
not :shipit:

2024-06-05 09:33 UTC, niusia-ua commented on site/docs/uk/hosting/zeabur-deno.md
> +### Спосіб 1: створення нового проєкту з нуля
I think this style is not inherent in the Ukrainian language.
@deptyped What do you think?

2024-06-05 15:17 UTC, deptyped approved these changes

2024-06-05 15:17 UTC, deptyped commented on site/docs/uk/hosting/zeabur-deno.md
> +# Створюємо файл deno.json, щоб згенерувати файл lock
```suggestion
# Створюємо файл deno.json, щоб згенерувати lock-файл
```

2024-06-05 15:17 UTC, deptyped commented on site/docs/uk/hosting/zeabur-deno.md
> +Deno автоматично завантажить залежності, згенерує файл lock і запустить вашого бота.
```suggestion
Deno автоматично завантажить залежності, згенерує lock-файл і запустить вашого бота.
```

2024-06-05 15:17 UTC, deptyped commented on site/docs/uk/hosting/zeabur-deno.md
> +1. Створіть репозиторій на GitHub (він може бути публічним або приватним) і перемістіть туди свій код.
```suggestion
1. Створіть репозиторій на GitHub (він може бути публічним або приватним) і завантажте туди свій код.
```

2024-06-05 15:17 UTC, deptyped commented on site/docs/uk/hosting/zeabur-nodejs.md
> +Далі нам потрібно додати до нашого `package.json` скрипти `start`.
```suggestion
Далі нам потрібно додати до нашого `package.json` скрипт `start`.
```

2024-06-05 15:17 UTC, deptyped commented on site/docs/uk/hosting/zeabur-nodejs.md
> +1. Створіть репозиторій на GitHub (він може бути публічним або приватним) і перемістіть туди свій код.
```suggestion
1. Створіть репозиторій на GitHub (він може бути публічним або приватним) і завантажте туди свій код.
```

2024-06-05 15:17 UTC, deptyped commented on site/docs/uk/hosting/zeabur-deno.md
> +### Спосіб 1: створення нового проєкту з нуля
@niusia-ua Yes, I agree. It's grammatically correct to use a lowercase letter here

2024-06-08 11:52 UTC, LWJerri approved these changes
:shipit:

2024-06-15 06:24 UTC, dzikrl requested changes

2024-06-15 06:24 UTC, dzikrl commented on site/docs/id/hosting/zeabur-deno.md
> +Tutorial ini ditujukan khusus untuk mendeploy bot Telegram yang dibuat menggunakan Deno ke Zeabur.
```suggestion
Tutorial ini ditujukan khusus untuk men-deploy bot Telegram yang dibuat menggunakan Deno ke Zeabur.
```

2024-06-15 06:24 UTC, dzikrl commented on site/docs/id/hosting/zeabur-deno.md
> +Zeabut memiliki sebuah templat yang bisa kamu gunakan sebagai acuan untuk membuat bot Telegram Deno.
```suggestion
Zeabur memiliki sebuah templat yang bisa kamu gunakan sebagai acuan untuk membuat bot Telegram Deno.
```

2024-06-15 06:24 UTC, dzikrl commented on site/docs/id/hosting/zeabur-nodejs.md
> +Tutorial ini ditujukan khusus untuk mendeploy bot Telegram yang dibuat menggunakan Node.js ke Zeabur.
```suggestion
Tutorial ini ditujukan khusus untuk men-deploy bot Telegram yang dibuat menggunakan Node.js ke Zeabur.
```

2024-06-15 06:24 UTC, dzikrl commented on site/docs/id/hosting/zeabur-nodejs.md
> +# Install dependensi utama.
```suggestion
# Instal dependensi utama.
```

2024-06-15 06:24 UTC, dzikrl commented on site/docs/id/hosting/zeabur-nodejs.md
> +# Install dependensi pengembangan.
```suggestion
# Instal dependensi pengembangan.
```

2024-06-15 06:24 UTC, dzikrl commented on site/docs/id/hosting/zeabur-nodejs.md
> +Zeabut memiliki sebuah templat untuk bot Telegram grammY yang bisa kamu gunakan sebagai acuan.
```suggestion
Zeabur memiliki sebuah templat untuk bot Telegram grammY yang bisa kamu gunakan sebagai acuan.
```

2024-06-15 09:40 UTC, dzikrl requested changes

2024-06-15 09:40 UTC, dzikrl commented on site/docs/id/hosting/zeabur-deno.md
> +Jika kamu mencari yang versi Node.js-nya, silahkan beralih ke [tutorial ini](./zeabur-nodejs).
```suggestion
Jika kamu mencari yang versi Node.js-nya, silahkan beralih ke [tutorial berikut](./zeabur-nodejs).
```

2024-06-15 09:40 UTC, dzikrl commented on site/docs/id/hosting/zeabur-nodejs.md
> +  "name": "telegram-bot-starter",
```suggestion
  "name": "bot-telegram-grammy",
```

2024-06-15 09:40 UTC, dzikrl commented on site/docs/id/hosting/zeabur-nodejs.md
> +  "description": "Percobaan Telegram Bot menggunakan TypeScript dan grammY",
```suggestion
  "description": "Bot Telegram menggunakan TypeScript dan grammY",
```

2024-06-15 09:59 UTC, dzikrl approved these changes

2024-06-15 10:13 UTC, quadratz approved these changes

2024-06-16 20:33 UTC, merged