Rework comparison with other frameworks
grammyjs/website pull request #1075
Opened 2024-06-16 20:08 UTC by KnorpelSenf

As promised in https://t.me/grammyjs/244931

2024-06-16 20:19 UTC, roj1512 commented on site/docs/resources/comparison.md
> +Pick a library written in Go if you already know fairly well what you will be building (you don't expect to need much assistance), and you alreay know that your bot will process very high numbers of
```suggestion
Pick a library written in Go if you already know fairly well what you will be building (you don't expect to need much assistance), and you already know that your bot will process very high numbers of updates.
```

2024-06-16 20:23 UTC, KnorpelSenf commented on site/docs/resources/comparison.md
> +Pick a library written in Go if you already know fairly well what you will be building (you don't expect to need much assistance), and you already know that your bot will process very high numbers of
```suggestion
Pick a library written in Go if you already know fairly well what you will be building (you don't expect to need much assistance), and you already know that your bot will process a very large number of updates.
```

2024-06-16 20:23 UTC, KnorpelSenf commented on site/docs/resources/comparison.md
> +Pick a library written in Go if you already know fairly well what you will be building (you don't expect to need much assistance), and you already know that your bot will process very high numbers of
@roj1512 accept this if you think that it is an improvement to the wording

2024-06-17 08:13 UTC, niusia-ua commented on site/docs/resources/comparison.md
> +If you want to use Rust, then do it, but consider saying that you love Rust and not that it is the right tool for the job.
`please not that`?

Is this correct?

2024-06-17 08:14 UTC, KnorpelSenf commented on site/docs/resources/comparison.md
> +If you want to use Rust, then do it, but consider saying that you love Rust and not that it is the right tool for the job.
No. It should be _please note that_

2024-06-17 08:21 UTC, niusia-ua commented on site/docs/resources/comparison.md
> +If you want to use Rust, then do it, but consider saying that you love Rust and not that it is the right tool for the job.
```suggestion
Also, please note that using Rust is fun but rarely necessary for bots.
If you want to use Rust, then do it, but consider saying that you love Rust and note that it is the right tool for the job.
```

2024-06-17 08:22 UTC, KnorpelSenf commented on site/docs/resources/comparison.md
> +If you want to use Rust, then do it, but consider saying that you love Rust and not that it is the right tool for the job.
Just here: 
```suggestion
Also, please note that using Rust is fun but rarely necessary for bots.
If you want to use Rust, then do it, but consider saying that you love Rust and not that it is the right tool for the job.
```

2024-06-17 09:15 UTC, LWJerri commented on site/docs/uk/resources/comparison.md
> +Якщо ви твердо налаштовані використовувати щось іншу мову програмування, то можете припинити читання тут.
```suggestion
Якщо ви твердо налаштовані використовувати іншу мову програмування, то можете припинити читання тут.
```

2024-06-17 09:16 UTC, LWJerri commented on site/docs/uk/resources/comparison.md
> +Це порівняння буде обмежено Python, Go та Rust.
```suggestion
Це порівняння буде обмежене Python, Go та Rust.
```

2024-06-17 09:19 UTC, LWJerri approved these changes
not :shipit:, bc I leave some comments.

2024-06-17 10:37 UTC, niusia-ua commented on site/docs/uk/resources/comparison.md
> +  Telegraf її не має: замість неї слугує згенерований довідник API, який не містить пояснень, а ті кілька посібників, що існують, є неповними і їх важко знайти.
Yes. Telegraf doesn't have the documentation. "Telegraf (кого/що?) її (документації) не має".

2024-06-17 10:46 UTC, niusia-ua approved these changes

2024-06-17 10:46 UTC, niusia-ua commented on site/docs/uk/resources/comparison.md
> +  Telegraf її не має: замість неї слугує згенерований довідник API, який не містить пояснень, а ті кілька посібників, що існують, є неповними і їх важко знайти.
```suggestion
  Telegraf не має її: замість неї слугує згенерований довідник API, який не містить пояснень, а ті кілька посібників, що існують, є неповними і їх важко знайти.
```

2024-06-18 06:41 UTC, deptyped requested changes

2024-06-18 06:41 UTC, deptyped commented on site/docs/uk/resources/comparison.md
> +- Багато інших речей, як-от краща продуктивність, велика екосистема плагінів, документація, перекладена для мільярдів людей, краща інтеграція з базами даних і вебфреймворками, краща сумісність під ча
```suggestion
- Багато інших речей, як-от краща продуктивність, велика екосистема плагінів, документація, перекладена для мільярдів людей, краща інтеграція з базами даних і вебфреймворками, краща сумісність з середовищами виконання, розширення [VS Code](https://marketplace.visualstudio.com/items?itemName=grammyjs.grammyjs) тощо, які ви відкриєте для себе в процесі роботи.
```

2024-06-18 06:41 UTC, deptyped commented on site/docs/uk/resources/comparison.md
> +Це набагато менш актуально, коли ви пишете бота, тому що більша частина часу витрачається на очікування мережі, але з часом це почне мати значення, як швидко ваш бот може розбирати JSON.
```suggestion
Це набагато менш актуально, коли ви пишете бота, тому що більша частина часу витрачається на очікування мережі, але з часом почне мати значення, як швидко ваш бот може розбирати JSON.
```

2024-06-18 06:41 UTC, deptyped commented on site/docs/uk/resources/comparison.md
> +Якщо ви хочете використовувати Rust, то робіть це, але не забувайте наголошувати на тому, що ви любите Rust і зазначати, що це правильний інструмент для роботи.
```suggestion
Якщо ви хочете використовувати Rust, то робіть це, але слід враховувати, що це скоріше ваша любов до Rust, ніж те, що він є правильним інструментом для цієї роботи.
```

2024-06-18 10:58 UTC, roziscoding approved these changes
Minor suggestions on the english version :)

2024-06-18 10:58 UTC, roziscoding commented on site/docs/resources/comparison.md
> +- There are a few details where Telegraf and grammY use different syntax to achieve the same thing, and you just happen to prefer one style of the other.
```suggestion
- There are a few details where Telegraf and grammY use different syntax to achieve the same thing, and you just happen to prefer one style over the other.
```

2024-06-18 10:58 UTC, roziscoding commented on site/docs/resources/comparison.md
> +Some of the following points are based partially based on personal opinions.
```suggestion
Some of the following points are partially based on personal opinions.
```

2024-06-19 05:28 UTC, deptyped approved these changes

2024-06-19 12:03 UTC, quadratz commented on site/docs/id/resources/comparison.md
> +Go bisa menjadi pilihan yang lebih baik dalam kasus ini.
```suggestion
Pilih library yang ditulis dalam Go jika kamu sudah tahu dan sudah jelas apa yang ingin kamu buat (tidak berharap membutuhkan banyak bantuan) dan tahu kalau bot kamu akan memproses banyak hal.
Sebagai bahasa yang di-compile secara native, Go lebih unggul dari TypeScript beberapa kali lipat dalam kecepatan pemrosesan CPU.
Keunggulan tersebut menjadi lebih relevan ketika kecepatan penguraian JSON menjadi hal yang krusial dan prioritas
Go bisa menjadi pilihan yang lebih baik dalam kasus ini.
```

2024-06-19 12:12 UTC, quadratz commented on site/docs/id/resources/comparison.md
> +Jika kamu ingin menggunakannya, maka gunakanlah, tapi pertimbangkanlah untuk mengatakan kalau kamu menyukai Rust hanya karena bahasanya dan Rust mungkin bukanlah alat yang tepat untuk pekerjaan terse
```suggestion
### Framework yang Ditulis Menggunakan Rust

[Sama dengan Go](#framework-yang-ditulis-menggunakan-go), tetapi Rust lebih unggul.
Kamu akan memerlukan lebih banyak waktu menulis menggunakan Rust, namun bot kamu juga akan lebih cepat tentunya.

Meski menggunakan Rust itu menyenangkan, namun membangun bot menggunakan Rust terlalu berlebihan.
Jika kamu ingin menggunakannya, maka gunakanlah, tetapi jika kamu menyukai Rust hanya karena bahasanya, mungkin Rust bukanlah alat yang tepat untuk pekerjaan tersebut.
```

2024-06-20 02:20 UTC, dzikrl commented on site/docs/id/resources/comparison.md
> +- Banyak hal lain seperti performa yang lebih baik, ekosistem plugin yang luas, dokumentasi yang telah diterjemahkan ke miliaran orang, integrasi dengan database dan framework web yang lebih baik, ko
@quadratz, how about this?

> integrasi dengan database dan framework web yang **lebih baik**, kompatibilitas runtime yang **lebih baik**

I'm running out of idea to reduce this repetition words.

2024-06-22 16:37 UTC, dzikrl commented on site/docs/id/resources/comparison.md
> +- Banyak hal lain seperti performa yang lebih baik, ekosistem plugin yang luas, dokumentasi yang telah diterjemahkan ke miliaran orang, integrasi dengan database dan framework web yang lebih baik, ko
I think it's okay.

2024-06-22 16:38 UTC, dzikrl commented on site/docs/id/resources/comparison.md
> +- Kamu mengenal Telegraf seperti punggung telapak tanganmu dan kamu tidak peduli untuk mengubah keahlianmu.
No, `seluk beluk` is the meaning. I just don't know how to figure it.

2024-06-22 16:39 UTC, dzikrl approved these changes

2024-06-23 13:26 UTC, quadratz approved these changes

2024-06-30 16:28 UTC, KnorpelSenf commented
Whoop whoop

2024-06-30 16:29 UTC, merged