Guard against other known limits
grammyjs/website pull request #1076
Opened 2024-06-16 20:09 UTC by KnorpelSenf

Triggered by https://t.me/tdlibchat/146123

2024-06-16 20:25 UTC, roj1512 commented on site/docs/advanced/flood.md
> +For instance, throttling your bot based on these number is still a bad idea:
What is that colon pointing to?

2024-06-16 20:27 UTC, KnorpelSenf commented on site/docs/advanced/flood.md
> +For instance, throttling your bot based on these number is still a bad idea:
The next section

2024-06-18 06:05 UTC, deptyped approved these changes

2024-06-19 10:42 UTC, quadratz requested changes

2024-06-19 10:42 UTC, quadratz commented on site/docs/id/advanced/flood.md
> +
```suggestion
Ada beberapa batasan lain yang tidak tertulis di dokumentasi resmi API Bot.
Contohnya, [sudah diketahui](https://t.me/tdlibchat/146123) bahwa bot hanya dapat mengedit maksimal 20 pesan dalam satu menit per obrolan grup.
Namun, batasan ini tidaklah selamanya benar, karena ia bisa saja berubah di masa mendatang.
Lagi pula, informasi ini tidak memberikan dampak apapun ke cara kamu memprogram bot.

Misalnya, memperlambat bot kamu berdasarkan angka di atas tetaplah ide yang buruk:

```

2024-06-20 01:03 UTC, dzikrl approved these changes

2024-06-23 13:08 UTC, quadratz approved these changes

2024-06-23 13:13 UTC, roziscoding approved these changes

2024-06-23 13:13 UTC, roziscoding commented on site/docs/advanced/flood.md
> +For instance, throttling your bot based on these number is still a bad idea:
```suggestion
For instance, throttling your bot based on this number is still a bad idea:
```

2024-06-23 22:41 UTC, KnorpelSenf commented on site/docs/advanced/flood.md
> +For instance, throttling your bot based on these number is still a bad idea:
Nice catch, I actually meant
```suggestion
For instance, throttling your bot based on these numbers is still a bad idea:
```

2024-06-23 22:42 UTC, roziscoding approved these changes

2024-06-29 22:22 UTC, merged