feat: add bun related docs
grammyjs/website pull request #1105
Opened 2024-07-30 09:18 UTC by stonega

2024-09-24 09:20 UTC, MasedMSD commented
@KnorpelSenf The issue of adding Bun is becoming more and more pressing. At the moment even plugin conversation, which could throw errors before, is working more and more stable.

+1 from me for adding documentation for Bun

Btw, many users from Russian-speaking chat also actively use it.

2024-09-24 09:26 UTC, KnorpelSenf commented
@winstxnhdw can you confirm that they have fixed their support for conversations, i18n, etc?

2024-09-24 09:27 UTC, MasedMSD commented on site/docs/guide/getting-started.md
> +Create a new empty text file, e.g. called `bot.ts`.
Aren't bun automatically creating index.ts if we `just press enter to accept the default answer for each prompt.`

2024-09-24 09:29 UTC, winstxnhdw commented
> @winstxnhdw can you confirm that they have fixed their support for conversations, i18n, etc?

Was i18n ever an issue?

2024-09-24 09:32 UTC, MasedMSD commented
> conversations

![image](https://github.com/user-attachments/assets/545622e1-d040-4edd-9523-1a075e642a9d)

2024-09-24 09:32 UTC, KnorpelSenf commented
I think all plugins compiled with dnt were, but I have never used bun, it's only what people reported

2024-09-24 09:32 UTC, KnorpelSenf commented
So they finally fixed it? That's pretty good!

2024-09-24 09:34 UTC, KnorpelSenf requested changes
Please also mention bun in https://grammy.dev/guide/introduction#prerequisites-to-getting-started

2024-09-24 09:35 UTC, KnorpelSenf commented
Actually, that section is pretty outdated anyway. Neither the part about Node nor the part about Deno are accurate anymore. I will fix things up in a subsequent PQ. We can keep this as-is for now.

2024-09-24 09:38 UTC, KnorpelSenf commented
@stonega what about https://grammy.dev/guide/api#type-definitions-for-the-bot-api?

2024-11-21 19:46 UTC, rojvv commented
Closing due to inactivity.

2024-11-21 19:46 UTC, closed without merging