Mention that bots have to be admin for reaction updates
grammyjs/website pull request #1130
Opened 2024-10-13 16:11 UTC by KnorpelSenf

As reported in https://t.me/grammyjs/274605

2024-10-13 16:13 UTC, Chinoman10 approved these changes
Looks good 👍 
Appreciate the quick turnaround!

2024-10-13 22:58 UTC, rojvv approved these changes

2024-10-14 05:28 UTC, MasedMSD approved these changes

2024-10-15 08:48 UTC, KnorpelSenf commented
Confer #1132

2024-10-18 10:55 UTC, quadratz requested changes

2024-10-18 10:55 UTC, quadratz commented on site/docs/es/guide/reactions.md
> +In addition, they **need to be enabled** via `allowed_updates`.
Umm, @habemuscode?

2024-10-26 05:43 UTC, quadratz approved these changes

2024-10-26 07:10 UTC, merged