docs: fix code example for similar commands
grammyjs/website pull request #1168
Opened 2024-12-16 17:45 UTC by eikowagenknecht

The previous example returned both messages when a command was found.

2024-12-16 18:25 UTC, roziscoding requested changes

2024-12-16 18:25 UTC, roziscoding commented on site/docs/plugins/commands.md
>      }
I'm a strong believer in early return over `else`. Please apply this to the other snippet too :)

```suggestion
    if (ctx.commandSuggestion) {
      // We found a potential match
      return ctx.reply(
        `Hmm... I don't know that command. Did you mean ${ctx.commandSuggestion}?`,
      );
    }
    
    // Nothing seems to come close to what the user typed
    await ctx.reply("Oops... I don't know that command :/");
```

2024-12-17 16:53 UTC, eikowagenknecht commented
Changed it to return early in both examples.

2024-12-17 20:31 UTC, roziscoding approved these changes

2024-12-17 20:33 UTC, KnorpelSenf requested changes
Can you change
```ts
return promise
```
to
```ts
await promise
return
```
in all cases? This implict promise handling is something experienced programmers might do sometimes as a micro optimisation, but it causes a large number of bugs for beginners.

2024-12-18 07:35 UTC, eikowagenknecht commented
Sure, I was just going with the suggestion of @roziscoding . I changed to a separate return in the if branch and left out the return at the end of the function now, as it would be meaningless.

2024-12-18 12:20 UTC, KnorpelSenf commented
@rojvv I took the liberty to sync everything, we can directly merge into `main` without doing any translations on an intermediate branch

2024-12-21 17:01 UTC, merged