Update menu docs
grammyjs/website pull request #118
Opened 2021-12-02 12:06 UTC by KnorpelSenf

Accounts for a few fixes including https://github.com/grammyjs/menu/issues/13, and adds more explanations.

2021-12-02 12:19 UTC, habemuscode approved these changes
LGTM

2021-12-02 16:07 UTC, rojserbest requested changes

2021-12-02 16:07 UTC, rojserbest commented on site/docs/plugins/menu.md
> +- The row/column position of the button
```suggestion
- The row/column position of the button.
```

2021-12-02 16:07 UTC, rojserbest commented on site/docs/plugins/menu.md
> +- The menu identifier
```suggestion
- The menu identifier.
```

2021-12-02 16:07 UTC, rojserbest commented on site/docs/plugins/menu.md
> +- An optional payload
```suggestion
- An optional payload.
```

2021-12-02 16:07 UTC, rojserbest commented on site/docs/plugins/menu.md
> +- A fingerprint flag that stores whether or not a fingerprint was used in the menu
```suggestion
- A fingerprint flag that stores whether or not a fingerprint was used in the menu.
```

2021-12-02 16:07 UTC, rojserbest commented on site/docs/plugins/menu.md
> +- A 4-byte hash that encodes either the fingerprint, or the menu layout and the button label
```suggestion
- A 4-byte hash that encodes either the fingerprint, or the menu layout and the button label.
```

2021-12-03 13:30 UTC, WingLim requested changes

2021-12-03 13:30 UTC, WingLim commented on site/docs/plugins/menu.md
> +- the shape of the menu changed (number of rows, or number of buttons in any row)
Upper the first word.
```suggestion
- The shape of the menu changed (number of rows, or number of buttons in any row)
```

2021-12-03 13:37 UTC, WingLim requested changes

2021-12-03 13:37 UTC, WingLim commented on site/docs/plugins/menu.md
> +It is also possible that your menu does not change fundamentally (i.e. the behavior of the handlers does not change), even though the above heuristic indicates indicates that the menu is outdates.
Repeated words.
```suggestion
It is also possible that your menu does not change fundamentally (i.e. the behavior of the handlers does not change), even though the above heuristic indicates that the menu is outdates.
```

2021-12-03 13:51 UTC, rojserbest approved these changes

2021-12-03 13:52 UTC, rojserbest commented
@WingLim you can approve too, if you have nothing left.

2021-12-03 13:54 UTC, KnorpelSenf commented
@WingLim nice catches! Thanks for reviewing even though you said once you did not want to! :D

I was mainly requesting you for the translation.

2021-12-03 13:56 UTC, WingLim approved these changes
Good to go now.

2021-12-03 13:57 UTC, merged