Add guide to writing plugins
grammyjs/website pull request #146
Opened 2021-12-10 15:56 UTC by KnorpelSenf

Based on https://github.com/Amir-Zouerami/plugin-template

2021-12-10 18:25 UTC, KnorpelSenf commented
I changed most lines, but almost none of the content. The only real difference is that I stripped down the middleware example a bit more.

There's currently an overlap between what we say in the “About Plugins” section and what we say in the early parts of this new guide. We need to figure out how those two documents are supporting each in other, instead of repeating each other.

Moreover, we currently have all the content of the guide in the README of the repo, too. This is not optimal, because while seemingly identical, the documents are going to diverge over time. We should figure out what to do with the README. I suggest to strip it down by a lot, and only reference this guide from now on. That's what is done with most other plugins etc.

2021-12-10 18:43 UTC, Amir-Zouerami commented
I suggest mixing the two pages together to get everything in one place because the "about plugins" page already talks about how to submit a plugin. I can cut down the README but what do you suggest to keep in? I would think that we keep "rules of contribution" and then say "go to this page for instructions on how to use this template repository". Just a suggestion.

2021-12-10 18:50 UTC, KnorpelSenf commented
> I suggest mixing the two pages together to get everything in one place

I disagree. There are two kinds of readers, plugin users (includes newcomers who don't have a clue) and people who know the framework to some extent and want to contribute a plugin. It's much easier to target those two groups individually.

It would be easier to take out the first section of the new guide and rather link to the About Plugins section, saying it is a prerequisite to writing plugins. (Maybe we should actually also link to middleware and transformers in the respective sections, just to make sure people know what they need to know before writing a plugin.)

> I would think that we keep "rules of contribution" and then say "go to this page for instructions on how to use this template repository".

That sounds good! Let's do it that way.

2021-12-10 19:14 UTC, Amir-Zouerami commented
The README is trimmed down.

> I disagree. There are two kinds of readers, plugin users (includes newcomers who don't have a clue) and people who know the framework to some extent and want to contribute a plugin. It's much easier to target those two groups individually.

The developing part of plugins is kind of tied to understanding them. How about we transfer the following sections to the "about the plugins":
- What Is a Plugin?
- Types of Plugins in grammY (minus the stuff about how "your plugin should return this and that").

Since we link the words "middleware" and "transformer", readers can click on and check what they are if they're unfamiliar with them. Then in the hitchhiker's section we can add a summary of two types of plugins (link them to "about plugins") and carry on with "Rules of Contribution".

2021-12-10 19:17 UTC, KnorpelSenf commented
I like that, that sounds good. That way, we can have everyone read the about section, and those who are interested in writing a plugin can read on.

Do you want to do the restructuring?

2021-12-10 19:19 UTC, Amir-Zouerami commented
> Do you want to do the restructuring?

I will. I'll let you know when it's finished.

2021-12-10 19:21 UTC, Amir-Zouerami commented
> Nice one, did not think about this

 Some guy name Dunkan in the Telegram group gave me the idea. All credits to him.

2021-12-10 19:22 UTC, KnorpelSenf commented
Thanks @dcdunkan :+1:

2021-12-11 12:49 UTC, Amir-Zouerami commented
I restructured [README ](https://github.com/grammyjs/website/commit/fe98a7d5bbb3736e2968c1e5dee34433749bfa72) and the [guide](https://github.com/grammyjs/website/commit/9a8b1877aba188b2a1a7a2d9429616a53033c847). Let me know what you think.

2021-12-11 13:41 UTC, KnorpelSenf commented
Thanks a bunch! I generally agree with this structure. There are a few minor refinements I'd like to have here and there, but I'll just rephrase those parts myself (I think that would take as much time as writing down here what I have in mind).

2021-12-11 14:35 UTC, Amir-Zouerami commented
great 👍

2021-12-15 12:52 UTC, Amir-Zouerami approved these changes
Well done on brushing the details especially making deno mandatory for official plugins. I wanted to do that but thought that you might not like it. Go ahead and merge whenever you're ready.

Nice job everyone who helped👍🏻

2021-12-15 13:06 UTC, KnorpelSenf commented
> making deno mandatory for official plugins

This has already been required by https://github.com/grammyjs/grammY/blob/main/CONTRIBUTING.md#how-to-contribute for a long time, it is just a lot more visible now :)

We need to wait for translations.

2021-12-15 15:23 UTC, roj1512 approved these changes

2021-12-18 07:35 UTC, WingLim requested changes

2021-12-18 07:35 UTC, WingLim commented on site/docs/plugins/guide.md
> +import { onlyAccept } from "./testing.ts";
Here should be `plugin.ts`.
```suggestion
import { onlyAccept } from "./plugin.ts";
```

2021-12-18 07:35 UTC, WingLim commented on site/docs/plugins/guide.md
> +    // Let through all matching updates
Add period.
```suggestion
    // Let through all matching updates.
```

2021-12-18 07:35 UTC, WingLim commented on site/docs/plugins/guide.md
> +  // Create and return a transformer function
Add period.
```suggestion
  // Create and return a transformer function.
```

2021-12-18 07:35 UTC, WingLim commented on site/docs/plugins/guide.md
> +    // Save the handle of the set interval so we can clear it later
Add period.
```suggestion
    // Save the handle of the set interval so we can clear it later.
```

2021-12-18 07:51 UTC, roj1512 commented
About the failed format in the latest commit: I don't get that when I format locally. Maybe it is because of the Deno version?

2021-12-18 08:03 UTC, roj1512 commented on site/docs/zh/plugins/guide.md
> +If you have a plugin ready, you may simply submit a pull request on GitHub (according to the [Rules of Contribution](#rules-of-contribution)), or notify us in the [community chat](https://t.me/grammy
Did you miss translating here?

2021-12-18 08:04 UTC, WingLim commented on site/docs/zh/plugins/guide.md
> +If you have a plugin ready, you may simply submit a pull request on GitHub (according to the [Rules of Contribution](#rules-of-contribution)), or notify us in the [community chat](https://t.me/grammy
Sorry, forgot to remove it.

2021-12-18 08:05 UTC, WingLim commented
> About the failed format in the latest commit: I don't get that change when I format locally. Maybe it is because of the Deno version of the formatting workflow?

The CI is pass in #162 , why failed in here?

2021-12-18 08:06 UTC, WingLim approved these changes

2021-12-18 08:06 UTC, roj1512 commented
@WingLim no idea. But can you try making the change the CI error requested manually?

2021-12-18 08:15 UTC, WingLim commented
@roj1512 The problem is I don't know why it failed.
And the most wired thing is, the error line did not show up in this PR, it's in #162 or in the main branch.

2021-12-18 08:30 UTC, roj1512 commented
@WingLim See the details here: https://github.com/grammyjs/website/runs/4568515512?check_suite_focus=true

2021-12-18 08:33 UTC, roj1512 commented
@WingLim Try making this change manually.
![image](https://user-images.githubusercontent.com/49933115/146634930-4120dea6-d6ee-45e8-8fe2-bd0e7f4dfa8e.png)

2021-12-18 08:35 UTC, WingLim commented
@roj1512 But this line did not exist in this branch...

2021-12-18 08:56 UTC, roj1512 commented
Thanks, @WingLim!

2021-12-18 08:57 UTC, merged