Short Version of PM2 Changes
grammyjs/website pull request #164
Opened 2021-12-13 19:29 UTC by Tecardo1

2021-12-14 10:20 UTC, rojserbest requested changes

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +## PM2 PROCESS MANAGER (NODE only)
```suggestion
## PM2 (Node.js only)
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +PM2 is a daemon process manager that will help you manage and keep your application online 24/7
```suggestion
PM2 is a daemon process manager for Node.js that will help you manage and keep your app online 24/7.
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +
```suggestion

> The `<app_name>` can be any identifier to your app, for example: `bot1`.  
> The `<entry_point>` should be the path to your index file (which runs your bot). 
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +# Start a simple process <entry_point> is your file location
```suggestion
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +#### Reloading an app:
```suggestion
#### Reload
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +#### Restarting an app:
```suggestion
#### Restart
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +Restart stops all processes of this app first and then starts it again.
```suggestion
By restarting, you stop the app, and start it again.
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +Reload first starts a new process before stopping the other processes resulting in 0-second-downtime. Recommended for stateless applications.
```suggestion
By reloading, you replace the current process of your app with a new one, resulting in a 0-second downtime. This is recommended for stateless applications.
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +#### Stopping an app:
```suggestion
#### Stop
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +# Stopping an app with its name
```suggestion
# A single app
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +# Stopping every app launched by pm2
```suggestion

# All apps
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +#### Deleting an app:
```suggestion
#### Delete
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +Also stops the app and deletes its logs and metrics
```suggestion
By deleting, you stop your app and remove its logs and metrics.
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +- Management of Processes: <https://pm2.keymetrics.io/docs/usage/process-management/>
```suggestion
For more, please refer to https://pm2.keymetrics.io/docs.
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +- Logs: <https://pm2.keymetrics.io/docs/usage/log-management/>
```suggestion
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +- Startup Script: <https://pm2.keymetrics.io/docs/usage/startup/>
```suggestion
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +- Graceful start and stop: <https://pm2.keymetrics.io/docs/usage/signals-clean-restart/>
```suggestion
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +#### Starting an app:
```suggestion
#### Start
```

2021-12-14 10:20 UTC, rojserbest commented on site/docs/hosting/vps.md
> +### Managing the pm2 process
```suggestion
### Managing the app
```

2021-12-14 10:48 UTC, rojserbest approved these changes

2021-12-18 05:28 UTC, WingLim approved these changes

2021-12-18 06:53 UTC, merged