uz/advanced/readme
grammyjs/website pull request #221
Opened 2022-01-28 06:16 UTC by mcpeblocker

2022-01-28 16:57 UTC, sad1go0 commented on site/docs/uz/advanced/README.md
> +Va nihoyat biz siz uchun botingizni ishga tushirayotganda [esingizda tutishingiz kerak bo'lgan ba'zi bir narsalarni](./deployment.md) tayyorlaganmiz.
narsalarni -> ma'lumotlarni

2022-01-28 16:57 UTC, sad1go0 commented on site/docs/uz/advanced/README.md
> +Bu yerda hech qanday yangi narsa kiritilgan emas, bu shunchaki taxminiy muammolarning markazlashtirilgan holdagi jamlanmasi.
narsa -> ma'lumot

2022-01-28 17:00 UTC, sad1go0 requested changes
Perfect!

2022-01-29 12:17 UTC, sad1go0 approved these changes

2022-01-29 12:18 UTC, merged

2022-01-29 14:11 UTC, KnorpelSenf commented
You're making good progress! Keep up the good work—and remember to delete your branches when a PR is merged 😉

Optionally, you may want to check out the GitHub Refined browser extension which does this automatically for you (but only if you feel like using it).