Update deployment.md
grammyjs/website pull request #247
Opened 2022-02-19 08:31 UTC by PavelPolyakov

Link an example of the bot covered with tests

2022-02-19 14:33 UTC, roj1512 reviewed
I prefer putting a link to the test file in your repository, put it in the “Contribute a Testing Framework”, and talk about it as if it is an example how tests could be done. I’d also like to know @KnorpelSenf’s opinion.

2022-02-19 18:42 UTC, KnorpelSenf commented
I tend to agree, but I'll leave the choice up to you guys.

2022-02-19 20:11 UTC, PavelPolyakov commented
I moved it to the tip section. Though I linked the whole repository, this gives an option to update repository without updating this documentation. I think it's fine, since that repo has proper `README.md`.

2022-02-19 20:13 UTC, roj1512 requested changes

2022-02-19 20:13 UTC, roj1512 commented on site/docs/advanced/deployment.md
> +[Example](https://github.com/PavelPolyakov/grammy-with-tests), which shows how tests could be done.
```suggestion
An example on how tests could be done [can be found here](https://github.com/PavelPolyakov/grammy-with-tests/blob/master/__tests__/bot.test.js).
```

2022-02-19 20:15 UTC, roj1512 approved these changes

2022-02-23 10:09 UTC, WingLim approved these changes
Done

2022-02-23 10:10 UTC, merged