Better emoji plugin documentation
grammyjs/website pull request #268
Opened 2022-03-28 17:21 UTC by andrrms

This includes better documentation and keeps up with changes proposed [here](https://github.com/grammyjs/emoji/pull/9)

2022-03-28 18:57 UTC, roj1512 requested changes

2022-03-28 18:57 UTC, roj1512 commented on site/docs/plugins/emoji.md
> +Now, whenever you want, you can get an emoji by name like this:
```suggestion
Now you can get emojis by names like this:
```

2022-03-29 09:49 UTC, roj1512 approved these changes

2022-03-29 10:03 UTC, KnorpelSenf commented
The changes at https://github.com/grammyjs/emoji/pull/9 are unlikely to be merged. This PQ needs to be reduced to the improvements unrelated to the aforementioned PQ.

2022-03-29 11:27 UTC, roj1512 commented
@andrrms I think it might be better to open documentation update PRs only when the current one is outdated (=after you have already made an update to your plugin), or maybe just mark it as a draft until the update on the other side (the side the documentation talks about, which is your plugin in this context) is complete.

2022-04-13 13:49 UTC, roj1512 approved these changes

2022-04-13 13:59 UTC, merged

2022-04-13 14:02 UTC, roj1512 commented
@andrrms Good move.

2022-04-13 14:07 UTC, KnorpelSenf commented
I think we need to communicate to everyone that they are not supposed to merge their own PQs. This happened repeatedly by different people now, so it looks like no one knows

2022-04-13 14:08 UTC, roj1512 commented
Should I tag everyone in the chat and tell them?

2022-04-13 14:13 UTC, WingLim commented
> > @andrrms ~Machiavélique~ move.
> 
> I saw a big shiny green button and no warning that I shouldn't merge yet, sorry about that 😅

It doesn't matter, you did a great job already.