Update throttler docs to use runner to strongly suggest the use of a concurrent update handling mechanism
grammyjs/website pull request #271
Opened 2022-04-08 01:34 UTC by KnightNiwrem

2022-04-08 01:48 UTC, KnorpelSenf requested changes
Thanks!

Tiny typo:

2022-04-08 01:48 UTC, KnorpelSenf commented on site/docs/plugins/transformer-throttler.md
> +// If you are using throttler, you most likely want to use a runner to handle update concurrently
```suggestion
// If you are using throttler, you most likely want to use a runner to handle updates concurrently
```

2022-04-08 01:48 UTC, KnorpelSenf commented on site/docs/plugins/transformer-throttler.md
> +// If you are using throttler, you most likely want to use a runner to handle update concurrently
```suggestion
// If you are using throttler, you most likely want to use a runner to handle updates concurrently
```

2022-04-08 01:48 UTC, KnorpelSenf commented on site/docs/plugins/transformer-throttler.md
> +// If you are using throttler, you most likely want to use a runner to handle update concurrently
```suggestion
// If you are using throttler, you most likely want to use a runner to handle updates concurrently
```

2022-04-08 01:55 UTC, KnorpelSenf approved these changes
LGTM

2022-04-08 01:56 UTC, merged

2022-04-08 02:01 UTC, KnorpelSenf commented
This wasn't supposed to be merged.

I have a suspicion that the standard comment format is different and that things should be aligned for consistency, but @roj1512 knows best about this.

We also need to update translations after @roj1512 has reviewed.

All follow-up changes can be performed in a new PQ, I restored the branch.

2022-04-08 09:13 UTC, KnightNiwrem commented
> This wasn't supposed to be merged.
> 
> I have a suspicion that the standard comment format is different and that things should be aligned for consistency, but @roj1512 knows best about this.
> 
> We also need to update translations after @roj1512 has reviewed.
> 
> All follow-up changes can be performed in a new PQ, I restored the branch.

Whoops. Is there any way to implement some kind of PQ checklist mechanism to make it clear that the PQ handling is different here?

2022-04-08 09:22 UTC, KnorpelSenf commented
There's not a checklist of tasks to do, but rather a distribution of responsibilities between several people. After a contribution, they take over with their well-established process. You can read more about this in the contribution guide, but the TL;DR is: perform the changes to the content, the rest will be taken care of.

2022-04-10 15:23 UTC, KnorpelSenf commented
@roj1512 @WingLim can you take care of this?