[Feat] [Translations] [Spanish]: plugins/guide
grammyjs/website pull request #347
Opened 2022-05-12 13:15 UTC by habemuscode

2022-05-12 13:20 UTC, KnorpelSenf commented
@habemuscode please merge `main` to fix the timeout problem.

2022-05-12 14:07 UTC, roj1512 requested changes

2022-05-12 14:07 UTC, roj1512 commented on site/docs/es/plugins/guide.md
> +Si tienes un plugin listo, puedes simplemente enviar un pull request en GitHub (de acuerdo con las [Reglas de Contribución](#rules-of-contribution)), o notificarnos en el [chat de la comunidad](https
```suggestion
Si tienes un plugin listo, puedes simplemente enviar un pull request en GitHub (de acuerdo con las [Reglas de Contribución](#reglas-de-contribucion)), o notificarnos en el [chat de la comunidad](https://t.me/grammyjs) para más ayuda.
```

2022-05-13 16:56 UTC, roj1512 approved these changes

2022-05-13 16:56 UTC, merged