Update styles for inline code in tables
grammyjs/website pull request #383
Opened 2022-05-23 22:19 UTC by Loskir

See /guide/filter-queries.html#query-structure

2022-05-23 22:42 UTC, KnorpelSenf requested changes

2022-05-23 22:42 UTC, KnorpelSenf commented on site/docs/.vuepress/styles/index.scss
> +html.dark tr:nth-child(2n) {
```suggestion
// adjust table background colors to avoid clashes with inline code snippets
html.dark tr:nth-child(2n) {
```

2022-05-23 22:43 UTC, KnorpelSenf approved these changes

2022-05-24 07:49 UTC, roj1512 approved these changes
Thanks for spotting it!

2022-05-24 07:50 UTC, merged