Add section about when to use sessions
grammyjs/website pull request #405
Opened 2022-05-26 12:02 UTC by KnorpelSenf

Closes #170.

2022-05-26 13:31 UTC, Loskir approved these changes

2022-05-26 13:37 UTC, roj1512 commented on site/docs/plugins/session.md
> +It will loading it from the database before our middleware runs.
```suggestion
It will be loading it from the database before our middleware runs.
```

2022-05-26 13:39 UTC, roj1512 requested changes

2022-05-26 13:39 UTC, roj1512 commented on site/docs/plugins/session.md
> +And your are right—sessions are an ideal solution, but only for some types of data.
```suggestion
And you are right—sessions are an ideal solution, but only for some types of data.
```

2022-05-27 06:54 UTC, roj1512 approved these changes

2022-05-27 21:35 UTC, habemuscode approved these changes

2022-05-28 15:11 UTC, roj1512 approved these changes

2022-05-28 15:11 UTC, merged

2022-05-28 22:58 UTC, KnorpelSenf commented
Is your extension broken? The branch did not get deleted

2022-05-29 05:41 UTC, roj1512 commented
Idk. It's enabled.