Mention the rutime process implicitly
grammyjs/website pull request #421
Opened 2022-06-05 14:31 UTC by roj1512

2022-06-05 15:23 UTC, CikiMomogi requested changes

2022-06-05 15:23 UTC, CikiMomogi commented on site/docs/advanced/reliability.md
> +// Stopping the bot when process
Stopping the bot when `the` process

2022-06-05 15:27 UTC, roj1512 commented on site/docs/advanced/reliability.md
> +// Stopping the bot when process
Ah my bad

2022-06-05 15:43 UTC, CikiMomogi approved these changes
LGTM!

2022-06-06 13:32 UTC, habemuscode approved these changes

2022-06-06 14:12 UTC, roj1512 commented on site/docs/es/plugins/runner.md
> +Para que el bot complete su trabajo correctamente, debes indicarle (../advanced/reliability.md#using-grammy-runner) que se detenga cuando el proceso esté a punto de ser destruido.
@habemuscode This is a broken link btw.

2022-06-09 16:14 UTC, habemuscode commented on site/docs/es/plugins/runner.md
> +Para que el bot complete su trabajo correctamente, debes indicarle (../advanced/reliability.md#using-grammy-runner) que se detenga cuando el proceso esté a punto de ser destruido.
Ups, fixed and other link also :)

2022-06-14 18:32 UTC, roj1512 commented
It was originally to remove the term "Node process" in the Deno code block.

2022-06-14 18:40 UTC, KnorpelSenf commented
> It was originally to remove the term "Node process" in the Deno code block.

I would prefer if we could simply fix that oversight and refer to the Deno process.

2022-06-14 19:40 UTC, KnorpelSenf approved these changes
Thanks!

2022-06-22 18:35 UTC, habemuscode approved these changes

2022-06-22 18:51 UTC, merged