Document `ctx.entities`
grammyjs/website pull request #497
Opened 2022-09-05 23:27 UTC by roziscoding

2022-09-05 23:27 UTC, roziscoding commented
Related to https://github.com/grammyjs/grammY/pull/276

2022-09-06 11:20 UTC, KnorpelSenf requested changes

2022-09-06 11:56 UTC, KnorpelSenf approved these changes
Please fix CI, otherwise LGTM

2022-09-06 11:57 UTC, roziscoding commented
> Please fix CI

I was on my way to see why it broke when things caught fire lol

2022-09-06 11:58 UTC, roziscoding commented
![image](https://user-images.githubusercontent.com/3948961/188629177-b818bbc1-3ae6-42b7-ad48-25590139e421.png)
🙃

2022-09-06 11:59 UTC, KnorpelSenf commented
That's my fault because my suggestion didn't have the right line width for the table. For once it's not GitHub that screwed up 🥲

2022-09-06 11:59 UTC, KnorpelSenf commented
> ![image](https://user-images.githubusercontent.com/3948961/188629177-b818bbc1-3ae6-42b7-ad48-25590139e421.png) 🙃

Oh wait what

2022-09-06 12:01 UTC, roziscoding commented
`deno fmt` to the rescue

2022-09-06 12:02 UTC, KnorpelSenf approved these changes
Thanks!

2022-09-06 12:31 UTC, roj1512 commented on site/docs/guide/context.md
> +  // Gets the text for the first entity
```suggestion
  // Get the first entity's text
```

2022-09-06 12:31 UTC, roj1512 commented on site/docs/guide/context.md
> +  // Get all entities present in the message text
```suggestion
  // Get all the entities.
```

2022-09-06 12:32 UTC, roj1512 commented on site/docs/guide/context.md
> +  // Get emails present in the message text
```suggestion
  // Get email entities.
```

2022-09-06 12:32 UTC, roj1512 commented on site/docs/guide/context.md
> +  // Get phones and emails present in the message text
```suggestion
  // Get phone and email entities.
```

2022-09-06 15:49 UTC, roj1512 approved these changes
It is unquestionable like this, thank you!

2022-09-06 16:05 UTC, KnorpelSenf commented
This can be fully translated, but it should not be published before the 1.12 release since the code should ideally be shipped before we roll out new docs.

2022-09-06 23:46 UTC, fadzikri commented
@CikiMomogi Where should i review that changes?

2022-09-07 00:07 UTC, fadzikri approved these changes
Okay, it's seems good.

2022-09-16 09:12 UTC, habemuscode approved these changes

2022-09-17 10:49 UTC, roj1512 approved these changes

2022-09-19 18:27 UTC, KnorpelSenf commented
Great idea with the label, thanks!

2022-12-30 16:57 UTC, KnorpelSenf commented
@roj1512 this can be merged after Chinese is removed. The respective feature has landed in the core library.

2022-12-30 17:03 UTC, merged