Inline API reference
grammyjs/website pull request #532
Opened 2022-10-25 21:29 UTC by KnorpelSenf

Work in progress.

Pending tasks:
- [ ] replace links to inlined API reference
- [ ] create TOC for each path, such as `/api/core`
- [ ] complete info for classes
- [ ] add pages for all other types of exports (see commented out parts)
- [ ] decide how to handle clashes
- [ ] support `/types.ts`
- [ ] fix loads of details in the docs, such as link highlighting, cross-references between API objects, and likely a lot more

2022-10-25 21:34 UTC, KnorpelSenf commented
https://635855ed09e68c00648923df--grammy.netlify.app/api/core/Bot.html

2022-11-14 23:23 UTC, KnorpelSenf commented
https://6372cc78d06d6331bdcaae80--grammy.netlify.app/ref/api/File.html

2022-12-03 20:03 UTC, KnorpelSenf commented
The goal of this is to deliver quality that's at least on par with Deno. We won't merge this before we're satisfied. We're trying to solve the following problems:

- the search on our page doesn't index the API reference of the core lib or the plugins
- navigating to the API reference leaves the page
- following a docs link inside the reference leaves the page again
- the API reference is hard to find because it's on a different origin
- the docs bot cannot send links to the API reference
- it's not obvious where the methods on https://core.telegram.org/bots/api are reflected in our docs so they're hard to find

It just helps to deliver an integrated experience.

2023-01-09 20:24 UTC, KnorpelSenf commented
If I'm honest, it is quite convenient that the Deno docs pages are getting better and better over time. I don't enjoy replicating their work here. Markdown is pretty constrained, and by now they also finally added a great search feature. Also, if we were to land this, we'd have to constantly work on this code and improve it. There are more downsides to this approach (in addition to it being a lot of work):
- cannot be translated, which is inconsistent
- worse/missing integration with the actual code
- hard to view docs of old versions (so the Deno docs would never be completely dispensable)
- constrained by the features of markdown (Deno docs can choose an arbitrary layout)
- must be adjusted when new TS features are released, in contrast to Deno docs which receive this feature automatically as soon as Deno is updated

I just feel like there are way cooler things to spend my time on (such as actual library innovation). Hence, I will close this. If anyone finds good reasons for picking this up again (and wants to invest the time), feel free to drop a comment so we restore the branch and let you continue.

2023-04-08 07:46 UTC, KnorpelSenf commented
> by now they also finally added a great search feature

The search was removed by them.

> * worse/missing integration with the actual code

This is not correct. Instead of pulling the API reference from Deno, we can do it from GitHub. This will give us links to the source on GitHub, which is even better than links to the code at /x.

> * hard to view docs of old versions (so the Deno docs would never be completely dispensable)

This is a good point, but let's be honest: how often are people interested in outdated docs? Basically only when using outdated major versions. This can be fixed by including docs for all latest versions of each major version. This sounds feasible to me.

> * constrained by the features of markdown (Deno docs can choose an arbitrary layout)
> * must be adjusted when new TS features are released, in contrast to Deno docs which receive this feature automatically as soon as Deno is updated

In fact, this is only true when we use new TS features. In the past two years, this has happened maybe once or twice. So while this point still stands, it's scope is very limited.

> I just feel like there are way cooler things to spend my time on (such as actual library innovation).

It turns out that by not working on this, I will instead spend my time explaining to people in the chat that the API reference exists, which I enjoy even less.

2023-06-09 08:51 UTC, KnorpelSenf commented
There's another reason to pick this up again. Some people who do not use Deno are confused if they have to visit a Deno website in order to read docs. It's not intuitive that these docs work for Node, too. We fix this by integrating the docs into our website.

2023-06-20 19:49 UTC, roj1512 requested changes
Resolve the conflicts, please.

2023-06-20 22:42 UTC, KnorpelSenf commented
Will do

2023-06-20 22:43 UTC, KnorpelSenf commented
Do you think it's feasible to implement this solely with markdown? If we want to be as good as /x then we either have to become markdown design wizards, or start creating a few Vue components to properly layout the API reference pages.

2023-06-22 14:27 UTC, KnorpelSenf commented
There are many things to display:
- doc string and params docs
- name, params, return type, generics
- optionally, an overview for classes and methods etc
- link to the source code on GitHub
- how to import
- type of the symbol

I'm not sure how to organise this.

2023-06-30 12:48 UTC, KnorpelSenf commented
We could see if it's possible to infer all properties of `other` types, so we can get an exhaustive option list per method.

2023-11-23 17:08 UTC, roj1512 commented on site/docs/.vitepress/config.ts
> +
```suggestion
```

2023-12-11 16:07 UTC, quadratz commented
https://t.me/grammyjs/184409
> Following direct links like [this one](https://655d0358e48e77008171630a--grammy.netlify.app/ref/core/GrammyError#description) will break the page layout upon navigation.

PQ https://github.com/grammyjs/website/pull/959, will fix the issue. (hopefully)

2023-12-12 09:37 UTC, KnorpelSenf commented
> [t.me/grammyjs/184378](https://t.me/grammyjs/184378)
> 
> > Following direct links like [this one](https://655d0358e48e77008171630a--grammy.netlify.app/ref/core/GrammyError#description) will break the page layout upon navigation.
> 
> @KnorpelSenf, PQ #959 will fix the issue

That is very interesting … why does it fix that? Can you provide a link to the changes that affect this?

2023-12-12 13:20 UTC, quadratz commented
> That is very interesting … why does it fix that? Can you provide a link to the changes that affect this?

I'm not certain, though. After updating VitePress and running the debug, the issue disappeared. The package hasn't been updated for 5 months, so there might have been many improvements during that time.

2023-12-12 13:26 UTC, KnorpelSenf commented
Fair enough, I'll take that. It did seem a bit like a vitepress bug anyway. So let's just get #959 merged and then we can check if that took care of problem 5 in https://t.me/grammyjs/184378 for us.

2023-12-14 23:08 UTC, KnorpelSenf commented
@roj1512 this makes no sense, we have to do a larger restructuring. It should be:
```
API ref
 - core
 - types
 - plugin0
 - plugin1
 - plugin2
```
Path structure can remain the same.

Main difference being that:
1. the UI lets us navigate from grammy.dev to API ref to plugin reference
2. we don't generate 20+ independent refs, one for each module, because they constantly link to each other, so we have to build a global index of symbols first and then we can insert cross-references.

I see this as the only way to address

> [ ] cross-package references such as `RawApi` in `files/hydrateFiles` currently 404

and also it will improve the discoverability of the plugin refs and the types ref.

2023-12-14 23:09 UTC, KnorpelSenf commented
As a side-effect, it will enable us to de-dupe function overloads. This will fix

> * [ ]  function overloads such as for `webhookCallback` are broken

2024-03-14 23:25 UTC, KnorpelSenf commented
This needs some more effort. Damn.

2024-03-15 19:08 UTC, roziscoding commented
Can we deploy this again?

2024-03-15 20:10 UTC, KnorpelSenf commented
Not easily. I'm currently working on the auto-retry plugin. Once it has a proper Deno build, we can generate docs for it again.

However, the autoquote plugin recently broke things because it uses an `npm:` import. Since it's a third-party plugin, we might as well skip generating the docs for it. I do not see a way how we could support it, unless we remove the `npm:` import from it again.

Once these two plugins are fixed, we can commence work on the remaining tasks.

Until then, you can just look at the most recent deployment.

2024-03-17 10:04 UTC, KnorpelSenf commented
@roziscoding we can deploy again

2024-03-17 18:00 UTC, roj1512 approved these changes

2024-03-17 21:48 UTC, KnorpelSenf commented
LGTM

2024-03-17 21:48 UTC, merged