Fix comments
grammyjs/website pull request #558
Opened 2022-11-30 14:36 UTC by habemuscode

Fix the following comments:

- https://github.com/grammyjs/website/pull/442#pullrequestreview-1195844440
- https://github.com/grammyjs/website/pull/555#discussion_r1033581869
- https://github.com/grammyjs/website/pull/505#discussion_r1033687861
- https://github.com/grammyjs/website/pull/505#discussion_r1033688382
- https://github.com/grammyjs/website/pull/505#discussion_r1033689138

2022-11-30 16:51 UTC, roj1512 commented
Undraft this?

2022-11-30 18:14 UTC, habemuscode commented
@roj1512 I will do when receive answer in the group to include extra fix or not

2022-11-30 18:52 UTC, roj1512 approved these changes
LGTM. Thank you so much!

2022-12-01 00:23 UTC, CikiMomogi requested changes

2022-12-01 00:23 UTC, CikiMomogi commented on site/docs/es/hosting/fly.md
> +# Simplemente omitiendo toda la sección de [[servicios]] ya que no estamos escuchando HTTP.
```suggestion
# Simplemente omitiendo toda la sección de [[services]] ya que no estamos escuchando HTTP.
```

2022-12-01 15:21 UTC, roj1512 approved these changes

2022-12-02 00:54 UTC, CikiMomogi approved these changes

2022-12-02 07:56 UTC, merged