feat: re-add Chinese translations
grammyjs/website pull request #596
Opened 2023-02-09 22:19 UTC by KnorpelSenf

2023-02-10 21:38 UTC, KnorpelSenf commented
@roj1512 what can we do about the memory consumption? This did not happen back in the days, did it?

2023-02-11 07:03 UTC, roj1512 commented
@KnorpelSenf It’s my first time seeing it. Maybe we can do something to stop pending builds when there’s a new commit pushed. I think they do something like that in Deno’s https://github.com/denoland/deno repository.

2023-02-11 07:03 UTC, roj1512 commented
https://github.com/denoland/deno/blob/211f49619afd915a2ce56cf0b5da50f640c90f73/.github/workflows/ci.yml#L18

2023-02-11 09:28 UTC, roj1512 commented
Huh it seems not related

2023-02-11 09:40 UTC, KnorpelSenf commented
Let's just throw more memory at the problem.

2023-03-04 12:28 UTC, CikiMomogi commented
I have listed the pull requests that have the label "ready for translation" from commit 48aa7020 (the first commit since ZH was removed) to date. Hope this helps.

To do list:
- [ ] #530
- [ ] #502 
- [ ] #513 
- [ ] #506 
- [ ] #518 
- [ ] #536 
- [ ] #545 
- [ ] #442 
- [ ] #505 
- [ ] #511
- [ ] #558 
- [ ] #560 
- [ ] #561 
- [ ] #564 
- [ ] #563
- [ ] #557 
- [ ] #520 
- [ ] #497 
- [ ] #568 
- [ ] #572 
- [ ] #576 
- [ ] #556 
- [ ] #579 
- [ ] #578 
- [x] #594 
- [ ] #589 
- [x] #597 
- [x] #626 
- [x] #559 
- [x] #587 
- [x] #585 
- [ ] #642 
- [ ] #641 
- [ ] #590
- [ ] #625

2023-03-04 12:49 UTC, CikiMomogi requested changes
#585

2023-03-04 12:49 UTC, CikiMomogi commented on site/docs/zh/plugins/chat-members.md
> +你可以使用有效的 grammY [存储适配器](./session.md#known-storage-adapters) 或任何实现 [`StorageAdapter`](https://deno.land/x/grammy/mod.ts?s=StorageAdapter) 接口的类的实例。
Broken link `./session.md#known-storage-adapters`

2023-03-06 12:04 UTC, roj1512 approved these changes
LGTM.

2023-03-06 12:05 UTC, merged