Add `README.md` Ukranian localization
grammyjs/website pull request #643
Opened 2023-03-04 00:17 UTC by LWJerri

Hello dear translators! First, I have a question about plugin names in the table. Do I need to translate names?

2023-03-04 04:27 UTC, Nazar-Ant commented
Вважаємо читача поважною особою, що звертаємося до нього на "ви" з великої букви? В принципі можна так звертатися в документації.

2023-03-04 08:49 UTC, deptyped requested changes

2023-03-04 08:49 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +Ми хочемо, щоб grammY був лаконічним та мінімальним, але розширюваним.
```suggestion
Ми хочемо, щоб grammY був компактним та мінімалістичним, але мав можливість розширення.
```

2023-03-04 08:49 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +Деякі плагіни одразу **вбудовано** до основної бібліотеки grammY, оскільки ми припускаємо можливості, що вони потрібні багатьом ботам.
```suggestion
Деякі плагіни **вбудовані** безпосередньо до бібліотеки grammY, оскільки ми вважаємо, що вони потрібні багатьом ботам.
```

2023-03-04 08:49 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +Ми координуємо їхні релізи з релізами grammy і стежимо за тим, щоб все працювало злагоджено.
```suggestion
Ми координуємо їхні релізи з релізами grammY і стежимо за тим, щоб вони працювали добре разом.
```

2023-03-04 08:49 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +(Якщо ви використовуєте Deno пакет, а не Node.js, вам слід імпортувати плагін з <https://deno.land/x/>, тобто з файлу `mod.ts` модуля `grammy_runner`).
```suggestion
(Якщо ви використовуєте Deno, а не Node.js, вам слід імпортувати плагін з <https://deno.land/x/>, тобто з файлу `mod.ts` модуля `grammy_runner`).
```

2023-03-04 08:49 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +Якщо ви хочете, Ваш власний, сторонній, плагін також можна розмістити на сайті, аби про нього дізналося більше людей.
```suggestion
Ви також можете розмістити свій власний плагін на сайті, щоб про нього дізналися більше людей.
```

2023-03-04 08:49 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +Встановлювати плагіни весело і легко, і ми хочемо, щоб ви знали, що ми маємо для Вас.
```suggestion
Встановлювати плагіни весело і легко, тому ми хочемо, щоб ви знали, які плагіни у нас для Вас є.
```

2023-03-04 08:49 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +Це означає, що ви встановлюєте їх через `bot.api.config.use`.
Я думаю, ми не повинні перекладати middleware і tranformers. Для цих слів немає сталого перекладу, а писати їх транслітом немає сенсу. Краще залишити їх англійською, що думаєте?

```suggestion
### Тип I: Middleware плагіни

[Middleware](../guide/middleware.md) - це функція, яка здійснює обробку вхідних даних у різноманітних формах.
Middleware плагіни встановлюються в бота, як ви вже здогадалися, як middleware.
Це означає, що вам потрібно встановлювати їх через `bot.use`.

### Тип II: Transformer плагіни

[Transformer](../advanced/transformers.md) - це повна протилежність middleware!
Це функція, яка обробляє вихідні дані.
Transformer плагіни встановлюються в бота, як ви вже знову здогадалися, як transformer функція.
Це означає, що вам потрібно встановлювати їх через `bot.api.config.use`.
```

2023-03-04 09:38 UTC, LWJerri commented
> Вважаємо читача поважною особою, що звертаємося до нього на "ви" з великої букви? В принципі можна так звертатися в документації.

Hi. My bad, I fix it today.

2023-03-04 09:41 UTC, LWJerri commented on site/docs/uk/plugins/README.md
> +Деякі плагіни одразу **вбудовано** до основної бібліотеки grammY, оскільки ми припускаємо можливості, що вони потрібні багатьом ботам.
I think better translation is: "Деякі плагіни одразу **вбудовано** до головної бібліотеки grammY, оскільки ми вважаємо, що вони потрібні багатьом ботам."

What's your mind about it?

2023-03-04 10:00 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +Деякі плагіни одразу **вбудовано** до основної бібліотеки grammY, оскільки ми припускаємо можливості, що вони потрібні багатьом ботам.
"Головної" looks superfluous. Removing the word does not change the meaning, because there is only one grammY library. Otherwise, it's fine.

2023-03-05 06:40 UTC, Nazar-Ant commented on site/docs/uk/plugins/README.md
> +Ми координуємо їхні релізи з релізами grammy і стежимо за тим, щоб все працювало злагоджено.
> 

```suggestion
Ми координуємо їхні релізи з релізами grammY і стежимо за тим, щоб вони добре працювали разом.
```

2023-03-05 06:44 UTC, Nazar-Ant commented on site/docs/uk/plugins/README.md
> +(Якщо ви використовуєте Deno пакет, а не Node.js, вам слід імпортувати плагін з <https://deno.land/x/>, тобто з файлу `mod.ts` модуля `grammy_runner`).
Прибирайте ці дужки. Я не знаю, навіщо вони там в англійській версії, але в українській мові таке не прийнято й вважається помилкою, коли все речення в дужках, бо правила для такого просто не існує. У дужках може бути прикладка (здається, саме так вона називається), але не все речення повністю.
 
```suggestion
Якщо ви використовуєте Deno пакет, а не Node.js, вам слід імпортувати плагін з <https://deno.land/x/>, тобто з файлу `mod.ts` модуля `grammy_runner`.
```

2023-03-05 06:48 UTC, Nazar-Ant commented on site/docs/uk/plugins/README.md
> +Існує також невелика кількість **сторонніх** плагінів.
```suggestion
Існує також низка **сторонніх** плагінів.
```

2023-03-05 06:52 UTC, Nazar-Ant commented
> Hello dear translators! First, I have a question about plugin names in the table. Do I need to translate names?

У навігаційному меню я їх переклав. Правда, деякі назви не очевидні з перекладу, але поряд все ще є оригінальна назва, тому, думаю, це не проблема. Якщо ми залишаємо переклад у меню, тоді перекладаємо й тут

2023-03-05 06:57 UTC, Nazar-Ant commented on site/docs/uk/plugins/README.md
> +grammY може використовувати переваги двох типів плагінів: _плагіни-мідлвари_ та _плагіни-трансформери_.
```suggestion
grammY може використовувати переваги двох типів плагінів: _middleware_ та _transformer_.
```

2023-03-05 06:59 UTC, Nazar-Ant commented on site/docs/uk/plugins/README.md
> +Якщо Ви хочете створити плагін та поділитись ним з іншими користувачами (навіть опублікувавши на офіційному сайті grammY), ми маємо для Вас [корисний посібник] (./guide.md), з яким Ви можете ознайоми
Ти переглядав переклад на сайті? У тебе через зайвий пробіл посилання зламається.

```suggestion
Якщо Ви хочете створити плагін та поділитись ним з іншими користувачами (навіть опублікувавши на офіційному сайті grammY), ми маємо для Вас [корисний посібник](./guide.md), з яким Ви можете ознайомитися.
```

2023-03-05 07:00 UTC, Nazar-Ant requested changes
Finally, let's resolve the changes, and then I'll accept those changes

2023-03-05 15:51 UTC, LWJerri commented on site/docs/uk/plugins/README.md
> +Це означає, що ви встановлюєте їх через `bot.api.config.use`.
Hello. Yes, I agree with your opinion.

2023-03-05 15:58 UTC, Nazar-Ant approved these changes

2023-03-05 16:41 UTC, deptyped requested changes

2023-03-05 16:41 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +| Sessions                    | _вбудовано_                                           | Зберігання даних користусвачів в базі                        |
```suggestion
| Sessions                    | _вбудовано_                                           | Зберігання даних користувачів в базі                        |
```

2023-03-05 16:41 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +| Router                      | [`router`](./router.md)                               | Перенаправління повідомлення в різні частини коду            |
```suggestion
| Router                      | [`router`](./router.md)                               | Направляйте повідомлення в різні частини коду            |
```

2023-03-05 16:41 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +| Runner                      | [`runner`](./runner.md)                               | Багатопоточний лонг полінг з масштабізацією                  |
```suggestion
| Runner                      | [`runner`](./runner.md)                               | Багатопоточне довге очікування (long polling) з масштабуванням                  |
```

2023-03-05 16:41 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +| Inline and Custom Keyboards | _вбудовано_                                           | Спрощення створення інлайн і кастомних клавіатур             |
```suggestion
| Inline and Custom Keyboards | _вбудовано_                                           | Спрощення створення вбудованих і кастомних клавіатур             |
```

2023-03-05 16:41 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +| Auto-retry                  | [`auto-retry`](./auto-retry.md)                       | Автоматичне оброблення лімітів                               |
```suggestion
| Auto-retry                  | [`auto-retry`](./auto-retry.md)                       | Автоматичне керування лімітами                               |
```

2023-03-05 16:41 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +| Conversations               | [`conversations`](./conversations.md)                 | Створення потужних діалогових інтерфейсів та діалогів        |
```suggestion
| Conversations               | [`conversations`](./conversations.md)                 | Створюйте потужні діалогові інтерфейси        |
```

2023-03-05 16:41 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +| Emoji                       | [`emoji`](./emoji.md)                                 | Спрощення у використання емодзі в коді                       |
```suggestion
| Emoji                       | [`emoji`](./emoji.md)                                 | Спрощення використання емодзі в коді                       |
```

2023-03-05 16:41 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +| Rate Limiter                | [`ratelimiter`](./ratelimiter.md)                     | Автоматичне обмеження користувачів, які спамлять Вашого бота |
```suggestion
| Rate Limiter                | [`ratelimiter`](./ratelimiter.md)                     | Автоматичне обмеження користувачів, які спамлять вашого бота |
```

2023-03-05 16:41 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +| Flood Control               | [`transformer-throttler`](./transformer-throttler.md) | Ставити виклики API в чергу для уникнення спаму до API       |
```suggestion
| Flood Control               | [`transformer-throttler`](./transformer-throttler.md) | Створення черги викликів до API для запобігання надмірної кількості запитів       |
```

2023-03-05 16:41 UTC, deptyped commented on site/docs/uk/plugins/README.md
> +Простіше кажучи, плагіни в grammY повертають або проміжну функцію, або функцію-трансформер.
```suggestion
Простіше кажучи, плагіни в grammY повертають або middleware функцію, або transformer функцію.
```

2023-03-05 17:04 UTC, LWJerri commented on site/docs/uk/plugins/README.md
> +| Emoji                       | [`emoji`](./emoji.md)                                 | Спрощення використання емодзі в коді                       |
```suggestion
| Emoji                       | [`emoji`](./emoji.md)                                 | Спрощене використання емодзі в коді                       |
```

2023-03-05 17:11 UTC, deptyped approved these changes

2023-03-05 17:20 UTC, Nazar-Ant commented on site/docs/uk/plugins/README.md
> +| Flood Control               | [`transformer-throttler`](./transformer-throttler.md) | Створення черги викликів до API для запобігання надмірної кількості запитів       |
```suggestion
| Плагін                      | Пакет                                                 | Опис                                                                        |
| --------------------------- | ----------------------------------------------------- | --------------------------------------------------------------------------- |
| Sessions                    | _вбудовано_                                           | Зберігання даних користувачів в базі                                        |
| Inline and Custom Keyboards | _вбудовано_                                           | Спрощення створення вбудованих і кастомних клавіатур                        |
| Auto-retry                  | [`auto-retry`](./auto-retry.md)                       | Автоматичне оброблення лімітів                                              |
| Conversations               | [`conversations`](./conversations.md)                 | Створюйте потужні діалогові інтерфейси                                      |
| Emoji                       | [`emoji`](./emoji.md)                                 | Спрощене використання емодзі в коді                                         |
| Files                       | [`files`](./files.md)                                 | Легка робота з файлами                                                      |
| Hydration                   | [`hydrate`](./hydrate.md)                             | Виклик методів в об'єктах, що повертаються з викликів API                   |
| Internationalization        | [`i18n`](./i18n.md) or [`fluent`](./fluent.md)        | Дозвольте вашому боту розмовляти кількома мовами                            |
| Interactive Menus           | [`menu`](./menu.md)                                   | Створюйте динамічні меню з кнопками та гнучкою навігацією                   |
| Parse Mode                  | [`parse-mode`](./parse-mode.md)                       | Спрощене форматування повідомлень                                           |
| Rate Limiter                | [`ratelimiter`](./ratelimiter.md)                     | Автоматичне обмеження користувачів, які спамлять вашого бота                |
| Router                      | [`router`](./router.md)                               | Направляйте повідомлення в різні частини коду                               |
| Runner                      | [`runner`](./runner.md)                               | Багатопоточне довге очікування (long polling) з масштабуванням              |
| Stateless Question          | [`stateless-question`](./stateless-question.md)       | Створення діалогів без використання сховища даних                           |
| Flood Control               | [`transformer-throttler`](./transformer-throttler.md) | Створення черги викликів до API для запобігання надмірної кількості запитів |
```

2023-03-05 17:29 UTC, merged