[Ukrainian] Translate `/resources/about.md`
grammyjs/website pull request #644
Opened 2023-03-04 10:15 UTC by deptyped

2023-03-04 10:39 UTC, LWJerri requested changes

2023-03-04 10:39 UTC, LWJerri commented on site/docs/uk/resources/about.md
> +grammY - це програмне забезпечення, завдяки якому ви можете запрограмувати свій власний [чат бот](https://core.telegram.org/bots) для [Telegram Messenger](https://telegram.org).
Probably correct translating is: "...свого власного [чат-бота](https://core.telegram.org/bots)..."

2023-03-04 10:39 UTC, LWJerri commented on site/docs/uk/resources/about.md
> +Ви можете знайти список усіх учасників в [README](https://github.com/grammyjs/grammY#contributors-) нашого репозиторію.
Maybe change "нашого" to "головного"? After all, in the link, we are referring to the main repository of the project.

2023-03-04 10:39 UTC, LWJerri commented on site/docs/uk/resources/about.md
> +Ми вітаємо участь усіх бажаючих.
On my mind, better translation also can be: "Ми вітаємо участь у розвитку проєкту всіх бажаючих."

2023-03-04 10:39 UTC, LWJerri commented on site/docs/uk/resources/about.md
> +(Технічно можна запустити grammY навіть у сучасних браузерах, хоча це вкрай рідко може знадобитися.)
The dot in parentheses is unnecessary, in my opinion.

2023-03-04 10:39 UTC, LWJerri commented on site/docs/uk/resources/about.md
> +- Допомагайте користувачам у [англомовному](https://t.me/grammyjs) чи [російськомовному](https://t.me/grammyjs_ru) чатах спільноти.
Also, we can translate this text as "Допомагайте користувачам у [англомовних](https://t.me/grammyjs) або [російськомовних](https://t.me/grammyjs_ru) чатах."

2023-03-04 15:57 UTC, deptyped commented on site/docs/uk/resources/about.md
> +- Допомагайте користувачам у [англомовному](https://t.me/grammyjs) чи [російськомовному](https://t.me/grammyjs_ru) чатах спільноти.
Not sure about that. If we're talking about one chat for each language, why use the plural forms "англомовних чатах" and "російськомовних чатах"?

2023-03-05 07:08 UTC, Nazar-Ant commented on site/docs/uk/resources/about.md
> +(Технічно можна запустити grammY навіть у сучасних браузерах, хоча це вкрай рідко може знадобитися)
```suggestion
Технічно можна запустити grammY навіть у сучасних браузерах, хоча це вкрай рідко може знадобитися.
```

2023-03-05 07:10 UTC, Nazar-Ant requested changes
Finally, let's resolve the changes, and then I'll accept those changes

2023-03-05 09:56 UTC, Nazar-Ant approved these changes

2023-03-05 09:57 UTC, Nazar-Ant approved these changes

2023-03-05 15:39 UTC, LWJerri approved these changes
Complete review and this PR ready to merge.

2023-03-05 15:55 UTC, merged