[Ukrainian] Translate `/guide/api.md`
grammyjs/website pull request #653
Opened 2023-03-07 12:20 UTC by Nazar-Ant

2023-03-07 13:52 UTC, deptyped requested changes

2023-03-07 13:52 UTC, deptyped commented on site/docs/uk/guide/api.md
> +Отже, якщо ви обійдете сервер Bot API, який Telegram запускає для вас, і просто [розмістите свій власний сервер Bot API](https://core.telegram.org/bots/api#using-a-local-bot-api-сервер), ви можете до
```suggestion
Отже, якщо ви обійдете сервер Bot API, який Telegram запускає для вас, і просто [розмістите свій власний сервер Bot API](https://core.telegram.org/bots/api#using-a-local-bot-api-server), ви можете дозволити своєму боту надсилати файли розміром до 2000 МБ.
```

2023-03-07 13:52 UTC, deptyped commented on site/docs/uk/guide/api.md
> +> Примітка: якщо ви працюєте з великими файлами через [довге опитування](./deployment-types.md), вам варто використовувати [конкурентність для grammY](../plugins/runner.md).
```suggestion
> Примітка: якщо ви працюєте з великими файлами через [тривале опитування](./deployment-types.md), вам варто використовувати [конкурентність для grammY](../plugins/runner.md).
```

2023-03-07 13:52 UTC, deptyped commented on site/docs/uk/guide/api.md
> +  // Відправляємо повідомлення користувачу з id 12345.
```suggestion
  // Надсилаємо повідомлення користувачу з id 12345.
```

2023-03-07 13:52 UTC, deptyped commented on site/docs/uk/guide/api.md
> +Утім зверніть увагу, як `sendMessage` у наведеному вище прикладі отримує два аргументи: ідентифікатор чату та рядок.
```suggestion
Утім зверніть увагу, як `sendMessage` у наведеному вище прикладі отримує два аргументи: ідентифікатор чату та текст повідомлення.
```

2023-03-07 13:52 UTC, deptyped commented on site/docs/uk/guide/api.md
> +grammY дозволяє вам узгоджено вказувати об’єкти в API та забезпечує серіалізацію правильних властивостей на льоту перед їх надсиланням.
```suggestion
Крім того, grammY подбав про безліч технічних деталей, щоб спростити використання API.
Наприклад, деякі властивості в певних методах потребують серіалізації за допомогою `JSON.stringify` перед надсиланням.
Це легко забути, важко налагодити та порушує виведення типів.
grammY дозволяє вам узгоджено вказувати обʼєкти через API, а також гарантує, що відповідні властивості будуть серіалізовані перед їх надсиланням.
```

2023-03-07 13:52 UTC, deptyped commented on site/docs/uk/guide/api.md
> +grammY постачається з повним покриттям типів Bot API.
```suggestion
grammY постачається з повним набором типів Bot API.
```

2023-03-07 13:52 UTC, deptyped commented on site/docs/uk/guide/api.md
> +Вони можуть бути довільно змінені в будь-коли, тому ми настійно рекомендуємо вам імпортувати типи з `grammy/types`.
```suggestion
Вони можуть бути змінені у будь-який час, тому ми наполегливо рекомендуємо вам імпортувати типи з `grammy/types`.
```

2023-03-07 13:52 UTC, deptyped commented on site/docs/uk/guide/api.md
> +Якщо ви не зміните свій файл `tsconfig.json`, як описано вище, може статися так, що ваш редактор коду запропонує в автодоповненні імпортувати типи з `grammy/out/client` або щось подібне.
```suggestion
Якщо ви не зміните свій файл `tsconfig.json`, як описано вище, може статися так, що ваш редактор коду запропонує в автодоповненні імпортувати типи з `grammy/out/client` або чогось подібного.
```

2023-03-07 13:52 UTC, deptyped commented on site/docs/uk/guide/api.md
> +Бувають випадки, коли ви захочете використовувати оригінальні сигнатури функцій, але все одно покладаєтеся на зручність API grammY: наприклад, серіалізація JSON, де це доречно.
```suggestion
Бувають випадки, коли ви захочете використовувати оригінальні сигнатури функцій, але все одно покладаєтеся на зручність API grammY: наприклад, серіалізацію JSON, де це доречно.
```

2023-03-07 13:52 UTC, deptyped commented on site/docs/uk/guide/api.md
> +Ви можете викликати raw методи так:
```suggestion
Ви можете використовувати оригінальні методи наступним чином:
```

2023-03-07 13:52 UTC, deptyped commented on site/docs/uk/guide/api.md
> +По суті, всі параметри даних сигнатури функції об’єднуються з об’єктом параметрів, коли ви використовуєте Raw API.
```suggestion
По суті, всі параметри з аргументів сигнатури функції обʼєднуються з обʼєктом параметрів методу, коли ви використовуєте оригінальний API.
```

2023-03-07 16:18 UTC, Nazar-Ant commented on site/docs/uk/guide/api.md
> +Вони можуть бути довільно змінені в будь-коли, тому ми настійно рекомендуємо вам імпортувати типи з `grammy/types`.
"У будь-який час" звучить як калька. Якщо не подобається "будь-коли", можна використати "коли завгодно".

2023-03-07 16:19 UTC, Nazar-Ant commented on site/docs/uk/guide/api.md
> +По суті, всі параметри даних сигнатури функції об’єднуються з об’єктом параметрів, коли ви використовуєте Raw API.
```suggestion
По суті, всі параметри з аргументів сигнатури функції обʼєднуються з обʼєктом параметрів методу, коли ви використовуєте оригінальний метод API.
```

2023-03-07 19:18 UTC, deptyped commented on site/docs/uk/guide/api.md
> +Вони можуть бути довільно змінені в будь-коли, тому ми настійно рекомендуємо вам імпортувати типи з `grammy/types`.
```suggestion
Вони можуть бути довільно змінені коли завгодно, тому ми настійно рекомендуємо вам імпортувати типи з `grammy/types`.
```

2023-03-08 18:52 UTC, deptyped approved these changes

2023-03-08 18:53 UTC, merged