[Ukrainian] Translate `/resources/comparison.md`
grammyjs/website pull request #654
Opened 2023-03-07 12:26 UTC by deptyped

2023-03-07 16:25 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +# grammY у порівнянні з іншими бот-фреймворками
```suggestion
# grammY у порівнянні з іншими фреймворками для створення ботів
```

2023-03-07 16:29 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +::: tip Для початку оберіть вашу мову програмування
```suggestion
::: tip Спочатку оберіть вашу мову програмування
```

2023-03-07 16:32 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +Існує два головних проєкти, якими надихався grammY, а саме [Telegraf](https://github.com/telegraf/telegraf) та [NTBA](https://github.com/yagop/node-telegram-bot-api).
"а саме" - це узагальнююче слово, після якого ставить двокрапка та йде перелік речей.

```suggestion
Існує два головних проєкти, якими надихався grammY, а саме: [Telegraf](https://github.com/telegraf/telegraf) та [NTBA](https://github.com/yagop/node-telegram-bot-api).
```

2023-03-07 16:33 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +grammY походить своїм корінням від Telegraf, тож нижче короткий огляд того, як ці фреймворки пов'язані між собою.
```suggestion
grammY походить своїм корінням від Telegraf, тож нижче приведений короткий огляд того, як ці фреймворки пов'язані між собою.
```

2023-03-07 16:36 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +На жаль, багато з описаних типів були настільки складними, що їх було дуже важко зрозуміти (але вони були правильними).
```suggestion
На жаль, багато з описаних типів були настільки складними, що їх було дуже важко зрозуміти, але вони були правильними.
```

2023-03-07 16:37 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +У результаті, незважаючи на те, що у версії 4.0 було зроблено спробу _покращити_ коректність типів і інструментів розробки, це призвело до того, що Telegraf став значно _складнішим у використанні_, н
```suggestion
У результаті, незважаючи на те, що у 4-й версії було зроблено спробу _покращити_ коректність типів і інструментів розробки, це призвело до того, що Telegraf став значно _складнішим у використанні_, ніж його нетипізований попередник.
```

2023-03-07 16:38 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +Це дало змогу проєкту мати чистий, узгоджений, компільований код, який надає користувачам відмінні типи (=підтримка редакторів коду).
```suggestion
Це дало змогу проєкту мати чистий, узгоджений, компільований код, який надає користувачам відмінні типи (читай підтримка редакторів коду).
```

2023-03-07 16:39 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +Виходячи з того, що Telegraf завис десь між 3 і 4 версією, є сенс порівнювати grammY з обома версіями окремо.
```suggestion
Виходячи з того, що Telegraf завис десь між 3-ю та 4-ю версією, є сенс порівнювати grammY з обома версіями окремо.
```

2023-03-07 16:40 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +#### Порівняння з v3
```suggestion
#### Порівняння з 3-ю версією
```

2023-03-07 16:40 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +bot.on("message", (ctx) => ctx.reply("Hi!"));
```suggestion
bot.on("message", (ctx) => ctx.reply("Привіт!"));
```

2023-03-07 16:41 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +Основною перевагою grammY над Telegraf 3.x є **значно краща підтримка інструментів розробки**.
```suggestion
Основною перевагою grammY над Telegraf 3-ї версії є **значно краща підтримка інструментів розробки**.
```

2023-03-07 16:41 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +Це дозволяє редактору коду (наприклад VS Code) аналізувати ваш код під час написання і надавати вам допомогу.
```suggestion
Це дозволяє редактору коду (наприклад ,VS Code) аналізувати ваш код під час написання і надавати вам допомогу.
```

2023-03-07 16:43 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +#### Порівняння з v4
```suggestion
#### Порівняння з 4-ю версією
```

2023-03-07 16:44 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +Основна перевага grammY над Telegraf 4.x полягає в тому, що **він набагато простіший**.
```suggestion
Основна перевага grammY над Telegraf 4 полягає в тому, що **він набагато простіший**.
```

2023-03-07 16:45 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +  У Telegraf часто потрібно писати код певним чином, інакше він не скомпілюється (попри те, що насправді він працюватиме без проблем).
```suggestion
  У Telegraf часто потрібно писати код певним чином, інакше він не скомпілюється - попри те, що насправді він працюватиме без проблем.
```

2023-03-07 16:45 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +  Telegraf її не має (замість неї згенерований довідник API, який не містить пояснень).
```suggestion
  Telegraf її не має: замість неї згенерований довідник API, який не містить пояснень.
```

2023-03-07 16:46 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +- grammY інтегрує підказки з [офіційної документації Bot API](https://core.telegram.org/bots/api), які допомагають вам під час написання коду.
```suggestion
- grammY інтегрує підказки з [офіційного довідника Bot API](https://core.telegram.org/bots/api), які допомагають вам під час написання коду.
```

2023-03-07 16:48 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +- Значно швидший у режимі довгого очікування (long polling) при використанні grammY runner
```suggestion
- Значно швидший у режимі тривалого опитування (long polling) при використанні плагіну конкурентності для grammY
```

2023-03-07 16:48 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +- Краща інтеграція з базами даних та веб-фреймворками
```suggestion
- Краща інтеграція з базами даних та фреймворками вебзастосунків
```

2023-03-07 16:48 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +- Більш активно розвивається
```suggestion
- Активніше розвивається
```

2023-03-07 16:50 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +Його архітектуру можна описати одним реченням, тоді як grammY для цього потрібен [посібник] (../guide/) на сайті документації.
```suggestion
Його архітектуру можна описати одним реченням, тоді як grammY для цього потрібен [посібник](../guide/) на сайті документації.
```

2023-03-07 16:51 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +Ідея помістити все в гігантський файл і використовувати примітивний `EventEmitter` для обробки потоку складних обʼєктів (так званих веб-запитів) принесла багато болю в світ Telegram-ботів і, безумовн
Слова з "веб" пишемо завжди разом

```suggestion
Ідея помістити все в гігантський файл і використовувати примітивний `EventEmitter` для обробки потоку складних обʼєктів (так званих вебзапитів) принесла багато болю в світ ботів Telegram і, безумовно, завадила реалізації багатьох гарних ідей.
```

2023-03-07 16:53 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +Будь-яка база коду з більш ніж 50 рядків, що використовує NTBA, перетворюється на жахливий безлад з перехресних звернень, які нагадують спагетті.
```suggestion
Будь-яка кодова база з більш ніж 50 рядків, що використовує NTBA, перетворюється на жахливий безлад з перехресних звернень, які нагадують спагеті.
```

2023-03-07 16:53 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +Ви можете змінювати цю сторінку і додавати порівняння, або поділитися з нами своїми думками в [груповому чаті](https://t.me/grammyjs)!
```suggestion
Ви можете змінювати цю сторінку і додавати порівняння або поділитися з нами своїми думками в [груповому чаті](https://t.me/grammyjs)!
```

2023-03-07 16:54 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +Оскільки ви продовжуєте читати, напевно, вам цікаво, чому grammY написан мовою TypeScript, і чому вам теж варто розглянути можливість вибору цієї мови для вашого бота.
```suggestion
Оскільки ви продовжуєте читати, напевно, вам цікаво, чому grammY написан мовою TypeScript і чому вам теж варто розглянути можливість вибору цієї мови для вашого бота.
```

2023-03-07 16:58 UTC, Nazar-Ant requested changes
Great

2023-03-07 19:28 UTC, deptyped commented on site/docs/uk/resources/comparison.md
> +Хоча grammY використовує певні концепції, які відомі завдяки іншим фреймворкам для ботів (та веб-фреймворкам), він був написаний з нуля для забезпечення кращої організації коду і швидкості роботи.
```suggestion
Хоча grammY використовує певні концепції, які відомі завдяки іншим фреймворкам для ботів та вебзастосунків, він був написаний з нуля для забезпечення кращої організації коду і швидкості роботи.
```
Може краще так, щоб не повторюватися?

2023-03-07 19:31 UTC, deptyped commented on site/docs/uk/resources/comparison.md
> +## Порівняння з іншими JavaScript-фреймворками
```suggestion
## Порівняння з іншими фреймворками на JavaScript
```
Може краще так? Бо фреймворки роблять не для мови, а на мові.

2023-03-07 19:36 UTC, deptyped commented on site/docs/uk/resources/comparison.md
> +Оскільки ви читаєте документацію до фреймворку з JavaScript-екосистеми, вам, напевно, цікавіше порівняння з бібліотеками, які працюють на Node.js (або Deno).
Мається на увазі, що фреймворк частина цієї JavaScript екосистеми, так само як інші фреймворки у порівнянні. Що думаєш щодо такого перекладу?
```suggestion
Оскільки ви читаєте документацію до фреймворку з екосистеми JavaScript, вам, напевно, цікавіше порівняння з бібліотеками, які працюють на Node.js (або Deno).
```

2023-03-07 19:39 UTC, deptyped commented on site/docs/uk/resources/comparison.md
> +Це дозволяє редактору коду (наприклад VS Code) аналізувати ваш код під час написання і надавати вам допомогу.
```suggestion
Це дозволяє редактору коду (наприклад, VS Code) аналізувати ваш код під час написання і надавати вам допомогу.
```

2023-03-08 07:11 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +Хоча grammY використовує певні концепції, які відомі завдяки іншим фреймворкам для ботів (та веб-фреймворкам), він був написаний з нуля для забезпечення кращої організації коду і швидкості роботи.
Так, це краще

2023-03-08 07:12 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +## Порівняння з іншими JavaScript-фреймворками
Так, це краще

2023-03-08 07:13 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +Оскільки ви читаєте документацію до фреймворку з JavaScript-екосистеми, вам, напевно, цікавіше порівняння з бібліотеками, які працюють на Node.js (або Deno).
Так, це краще

2023-03-09 06:38 UTC, Nazar-Ant approved these changes
This PR is ready to merge

2023-03-09 08:55 UTC, KnorpelSenf requested changes
Please fix the formatting before.

2023-03-09 17:02 UTC, Nazar-Ant commented
> Please fix the formatting before.

Other maintainers have already helped us resolve this issue in all PRs. So, is your comment exhausted?

2023-03-09 17:22 UTC, KnorpelSenf approved these changes
Yes, thanks!

2023-03-19 11:28 UTC, LWJerri requested changes

2023-03-19 11:28 UTC, LWJerri commented on site/docs/uk/resources/comparison.md
> +Оскільки ви читаєте документацію до фреймворку з екосистеми JavaScript, вам, напевно, цікавіше порівняння з бібліотеками, які працюють на Node.js (або Deno).
```suggestion
Оскільки ви читаєте документацію до фреймворку з екосистеми JavaScript, вам, напевно, цікавіше порівняння з бібліотеками, які працюють на Node.js або Deno.
```

2023-03-19 11:28 UTC, LWJerri commented on site/docs/uk/resources/comparison.md
> +Також ви знайдете коротке порівняння з фреймворками з інших мов (переважно з Python).
```suggestion
Також ви знайдете коротке порівняння з фреймворками з інших мов, переважно з Python.
```

2023-03-19 11:28 UTC, LWJerri commented on site/docs/uk/resources/comparison.md
> +Однак раніше Telegraf був написаний на JavaScript (у 3-й версії).
```suggestion
Раніше, у третій версії, Telegraf був реалізований з використанням JavaScript.
```

This is probably a good translation but still optional.

2023-03-19 11:28 UTC, LWJerri commented on site/docs/uk/resources/comparison.md
> +Це дозволяє редактору коду (наприклад, VS Code) аналізувати ваш код під час написання і надавати вам допомогу.
```suggestion
Така можливість дає змогу редактору коду, наприклад, VS Code, проаналізувати ваш код під час написання та надавати вам допомогу.
```

2023-03-19 11:28 UTC, LWJerri commented on site/docs/uk/resources/comparison.md
> +Оскільки ви продовжуєте читати, напевно, вам цікаво, чому grammY написан мовою TypeScript і чому вам теж варто розглянути можливість вибору цієї мови для вашого бота.
```suggestion
Оскільки ви продовжуєте читати, напевно, вам цікаво, чому grammY написаний мовою TypeScript і чому вам теж варто розглянути можливість вибору цієї мови для вашого бота.
```

2023-03-19 11:28 UTC, LWJerri commented on site/docs/uk/resources/comparison.md
> +   Рушій V8 робить JavaScript найшвидшою скриптовою мовою у видимому всесвіті.
```suggestion
   Двигун V8 робить JavaScript найшвидшою скриптовою мовою у видимому всесвіті.
```

2023-03-19 11:33 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +Однак раніше Telegraf був написаний на JavaScript (у 3-й версії).
Думаю, краще всі цифри й суміжні слова через цифру й закінчення, щоб читачу було легше зачепитися оком за цифру, а не шукати слово серед інших слів

2023-03-19 11:35 UTC, deptyped commented on site/docs/uk/resources/comparison.md
> +   Рушій V8 робить JavaScript найшвидшою скриптовою мовою у видимому всесвіті.
В вікі перекладено як "рушій", тому думаю буде краще залишити цей переклад
https://uk.wikipedia.org/wiki/V8_(%D1%80%D1%83%D1%88%D1%96%D0%B9_JavaScript)
https://uk.wikipedia.org/wiki/%D0%A0%D1%83%D1%88%D1%96%D0%B9_JavaScript

2023-03-19 11:35 UTC, Nazar-Ant commented on site/docs/uk/resources/comparison.md
> +   Рушій V8 робить JavaScript найшвидшою скриптовою мовою у видимому всесвіті.
Рушій тут краще підходить, як на мене, до того ж це наче як загальноприйнятий переклад. Принаймні я завжди чув саме "рушій", замість двигуна

2023-03-19 11:38 UTC, deptyped commented on site/docs/uk/resources/comparison.md
> +Це дозволяє редактору коду (наприклад, VS Code) аналізувати ваш код під час написання і надавати вам допомогу.
```suggestion
Це надає додаткові можливісті редактору коду, наприклад, VS Code, проаналізувати ваш код під час написання та надавати вам допомогу.
```

2023-03-19 11:41 UTC, LWJerri approved these changes

2023-03-19 16:22 UTC, merged