[Ukrainian] Improve navbar
grammyjs/website pull request #657
Opened 2023-03-07 17:15 UTC by Nazar-Ant

There is nothing to check here, so just approve the changes, please.

2023-03-07 19:24 UTC, deptyped requested changes

2023-03-07 19:24 UTC, deptyped commented on site/docs/.vuepress/configs/uk.ts
> +                text: "Розмови без стану (stateless-question)",
```suggestion
                text: "Питання без стану (stateless-question)",
```
Думаю, краще залишити "питання". Це більш відповідає призначенню плагіна, а також використання "розмов" створить плутанину з плагіном для розмов.

2023-03-08 18:38 UTC, Nazar-Ant commented on site/docs/.vuepress/configs/uk.ts
> +                text: "Запити фільтрування і bot.on()",
```suggestion
                text: "Запити фільтрування та bot.on()",
```

2023-03-08 18:50 UTC, deptyped approved these changes

2023-03-08 18:51 UTC, merged