[Ukrainian] Translate `/guide/filter-queries.md`
grammyjs/website pull request #658
Opened 2023-03-08 15:59 UTC by Nazar-Ant

Since @LWJerri got sick, I will not ask him to check the translation.

2023-03-08 16:43 UTC, KnorpelSenf commented
Ukrainian translations go brrrrr

2023-03-09 00:45 UTC, deptyped requested changes

2023-03-09 00:45 UTC, deptyped commented on site/docs/uk/guide/filter-queries.md
> +Middleware буде виконано, якщо _будь-який із наданих запитів_ збігається.
```suggestion
Middleware буде виконано, якщо оновлення відповідає _будь-якому із наданих запитів_.
```

2023-03-09 00:45 UTC, deptyped commented on site/docs/uk/guide/filter-queries.md
> +Якщо ви хочете встановити якусь частину middleware за конкатенацією І двох запитів, ви можете пов’язати виклики `bot.on()`.
```suggestion
Якщо ви хочете встановити якусь middleware після запитів фільтрування, поєднаних операцією І, вам треба створити ланцюжок викликів `bot.on()` з відповідними запитами.
```

2023-03-09 00:45 UTC, deptyped commented on site/docs/uk/guide/filter-queries.md
> +bot.on(":photo").on("::hashtag" /* , ... */);
```suggestion
// Відповідає пересланим URL-адресам
bot.on("::url").on(":forward_date" /* , ... */);
// Відповідає фотографіям, які містять хештег у підписі
bot.on(":photo").on("::hashtag" /* , ... */);
```

2023-03-09 00:45 UTC, deptyped commented on site/docs/uk/guide/filter-queries.md
> +Скорочення `edit` групує редаговані повідомлення та редаговані дописи на каналі.
```suggestion
Скорочення `edit` групує редаговані повідомлення та редаговані дописи каналів.
```

2023-03-09 00:45 UTC, deptyped commented on site/docs/uk/guide/filter-queries.md
> +bot.on("edit"); // будь-які редаговані повідомлення або дописи на каналі
```suggestion
bot.on("edit"); // будь-які редаговані повідомлення або дописи каналів
```

2023-03-09 00:45 UTC, deptyped commented on site/docs/uk/guide/filter-queries.md
> +bot.on("edit:file"); // редаговані повідомлення або дописи на каналі з файлами
```suggestion
bot.on(":file"); // повідомлення або дописи каналів з файлами
bot.on("edit:file"); // редаговані повідомлення або дописи каналів з файлами
```

2023-03-09 00:45 UTC, deptyped commented on site/docs/uk/guide/filter-queries.md
> +Синтаксичний цукор `:me` можна використовувати для посилання на вашого бота всередині запиту, який порівнюватиме ідентифікатори користувачів за вас.
```suggestion
Є дві особливих частини запитів, які роблять фільтрування ще зручнішим.
Ви можете фільтрувати ботів у запитах за допомогою частини запиту `:is_bot`.
Синтаксичний цукор `:me` можна використовувати для фільтрування посилань на вашого бота в запитах, завдяки чому буде виконуватися порівняння ідентифікаторів користувачів з ідентифікатором боту.
```

2023-03-09 01:00 UTC, deptyped requested changes

2023-03-09 06:44 UTC, Nazar-Ant commented on site/docs/uk/guide/filter-queries.md
> +У певному сенсі grammY реалізує запити фільтрування як під час виконання, так і на рівні типів.
```suggestion
Отже, grammY реалізує запити фільтрування як під час виконання, так і на рівні типів.
```

2023-03-09 06:51 UTC, Nazar-Ant commented on site/docs/uk/guide/filter-queries.md
> +Механізм запитів grammY дозволяє визначати чіткі скорочення, які групують пов’язані запити.
"Елегантний", який стосується краси та одягу, не підходить. Може краще використаємо "вишуканий", оскільки це слово має більш широке значення? 

```suggestion
Механізм запитів grammY дозволяє визначати вишукані скорочення, які групують пов’язані запити.
```

2023-03-09 07:40 UTC, Nazar-Ant commented
I did shit :weary:

2023-03-09 12:31 UTC, Nazar-Ant commented
Dear @CikiMomogi and @roj1512, Thank you so much for correcting what I did while trying to fix an obscure formatting error. Can you please briefly explain why everything broke and how you fixed it?

2023-03-09 14:42 UTC, CikiMomogi commented
No problem. The previous build failed because we forgot to update the package-lock.json in #660. We fixed this issue in #661, and now that PR has been merged into the 'uk' branch, everything should be good to go.

2023-03-10 09:24 UTC, LWJerri commented on site/docs/uk/guide/filter-queries.md
> +Синтаксичний цукор `:me` можна використовувати для посилання на вашого бота всередині запиту, який порівнюватиме ідентифікатори користувачів за вас.
"Синтаксичний **цукор**"? What do u mean?

2023-03-10 09:25 UTC, LWJerri approved these changes

2023-03-10 09:26 UTC, Nazar-Ant commented on site/docs/uk/guide/filter-queries.md
> +Синтаксичний цукор `:me` можна використовувати для посилання на вашого бота всередині запиту, який порівнюватиме ідентифікатори користувачів за вас.
Так було в оригіналі. Гадки не маю, як це перекласти інакше.

2023-03-10 20:37 UTC, deptyped approved these changes

2023-03-11 07:01 UTC, merged