[Ukrainian] Translate `/guide/middleware.md`
grammyjs/website pull request #667
Opened 2023-03-09 18:23 UTC by Nazar-Ant

@deptyped у мене були питання щодо перекладу `downsteam` та `upstream` (ну і ще декілька незрозумілих моментів, але я вже не згадаю їх), приділи їм увагу, будь ласка.

2023-03-11 12:20 UTC, Nazar-Ant commented on site/docs/uk/guide/middleware.md
> +- :x: Механізм протидії [конкурентності для grammY](../plugins/runner.md) ламається, що захищає ваш сервер від надмірно високого навантаження, наприклад, під час стрибків навантаження.
```suggestion
- :x: Механізм протидії [плагіну для конкурентності](../plugins/runner.md) ламається, що захищає ваш сервер від надмірно високого навантаження, наприклад, під час стрибків навантаження.
```

2023-03-11 12:21 UTC, Nazar-Ant commented on site/docs/uk/guide/middleware.md
> +- :x: Механізм протидії [плагіну для конкурентності](../plugins/runner.md) ламається, що захищає ваш сервер від надмірно високого навантаження, наприклад, під час стрибків навантаження.
```suggestion
- :x: Механізм протидії [плагіну для конкурентності (runner)](../plugins/runner.md) ламається, що захищає ваш сервер від надмірно високого навантаження, наприклад, під час стрибків навантаження.
```

2023-03-11 13:17 UTC, deptyped requested changes

2023-03-11 13:17 UTC, deptyped commented on site/docs/uk/guide/middleware.md
> +Ви можете порівняти його з типом middleware, наведеного вище, і переконатися, що ми дійсно маємо middleware.
```suggestion
Ви можете порівняти його з типом middleware, наведеного вище, і переконатися, що ми дійсно створили middleware.
```

2023-03-11 13:17 UTC, deptyped commented on site/docs/uk/guide/middleware.md
> +   Це включає підбір команд, відповідання та все інше, що робить ваш бот.
```suggestion
   Це включає обробку команд, відповідання та все інше, що робить ваш бот.
```

2023-03-11 13:17 UTC, deptyped commented on site/docs/uk/guide/middleware.md
> +Важливо _спочатку_ встановити наш middleware `responseTime` у бота: верхню частину стеку middleware, щоб переконатися, що всі операції включені у вимірювання.
```suggestion
Дуже важливо встановити наш middleware `responseTime` у бота у самому _спочатку_, на верхній рівень стеку. Це важливо тому, що ми хочемо вимірювати час _усіх_ операцій обробки оновлення.
```

2023-03-11 13:17 UTC, deptyped commented on site/docs/uk/guide/middleware.md
> +  console.log(`Час відгуку: ${after - before} мс`);
```suggestion
  console.log(`Час обробки: ${after - before} мс`);
```

2023-03-11 13:17 UTC, deptyped commented on site/docs/uk/guide/middleware.md
> +  console.log(`Час відгуку: ${after - before} мс`);
```suggestion
  console.log(`Час обробки: ${after - before} мс`);
```

2023-03-11 13:17 UTC, deptyped commented on site/docs/uk/guide/middleware.md
> +- :x: Механізм протидії [плагіну для конкурентності (runner)](../plugins/runner.md) ламається, що захищає ваш сервер від надмірно високого навантаження, наприклад, під час стрибків навантаження.
```suggestion
- :x: Ламається механізм [плагіну для конкурентності (runner)](../plugins/runner.md), що захищає ваш сервер від перенавантаження, наприклад, під час різких сплесків навантаження.
```

2023-03-11 13:17 UTC, deptyped commented on site/docs/uk/guide/middleware.md
> +Якщо ви хочете глибше дізнатися, як grammY реалізує middleware, перегляньте [спрощення middleware](../advanced/middleware.md) у розширеному розділі документації.
```suggestion
Якщо ви хочете глибше дізнатися, як grammY реалізує middleware, перегляньте [спрощення middleware](../advanced/middleware.md) у просунутій документації.
```

2023-03-11 16:03 UTC, Nazar-Ant commented on site/docs/uk/guide/middleware.md
> +(ctx, next) => ...    |
"відносно до" - це помилка, як на мене. Ну а "middleware вищий/нижчий" звучить правильніше. 

```suggestion
(ctx, next) => ...    |
(ctx, next) => ...    |—————вищий middleware відносно X
(ctx, next) => ...    |
(ctx, next) => ...       <— middleware X. Викликаємо `next`, щоб передати оновлення 🡳
(ctx, next) => ...    |
(ctx, next) => ...    |—————нижчий middleware відносно X
(ctx, next) => ...    |
```

2023-03-11 16:42 UTC, Nazar-Ant commented on site/docs/uk/guide/middleware.md
> +Важливо _спочатку_ встановити наш middleware `responseTime` у бота: верхню частину стеку middleware, щоб переконатися, що всі операції включені у вимірювання.
Ти залишив "спочатку", замість "початку"

```suggestion
Дуже важливо встановити наш middleware `responseTime` у бота у самому _початку_, на верхній рівень стеку. Це важливо тому, що ми хочемо вимірювати час _усіх_ операцій обробки оновлення.
```

2023-03-11 22:29 UTC, deptyped approved these changes

2023-03-19 11:51 UTC, LWJerri requested changes

2023-03-19 11:51 UTC, LWJerri commented on site/docs/uk/guide/middleware.md
> +2. Middleware плагіну для роботи сесій отримує оновлення і виконує необхідні дії для забезпечення сесії.
```suggestion
2. Middleware плагін для роботи сесій отримує оновлення і виконує необхідні дії для забезпечення сесії.
```

2023-03-19 11:53 UTC, Nazar-Ant commented on site/docs/uk/guide/middleware.md
> +2. Middleware плагіну для роботи сесій отримує оновлення і виконує необхідні дії для забезпечення сесії.
Тут мова про "middleware (кого/чого?) плагіну".

2023-03-19 11:58 UTC, LWJerri approved these changes

2023-03-19 12:01 UTC, merged