[Ukrainian] Translate `/guide/errors.md`
grammyjs/website pull request #670
Opened 2023-03-10 09:19 UTC by Nazar-Ant

2023-03-11 12:22 UTC, Nazar-Ant commented on site/docs/uk/guide/errors.md
> +Якщо ви запускаєте свого бота через `bot.start()` або використовуєте [плагін конкурентності для grammY](../plugins/runner.md), то вам треба **встановити обробник помилок через `bot.catch`**.
```suggestion
Якщо ви запускаєте свого бота через `bot.start()` або використовуєте [плагін для конкурентності (runner)](../plugins/runner.md), то вам треба **встановити обробник помилок через `bot.catch`**.
```

2023-03-24 16:22 UTC, LWJerri approved these changes

2023-03-28 19:00 UTC, deptyped requested changes

2023-03-30 14:52 UTC, deptyped approved these changes

2023-03-30 14:58 UTC, merged