[Ukrainian] Translate `/guide/games.md`
grammyjs/website pull request #675
Opened 2023-03-11 09:27 UTC by Nazar-Ant

2023-03-13 11:50 UTC, deptyped commented on site/docs/uk/guide/games.md
> +> Примітка: ми вивчатимемо лише розробку ботів.
```suggestion
> Примітка: ми вивчатимемо лише розробку бота.
```

2023-03-13 11:52 UTC, deptyped commented on site/docs/uk/guide/games.md
> +> Все, що нам тут потрібно, це посилання на гру HTML5, розміщену в Інтернеті.
```suggestion
> Все, що нам тут потрібно, це посилання на гру, зроблену на HTML5, розміщену в Інтернеті.
```

2023-03-13 11:54 UTC, deptyped commented on site/docs/uk/guide/games.md
> +// бути кнопкою запуску гри!
```suggestion
// Визначаємо нову вбудовану клавіатуру. Ви можете написати будь-який текст,
// який буде показано на кнопці, але переконайтеся, що перша кнопка завжди є
// кнопкою запуску гри!
```

2023-03-13 11:55 UTC, deptyped commented on site/docs/uk/guide/games.md
> +await ctx.api.sendGame(chatId, "my_game", { reply_markup: keyboard });
```suggestion
// Надсилання за допомогою методу `replyWithGame`
await ctx.replyWithGame("my_game", { reply_markup: keyboard });

// Надсилання за допомогою методу `api.sendGame`
await ctx.api.sendGame(chatId, "my_game", { reply_markup: keyboard });
```

2023-03-13 11:56 UTC, deptyped commented on site/docs/uk/guide/games.md
> +Для надання логіки кнопці під час її натискання та для перенаправлення наших користувачів до нашої гри та багато іншого ми слухаємо подію `callback_query:game_short_name`, яка повідомляє нам, що кори
```suggestion
Для надання логіки кнопці при її натисканні та для перенаправлення наших користувачів до нашої гри та ще багато чого іншого, ми обробляємо подію `callback_query:game_short_name`, яка повідомляє нам, що користувач натиснув кнопку гри.
```

2023-03-13 15:16 UTC, Nazar-Ant commented on site/docs/uk/guide/games.md
> +> Все, що нам тут потрібно, це посилання на гру HTML5, розміщену в Інтернеті.
```suggestion
> Все, що нам тут потрібно, це посилання на гру, зроблену на HTML5 та розміщену в Інтернеті.
```

2023-03-19 11:39 UTC, LWJerri requested changes

2023-03-19 11:39 UTC, LWJerri commented on site/docs/uk/guide/games.md
> +> Все, що нам тут потрібно, це посилання на гру, зроблену на HTML5 та розміщену в Інтернеті.
```suggestion
> Все, що нам тут потрібно - це посилання на гру, зроблену на HTML5 та розміщену в Інтернеті.
```

2023-03-19 11:39 UTC, LWJerri commented on site/docs/uk/guide/games.md
> +   // Використовуватимемо команду start для виклику методу відповіді грою.
```suggestion
   // Використовуємо команду start для виклику методу відповіді грою.
```

2023-03-19 11:39 UTC, LWJerri commented on site/docs/uk/guide/games.md
> +    // Або ви можете скористатися тут методом API відповідно до ваших потреб.
```suggestion
    // Або ми можемо скористатися тут методом API відповідно до наших потреб.
```

2023-03-19 11:45 UTC, LWJerri approved these changes

2023-03-19 11:49 UTC, merged