Fix #676
grammyjs/website pull request #677
Opened 2023-03-11 11:32 UTC by roj1512

2023-03-11 11:35 UTC, KnorpelSenf commented on site/docs/plugins/session.md
> +Visit [here](https://github.com/grammyjs/storages/tree/main/packages#grammy-storages) to see a list of currently supported adapters and get guide on using them.
```suggestion
Visit [here](https://github.com/grammyjs/storages/tree/main/packages#grammy-storages) to see a list of currently supported adapters and get guidance on using them.
```

2023-03-11 11:44 UTC, roj1512 commented on site/docs/plugins/session.md
> +Visit [here](https://github.com/grammyjs/storages/tree/main/packages#grammy-storages) to see a list of currently supported adapters and get guide on using them.
Gut catch

2023-03-11 11:51 UTC, KnorpelSenf approved these changes
TYSM!

2023-03-11 16:58 UTC, habemuscode approved these changes

2023-03-12 00:59 UTC, fadzikri requested changes

2023-03-12 00:59 UTC, fadzikri commented on site/docs/id/plugins/session.md
> +Kunjugi repository [berikut](https://github.com/grammyjs/storages/tree/main/packages#grammy-storages) untuk melihat adapter apa saja yang didukung serta mempelajari cara penggunaannya.
```suggestion
Kunjungi repository [berikut](https://github.com/grammyjs/storages/tree/main/packages#grammy-storages) untuk melihat adapter apa saja yang didukung serta mempelajari cara penggunaannya.
```

2023-03-12 00:59 UTC, fadzikri commented on site/docs/id/plugins/session.md
> +Kunjugi repository [berikut](https://github.com/grammyjs/storages/tree/main/packages#grammy-storages) untuk melihat adapter apa saja yang didukung serta mempelajari cara penggunaannya.
just it.

2023-03-12 02:02 UTC, fadzikri approved these changes

2023-03-12 09:21 UTC, KnorpelSenf commented
@roj1512 something fails with the translation guard (which for some reason is called test now)

2023-03-12 12:45 UTC, merged