[Ukrainian] Translate `/plugins/guide.md`
grammyjs/website pull request #679
Opened 2023-03-11 12:59 UTC by LWJerri

2023-03-12 08:36 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +- Transformer плагіни: Задачею плагіна є повернути [transformer функцію](../advanced/transformers.md), яку можна використовувати в боті grammY.
```suggestion
- Middleware плагіни: задачею плагіна є повернути [middleware функцію](../guide/middleware.md), яку можна використовувати в боті grammY.
- Transformer плагіни: задачею плагіна є повернути [transformer функцію](../advanced/transformers.md), яку можна використовувати в боті grammY.
```

2023-03-12 08:40 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +## Правила співпраці
Не бачу сенсу перекладати якось інакше. Це слово відоме й у перекладі воно не дуже псується. Тому ок буде просто так само написати українською.

```suggestion
## Правила контрибʼютингу
```

2023-03-12 08:41 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Ви можете опублікувати свій плагін в одному з таких варіантів:
```suggestion
Ви можете опублікувати свій плагін в одному з настпуних варіантів:
```

2023-03-12 08:45 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Якщо ви вирішите опублікувати свій плагін як сторонній, ми все ще можемо запропонувати вам видне місце на цьому веб-сайті. Однак, ми більш перевагу віддаємо, якщо ви публікуєте свій плагін в [організ
Слова приставкою "веб" пишемо разом. Також у тебе два речення розмістилися на одному рядку.

```suggestion
Якщо ви вирішите опублікувати свій плагін як сторонній, ми все ще можемо запропонувати вам видне місце на цьому вебсайті.
Однак, ми віддаємо перевагу , якщо ви опублікуєте свій плагін в [організації grammyjs](https://github.com/grammyjs) на GitHub, зробивши його офіційним плагіном.
```

2023-03-12 08:46 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Перед тим як перейти до деяких практичних прикладів, є кілька правил, на які потрібно звернути увагу, якщо ви хочете, щоб ваші плагіни були включені до списку на цьому веб-сайті.
```suggestion
Перед тим як перейти до деяких практичних прикладів, є кілька правил, на які потрібно звернути увагу, якщо ви хочете, щоб ваші плагіни були включені до списку на цьому вебсайті.
```

2023-03-12 08:46 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +1. Необхідно мати файл README на GitHub (та npm) з **короткими і чіткими** інструкціями щодо використання плагіна.
```suggestion
1. Необхідно мати файл README на GitHub та npm з **короткими і чіткими** інструкціями щодо використання плагіна.
```

2023-03-12 08:49 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +2. Поясніть призначення вашого плагіна та як його використовувати, додавши сторінку до [документації](https://github.com/grammyjs/website). Якщо ви не впевнені, як це зробити, ми можемо створити стор
Знову два речення на одному рядку

```suggestion
2. Поясніть призначення вашого плагіна та як його використовувати, додавши сторінку до [документації](https://github.com/grammyjs/website).
   Якщо ви не впевнені, як це зробити, ми можемо створити сторінку за вас.
```

2023-03-12 08:50 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +3. Оберіть ліцензію з дозволом на використання, наприклад MIT або ISC.
```suggestion
3. Оберіть ліцензію з дозволом на використання: наприклад, MIT або ISC.
```

2023-03-12 08:55 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Нарешті, ви повинні знати, що хоча grammY підтримує як Node.js, так і [Deno](https://deno.land/), він є проектом, спрямованим на Deno, і ми також підтримуємо написання плагінів для Deno (і, відповідн
Гадки не маю, що за стилі тут маються на увазі, але в перекладі однозначно має бути "згодом" замість "відповідно". Може мається на увазі стиль написання коду?

```suggestion
Нарешті, ви повинні знати, що хоча grammY підтримує як Node.js, так і [Deno](https://deno.land/), він є проєктом, спрямованим на Deno, і ми також підтримуємо написання плагінів для Deno (згодом й у стилі!).
```

2023-03-12 08:56 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Тем не менш, ми дуже рекомендуємо спробувати Deno.
https://onlinecorrector.com.ua/uk/%D0%BE%D0%B4%D0%BD%D0%B0%D0%BA-%D0%BF%D1%80%D0%BE%D1%82%D0%B5-%D0%B0-%D1%82%D0%B0%D0%BA%D0%BE%D0%B6-%D0%B0-%D0%B2%D1%82%D1%96%D0%BC/

```suggestion
Утім, ми дуже рекомендуємо спробувати Deno.
```

2023-03-12 09:00 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Припустимо, ми хотіли б розробити плагін, який реагує тільки на певних користувачів!
```suggestion
Припустимо, ми хотіли б розробити плагін, який відповідає лише певним користувачам!
```

2023-03-12 09:01 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Ось вам тестовий код:
```suggestion
Ось приклад:
```

2023-03-12 09:02 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +// Імпортуємо типи з grammY (ми переекспортуємо їх в `deps.deno.ts`).
```suggestion
// Імпортуємо типи з grammY, ми реекспортуємо їх в `deps.deno.ts`.
```

2023-03-12 09:03 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +// Ваш плагін може мати одну основну функцію, яка створює пmiddleware.
```suggestion
// Ваш плагін може мати одну основну функцію, яка створює middleware.
```

2023-03-12 09:05 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +      // Передаємо керування потоком вниз по middleware.
```suggestion
      // Викликаємо нижній middleware
```

2023-03-12 09:06 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +      // Скажемо, що ми не працюємо з такими
```suggestion
      // Скажемо їм, що ми не працюємо з такими
```

2023-03-12 09:07 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +// Код плагіни знаходиться в файлі з назвою `plugin.ts`
```suggestion
// Код плагіну знаходиться у файлі з назвою `plugin.ts`
```

2023-03-12 09:08 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Ви створили свій власний плагін, хіба не так?
```suggestion
Ви створили власний плагін, чи не так?
```

2023-03-12 09:09 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Нам ще потрібно упакувати його, але перед цим давайте поглянемо на trnsformer плагіни.
```suggestion
Нам ще потрібно упакувати його, але перед цим давайте подивимося на transformer плагіни.
```

2023-03-12 09:10 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +## Розробка тестового transformet плагіну
```suggestion
## Розробка тестового transformer плагіну
```

2023-03-12 09:11 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Уявіть, що ви пишете плагін, який автоматично надсилає відповідну [дію чату](https://core.telegram.org/bots/api#sendchataction) кожного разу, коли бот надсилає документ.
```suggestion
Уявіть, що ви пишете плагін, який автоматично надсилає відповідну [дію чату](https://core.telegram.org/bots/api#sendchataction) щоразу, коли бот надсилає документ.
```

2023-03-12 09:14 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +    // Збережемо ідентифікатор функції setInterval для того, щоби потім можна було його зупинити.
```suggestion
    // Збережемо ідентифікатор встановленого інтервалу, щоби потім можна було його зупинити.
```

2023-03-12 09:15 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +      // Постійно встановлюємл дію чату під час завантаження файлу.
```suggestion
      // Постійно встановлюємо дію чату під час завантаження файлу.
```

2023-03-12 09:16 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +      // Запускаємо актуальний метод з бота.
```suggestion
      // Запускаємо справжній метод із бота.
```

2023-03-12 09:17 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +      // Зупиняємо інтервал, щоб припинити відправку дії в чат клієнту.
```suggestion
      // Очищаємо інтервал, щоб припинити надсилання дії в чат клієнту.
```

2023-03-12 09:17 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +// Код плагіни знаходиться в файлі з назвою `plugin.ts`
```suggestion
// Код плагіну знаходиться у файлі з назвою `plugin.ts`
```

2023-03-12 09:18 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +// Створюємо інстанс бота.
```suggestion
// Створюємо екземплям бота.
```

2023-03-12 09:19 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Тепер кожного разу, коли ми відправляємо документ, дія чату `upload_document` буде відправлена нашому клієнту.
```suggestion
Тепер щоазу, коли ми відправляємо документ, дія чату `upload_document` буде відправлена нашому клієнту.
```

2023-03-12 09:21 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Ймовірно, вам не потрібно встановлювати статус, якщо файл дуже малий, тому тут є деякі оптимізації, які можна зробити.
```suggestion
Імовірно, вам не потрібно встановлювати статус, якщо файл дуже малий, тому тут є деякі оптимізації, які можна зробити.
```

2023-03-12 09:23 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Немає конкретних правил щодо того, як це зробити, і npm - ваша перлина, але щоб все було організовано, у нас є для вас пропозиція шаблону.
```suggestion
Немає конкретних правил щодо того, як це зробити, а npm - ваша перлина, але щоб все було організовано, у нас є для вас пропозиція шаблону.
```

2023-03-12 09:24 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Початково структура папок:
```suggestion
Початкова структура каталогів:
```

2023-03-12 09:24 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +**`deps.deno.ts`** та **`deps.node.ts`**: Це для розробників, які бажають написати плагін для Deno, а потім транспілювати його для Node.js.
```suggestion
**`deps.deno.ts`** та **`deps.node.ts`**: це для розробників, які бажають написати плагін для Deno, а потім транспілювати його для Node.js.
```

2023-03-12 09:25 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +У `deno2node` є функція, яка дозволяє надавати йому файлів, специфічних для рантайму.
```suggestion
У `deno2node` є функція, яка дозволяє надавати йому файли, специфічні для середовища виконання.
```

2023-03-12 09:26 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +> _**Примітка**_: Ви також можете використовувати інші інструменти, такі як [deno dnt](https://github.com/denoland/dnt), для компіляції вашого коду Deno, або використовувати іншу структуру папок.
```suggestion
> _**Примітка**_: ви також можете використовувати інші інструменти, такі як [deno dnt](https://github.com/denoland/dnt), для траспіляції вашого коду Deno, або використовувати іншу структуру каталогів.
```

2023-03-12 09:28 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +> Важливо не інструменти, які ви використовуєте, а те, що пишете код для Deno краще і простіше.
```suggestion
> Інструменти, які ви використовуєте, не важливі - головне, що писати код для Deno краще і простіше.
```

2023-03-12 09:28 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +**`tsconfig.json`**: Це конфігураційний файл компілятора TypeScript, який використовується `deno2node` для транспіляції твого коду.
```suggestion
**`tsconfig.json`**: це конфігураційний файл компілятора TypeScript, який використовується `deno2node` для транспіляції вашого коду.
```

2023-03-12 09:29 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Він відповідає конфігурації TypeScript, яку використовує Deno внутрішньо, і ми рекомендуємо, щоб ти залишався з цією конфігурацією.
```suggestion
Він відповідає конфігурації TypeScript, яку використовує Deno внутрішньо, і ми рекомендуємо, щоб ви залишалися з цією конфігурацією.
```

2023-03-12 09:30 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +**`package.json`**: Файл package.json для npm-версії вашого плагіна.
```suggestion
**`package.json`**: файл package.json для версіонування вашого плагіна в npm.
```

2023-03-12 09:30 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +**Переконайтеся, що зміните його згідно з вашим проектом**.
```suggestion
**Переконайтеся, що зміните його згідно з вашим проєктом**.
```

2023-03-12 09:30 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +**Переконайтеся, що зміните його згідно з вашим проектом**.
```suggestion
**Переконайтеся, що зміните його згідно з вашим проєктом**.
```

2023-03-12 09:31 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +**`README.md`**: Інструкції по використанню плагіну.
```suggestion
**`README.md`**: інструкції щодо використання плагіну.
```

2023-03-12 09:32 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +**`index.ts`**: Це файл, що містить бізнес-логіку вашого плагіна, тобто ваш основний код плагіна.
```suggestion
**`index.ts`**: файл, що містить бізнес-логіку вашого плагіна, тобто ваш основний код плагіну.
```

2023-03-12 09:33 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Якщо ви хочете розробити плагін для grammY і не знаєте, з чого почати, ми дуже рекомендуємо використовувати код зразка, що знаходиться у [нашому репозиторії](https://github.com/grammyjs/plugin-templa
```suggestion
Якщо ви хочете розробити плагін для grammY, але не знаєте, з чого почати, ми дуже рекомендуємо використовувати код шаблону, що знаходиться у [нашому репозиторії](https://github.com/grammyjs/plugin-template).
```

2023-03-12 09:33 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Ви можете клонувати код до себе та почати програмування, користуючись тим, що було розглянуто у цій статті.
```suggestion
Ви можете клонувати код до себе та почати програмувати, користуючись тим, що було розглянуто у цій статті.
```

2023-03-12 09:34 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +У цьому репозиторії також є додаткові корисні файли, такі як `.editorconfig`, `LICENSE`, `.gitignore` і т.д., але ви можете видалити їх за потреби.
```suggestion
У цьому репозиторії також є додаткові корисні файли: наприклад, `.editorconfig`, `LICENSE`, `.gitignore` тощо, але ви можете видалити їх за потреби.
```

2023-03-12 09:35 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Добре, ви щось втрачаєте!
```suggestion
Ну що ж, це втрата!
```

2023-03-12 09:35 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Ви все ще можете опублікувати плагін і додати його до списку сторонніх плагінів на цьому веб-сайті.
```suggestion
Ви все ще можете опублікувати плагін і додати його до списку сторонніх плагінів на цьому вебсайті.
```

2023-03-12 09:35 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +У такому випадку ви можете використовувати будь-яку структуру папок, яку бажаєте (якщо вона організована, як будь-який інший npm-проєкт).
```suggestion
У такому випадку ви можете використовувати будь-яку структуру каталогів, яку бажаєте, якщо вона організована, як будь-який інший проєкт npm.
```

2023-03-12 09:36 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Просто встановіть grammY через npm з `npm install grammy` і починайте кодувати.
```suggestion
Просто встановіть grammY через npm з `npm install grammy` і починайте програмувати.
```

2023-03-12 09:37 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Якщо у вас є готовий плагін, ви можете просто створити pull request на GitHub (відповідно до [правил внеску](#rules-of-contribution)), або повідомити нас у [спільноті чату](https://t.me/grammyjs) для
```suggestion
Якщо у вас є готовий плагін, ви можете просто створити pull request на GitHub відповідно до [правил контрибʼюингу](#правила-котрибʼютингу) або повідомити нас у [чаті спільноти](https://t.me/grammyjs) для подальшої допомоги.
```

2023-03-12 09:55 UTC, Nazar-Ant requested changes
Переглянь новий топік у телеграмі. Там збиратиму правила перекладу

2023-03-12 12:23 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +Якщо у вас є готовий плагін, ви можете просто створити pull request на GitHub відповідно до [правил контрибʼютингу](#правила-котрибʼютингу) або повідомити нас у [чаті спільноти](https://t.me/grammyjs
```suggestion
Якщо у вас є готовий плагін, ви можете просто створити pull request на GitHub відповідно до [правил контрибʼютингу](#правила-контрибʼютингу) або повідомити нас у [чаті спільноти](https://t.me/grammyjs) для подальшої допомоги.
```

2023-03-12 12:26 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +
```suggestion

```

2023-03-12 12:26 UTC, Nazar-Ant commented on site/docs/uk/plugins/guide.md
> +## Типи плагінів в grammY
```suggestion
> Ця стаття - це глибоке занурення в їх внутрішні процеси.

## Типи плагінів в grammY
```

2023-03-12 12:30 UTC, Nazar-Ant approved these changes

2023-03-17 18:36 UTC, deptyped requested changes

2023-03-17 18:36 UTC, deptyped commented on site/docs/uk/plugins/guide.md
> +    }
```suggestion
    // Допускаємо оновлення, якщо воно відповідає умовам.
    if (name === undefined || name.includes(str)) {
      // Викликаємо нижній middleware
      await next();
    } else {
      // Якщо не відповідає умовам, скажемо, що ми з такими не працюємо.
      await ctx.reply(`Я не буду з вами розмовляти! Ви не цікавитеся ${str}!`);
    }
```

2023-03-17 18:36 UTC, deptyped commented on site/docs/uk/plugins/guide.md
> +Ви можете завантажити [код з нашого репозиторію шаблонів плагінів на GitHub](https://github.com/grammyjs/plugin-template) і почати розробляти свій плагін без витрачення часу на налаштування.
```suggestion
Ви можете завантажити [код шаблону плагіна з нашого репозиторію на GitHub](https://github.com/grammyjs/plugin-template) і почати розробляти свій плагін без витрачення часу на налаштування.
```

2023-03-17 18:36 UTC, deptyped commented on site/docs/uk/plugins/guide.md
> +Ну що ж, це втрата!
```suggestion
Ну що ж, ви багато втрачаєте!
```

2023-03-17 18:36 UTC, deptyped commented on site/docs/uk/plugins/guide.md
> +## Як подати заявку?
```suggestion
## Як опублікувати мій плагін?
```

2023-03-19 11:01 UTC, LWJerri commented
@deptyped, can u approve this PR?

2023-03-19 11:10 UTC, deptyped approved these changes

2023-03-19 11:12 UTC, merged