[Ukrainian] Translate `/plugins/console-time.md`
grammyjs/website pull request #680
Opened 2023-03-11 13:00 UTC by LWJerri

2023-03-11 13:55 UTC, deptyped requested changes

2023-03-11 13:55 UTC, deptyped commented on site/docs/uk/plugins/console-time.md
> +# Виведення логів у консоль під час налагодження
```suggestion
# Вимірювання часу обробки у консоль під час налагодження
```

2023-03-11 13:55 UTC, deptyped commented on site/docs/uk/plugins/console-time.md
> +Ця бібліотека призначена для допомоги в роботі з окремими оновленнями.
```suggestion
Цей плагін призначений для відлагодження окремих запитів з метою вирішення окремих проблем.
У продакшен середовищі вам знадобиться щось інше, щоб отримати загальну інформацію про всі запити.
Наприклад, під час відлагодження проблеми з командою `/start` ви перевіряєте окреме оновлення Telegram.
В контексті продакшену вас скоріше цікавлять взагалі всі оновлення з командою `/start`, але ця бібліотека призначена для допомоги в роботі з окремими оновленнями.
```

2023-03-11 13:55 UTC, deptyped commented on site/docs/uk/plugins/console-time.md
> +bot.command("старт" /* , ... */);
```suggestion
bot.command("start" /* , ... */);
```

2023-03-11 13:55 UTC, deptyped commented on site/docs/uk/plugins/console-time.md
> +які будуть виводи із такого тексту:
```suggestion
Це код виведе щось на зразок цього:
```

2023-03-11 13:55 UTC, deptyped commented on site/docs/uk/plugins/console-time.md
> +2020-03-31T14:46:11.385Z 490ai message text Andrey 6 /старт: 892.452ms
```suggestion
2020-03-31T14:32:36.974Z 490af message text Andrey 6 /start: 926.247ms
2020-03-31T14:32:57.750Z 490ag message text Andrey 6 /start: 914.764ms
2020-03-31T14:33:01.188Z 490ah message text Andrey 5 /stop: 302.666ms
2020-03-31T14:46:11.385Z 490ai message text Andrey 6 /start: 892.452ms
```

2023-03-11 13:55 UTC, deptyped commented on site/docs/uk/plugins/console-time.md
> +Це корисно при розгляді максимальної довжини для таких речей, як дані зворотного виклику.
```suggestion
Це корисно, коли потрібно врахувати максимальну довжину для таких речей, як дані зворотного виклику.
```

2023-03-11 13:55 UTC, deptyped commented on site/docs/uk/plugins/console-time.md
> +Коли ви створюєте власний middleware або вважаєте, що інший middleware повільний, ви можете використовувати ці middlewares, щоб створити профіль часу виконання.
```suggestion
Коли ви створюєте власний middleware або вважаєте, що якийсь middleware повільний, ви можете використовувати ці middleware, щоб створити профіль часу виконання.
```

2023-03-11 13:55 UTC, deptyped commented on site/docs/uk/plugins/console-time.md
> +// Використовуйте BeforeMiddleware перед завантаженням тестувального middleware.
```suggestion
// Використовуйте BeforeMiddleware перед встановленням middleware, що тестується.
```

2023-03-11 13:55 UTC, deptyped commented on site/docs/uk/plugins/console-time.md
> +// Використовуйте AfterMiddleware після завантаження middleware, який ви тестуєте з тією самою міткою.
```suggestion
// Використовуйте AfterMiddleware з тією самою міткою, після встановлення middleware, що тестується.
```

2023-03-11 13:55 UTC, deptyped commented on site/docs/uk/plugins/console-time.md
> +// Інші middlewares/реалізації, вони займатимуть "внутрішній" час при використанні.
```suggestion
// Усі інші middleware та код боту, вони рахуватимуться як "inner" при вимірюванні часу.
```

2023-03-11 13:55 UTC, deptyped commented on site/docs/uk/plugins/console-time.md
> +Цей вивід буде виглядати так:
```suggestion
Це код виведе щось на зразок цього:
```

2023-03-11 22:39 UTC, deptyped requested changes

2023-03-11 22:39 UTC, deptyped commented on site/docs/uk/plugins/console-time.md
> +## Опис плагіна
```suggestion
## Загальні відомості про плагін
```

2023-03-12 10:02 UTC, Nazar-Ant commented on site/docs/uk/plugins/console-time.md
> +Ця бібліотека призначена для допомоги в роботі з окремими оновленнями.
Чи варто нам паплюжити переклад словом "продакшн"?

```suggestion
Цей плагін призначений для відлагодження окремих запитів з метою вирішення окремих проблем.
У production середовищі вам знадобиться щось інше, щоб отримати загальну інформацію про всі запити.
Наприклад, під час відлагодження проблеми з командою `/start` ви перевіряєте окреме оновлення Telegram.
У контексті production вас скоріше цікавлять взагалі всі оновлення з командою `/start`, але ця бібліотека призначена для допомоги в роботі з окремими оновленнями.
```

2023-03-12 10:08 UTC, Nazar-Ant commented on site/docs/uk/plugins/console-time.md
> +Цей плагін призначений для відлагодження окремих запитів з метою вирішення окремих проблем.
```suggestion
Цей плагін призначений для налагодження окремих запитів з метою вирішення окремих проблем.
```

2023-03-12 10:08 UTC, Nazar-Ant commented on site/docs/uk/plugins/console-time.md
> +Наприклад, під час відлагодження проблеми з `/start` ви перевіряєте окреме оновлення Telegram.
```suggestion
Наприклад, під час налагодження проблеми з `/start` ви перевіряєте окреме оновлення Telegram.
```

2023-03-12 10:09 UTC, Nazar-Ant commented on site/docs/uk/plugins/console-time.md
> +## Відлагодження вашого middleware
```suggestion
## Налагодження вашого middleware
```

2023-03-12 10:11 UTC, Nazar-Ant commented on site/docs/uk/plugins/console-time.md
> +Це свідчить про те, що перевірений middleware виконувався сам по собі 800мс і, можливо, його продуктивність не є достатньою.
```suggestion
Це свідчить про те, що перевірений middleware виконувався сам по собі 800 мс і, можливо, його продуктивність достатня.
```

2023-03-12 10:17 UTC, Nazar-Ant requested changes
...

2023-03-12 11:58 UTC, LWJerri commented on site/docs/uk/plugins/console-time.md
> +// Інші middlewares/реалізації, вони займатимуть "внутрішній" час при використанні.
Why do you not translate the word "inner"?

2023-03-12 12:00 UTC, LWJerri commented on site/docs/uk/plugins/console-time.md
> +Це свідчить про те, що перевірений middleware виконувався сам по собі 800мс і, можливо, його продуктивність не є достатньою.
Changing one word for another has not changed anything, the meaning is the same.

2023-03-12 12:06 UTC, KnorpelSenf commented
@LWJerri if you want to accept many suggestions, consider switching to the files tab
![image](https://user-images.githubusercontent.com/12952387/224543497-ed18fe51-8cef-4aab-8512-5bdf51c30b3d.png)
at https://github.com/grammyjs/website/pull/680/files and add many suggestions to a batch. That way, you can perform a single commit that collects them all.

2023-03-12 12:08 UTC, Nazar-Ant commented on site/docs/uk/plugins/console-time.md
> +Це свідчить про те, що перевірений middleware виконувався сам по собі 800мс і, можливо, його продуктивність не є достатньою.
По суті так, але тепер це легше читається і правильніше з точки зору мови, як на мене.

2023-03-12 12:15 UTC, LWJerri commented
> @LWJerri if you want to accept many suggestions, consider switching to the files tab ![image](https://user-images.githubusercontent.com/12952387/224543497-ed18fe51-8cef-4aab-8512-5bdf51c30b3d.png) at https://github.com/grammyjs/website/pull/680/files and add many suggestions to a batch. That way, you can perform a single commit that collects them all.

Yes, I'm aware of that, but I'm more comfortable doing reviews from this page.

2023-03-12 12:16 UTC, Nazar-Ant approved these changes

2023-03-12 15:26 UTC, deptyped commented on site/docs/uk/plugins/console-time.md
> +// Інші middlewares/реалізації, вони займатимуть "внутрішній" час при використанні.
The measurement result does not contain "внутрішній". How is the user supposed to know it's about "inner"?

2023-03-19 08:05 UTC, Nazar-Ant approved these changes

2023-03-19 10:44 UTC, merged