[Ukrainian] Translate `/plugins/middlewares.md`
grammyjs/website pull request #681
Opened 2023-03-11 13:00 UTC by LWJerri

2023-03-11 22:37 UTC, deptyped requested changes

2023-03-11 22:37 UTC, deptyped commented on site/docs/uk/plugins/middlewares.md
> +Я постійно переписував ті самі middlewares знову і знову для всіх своїх ботів, тому я вирішив витягнути їх усі в окремий пакет.
```suggestion
Я постійно переписував ті самі middlewares знову і знову для всіх своїх ботів, тому я вирішив помістити їх в окремий пакет.
```

2023-03-11 22:37 UTC, deptyped commented on site/docs/uk/plugins/middlewares.md
> +Всі фабрики middlewares доступу є фабриками, навіть якщо не всі з них повинні бути такими.
```suggestion
Всі middleware є фабриками, навіть якщо не всі з них повинні бути такими.
```

2023-03-11 22:37 UTC, deptyped commented on site/docs/uk/plugins/middlewares.md
> +    ctx.reply("Ви можете використовувати тільки публічні плагіни")
```suggestion
    ctx.reply("Ви можете використовувати це тільки в публічних групах")
```

2023-03-11 22:37 UTC, deptyped commented on site/docs/uk/plugins/middlewares.md
> +## Опис плагіна
```suggestion
## Загальні відомості про плагін
```

2023-03-12 10:18 UTC, Nazar-Ant commented on site/docs/uk/plugins/middlewares.md
> +Я постійно переписував ті самі middlewares знову і знову для всіх своїх ботів, тому я вирішив витягнути їх усі в окремий пакет.
```suggestion
Я постійно переписував ті самі middleware знову і знову для всіх своїх ботів, тому я вирішив помістити усі в окремий пакет.
```

2023-03-12 10:19 UTC, Nazar-Ant commented on site/docs/uk/plugins/middlewares.md
> +## Middlewares
```suggestion
## Усі middleware
```

2023-03-12 10:23 UTC, Nazar-Ant commented on site/docs/uk/plugins/middlewares.md
> +Базовий [sequentialize](../advanced/scaling.md#concurrency-is-hard) middleware, який використовує chat id як послідовний ідентифікатор.
```suggestion
Базовий [sequentialize](../advanced/scaling.md#паралелізм-важкий) middleware, який використовує chat id як послідовний ідентифікатор.
```

2023-03-12 11:55 UTC, Nazar-Ant approved these changes

2023-03-17 18:13 UTC, deptyped approved these changes

2023-03-19 08:06 UTC, Nazar-Ant approved these changes

2023-03-19 10:44 UTC, merged