[Ukrainian] Translate `/guide/deployment-types.md`
grammyjs/website pull request #683
Opened 2023-03-11 15:50 UTC by Nazar-Ant

2023-03-13 07:42 UTC, Nazar-Ant commented on site/docs/uk/guide/deployment-types.md
> +Наприклад, плагін сеансу неминуче вийде з ладу через небезпеку [запису після читання](https://en.wikipedia.org/wiki/Hazard_(computer_architecture)#Write_after_read_(WAR)).
```suggestion
Наприклад, плагін сеансу неминуче вийде з ладу через конфлікт [запису після читання](https://en.wikipedia.org/wiki/Hazard_(computer_architecture)#Write_after_read_(WAR)).
```

2023-03-22 05:36 UTC, Nazar-Ant commented on site/docs/uk/guide/deployment-types.md
> +| `worktop`        | Фреймворк `worktop` для воркерів Cloudflare                   | Node                 |
```suggestion
| `worktop`        | Фреймворк `worktop` для Cloudflare Workers                    | Node                 |
```

2023-03-23 13:06 UTC, KnorpelSenf commented
See https://github.com/grammyjs/website/commit/985c0c6d1e4105d470bde994c81903e9fd09b68a#commitcomment-105737043

2023-03-24 16:19 UTC, LWJerri approved these changes

2023-04-01 17:14 UTC, LWJerri requested changes

2023-04-01 17:14 UTC, LWJerri commented on site/docs/uk/guide/deployment-types.md
> +**Опитування** означає, що grammY завчасно надсилає запит до Telegram із запитом на нові оновлення (читайте повідомлення).
```suggestion
**Опитування** означає, що grammY завчасно надсилає запит до Telegram із запитом на нові оновлення, читайте повідомлення.
```

2023-04-01 17:14 UTC, LWJerri commented on site/docs/uk/guide/deployment-types.md
> +Коли grammY надсилає запит до Telegram і тим часом вашому боту надсилаються нові повідомлення, Telegram повертає їх у вигляді масиву до 100 об’єктів оновлення.
```suggestion
Коли grammY надсилає запит до Telegram і тим часом вашому боту надсилаються нові повідомлення, Telegram повертає їх у вигляді масиву до 100 об’єктів.
```

2023-04-01 17:14 UTC, LWJerri commented on site/docs/uk/guide/deployment-types.md
> +Налаштування **вебхуку** означає, що ви надасте Telegram URL-адресу, доступну з публічного Інтернету.
```suggestion
Налаштування **вебхуку** означає, що ви надасте Telegram URL-адресу, доступну з Інтернету.
```

2023-04-01 17:14 UTC, LWJerri commented on site/docs/uk/guide/deployment-types.md
> +Він обіцяє особисто завітати до вашої квартири, коли приїде нове морозиво, щоб воно не розтало на пошті.
```suggestion
Він обіцяє особисто завітати до вашої домівки, коли приїде нове морозиво, щоб воно не розтало на пошті.
```

2023-04-01 17:14 UTC, LWJerri commented on site/docs/uk/guide/deployment-types.md
> +Перегляньте параметр конфігурації [тут](https://deno.land/x/grammy/mod.ts?s=ApiClientOptions#prop_canUseWebhookReply).
```suggestion
Перегляньте параметри конфігурації [тут](https://deno.land/x/grammy/mod.ts?s=ApiClientOptions#prop_canUseWebhookReply).
```

2023-04-01 17:14 UTC, LWJerri commented on site/docs/uk/guide/deployment-types.md
> +щоб запустити свого бота за допомогою дуже простої форми тривалого опитування.
```suggestion
Щоб запустити свого бота за допомогою дуже простої форми тривалого опитування.
```

2023-04-02 08:08 UTC, Nazar-Ant commented on site/docs/uk/guide/deployment-types.md
> +Іншими словами, є два принципово різні способи розміщення вашого бота та запуску його на якомусь сервері; вони відрізняються способом, яким повідомлення досягають вашого бота і яким можуть бути оброб
Тут потрібна саме крапка з комою, тому що це безсполучникове складне речення. У другій частині є свої знаки пунктуації, тому між частинами потрібна крапка з комою

2023-04-02 08:10 UTC, Nazar-Ant commented on site/docs/uk/guide/deployment-types.md
> +**Опитування** означає, що grammY завчасно надсилає запит до Telegram із запитом на нові оновлення (читайте повідомлення).
Думаю, тут все ж таки потрібні круглі дужки відповідно до [1-го пункта](https://dyskurs.net/pravyla-vzhyvannia-duzhok/)

2023-04-02 08:12 UTC, Nazar-Ant commented on site/docs/uk/guide/deployment-types.md
> +Перегляньте параметр конфігурації [тут](https://deno.land/x/grammy/mod.ts?s=ApiClientOptions#prop_canUseWebhookReply).
Тут ми посилаємося на конретний параметр

2023-04-02 08:13 UTC, Nazar-Ant commented on site/docs/uk/guide/deployment-types.md
> +щоб запустити свого бота за допомогою дуже простої форми тривалого опитування.
Речення розірвано прикладом коду, тому продовження пишемо з маленької літери (ми завжди так робили)

2023-04-03 09:07 UTC, LWJerri approved these changes

2023-04-03 09:07 UTC, LWJerri commented on site/docs/uk/guide/deployment-types.md
> +|            |       *обробка ботом тричі*          ...  |           |
```suggestion
|            |        *обробка ботом двічі*         ..   |           |
|            |                                      ..   |           |
|            | ---          ПРИИИВВВІІІТ         --->    |           |
|            |                                      ...  |           |
|            |        *обробка ботом тричі*         ...  |           |
```

Centred the last text, and highlighted as much to see the last test from the middle.

2023-04-03 11:45 UTC, LWJerri approved these changes

2023-04-08 13:49 UTC, deptyped requested changes

2023-04-08 14:06 UTC, Nazar-Ant commented on site/docs/uk/guide/deployment-types.md
> +Витратьте час, щоб правильно вирішити цю проблему, тоді майбутні ви та ваші користувачі будуть вам вдячні.
ти хотів зробити так?

```suggestion
Якщо ви це зробите, ви в певному сенсі використовуєте чергу Telegram для доставки оновлень через вебхук як чергу завдань.
Це погана ідея з усіх причин, описаних вище.
Те, що grammY _може_ приховувати помилки, через які ви можете втратити свої дані, не означає, що ви _маєте_ робити це.
Цей параметр конфігурації не слід використовувати у випадках, коли виконання ваших middleware просто займає надто багато часу.
Витратьте час, щоб правильно вирішити цю проблему, тоді ви в майбутньому та ваші користувачі будуть вам вдячні.
```

2023-04-08 14:06 UTC, Nazar-Ant commented on site/docs/uk/guide/deployment-types.md
> +Витратьте час, щоб правильно вирішити цю проблему, тоді майбутні ви та ваші користувачі будуть вам вдячні.
Думаю, тоді краще "в майбутньому" помістити перед "ми"
```suggestion
Якщо ви це зробите, ви в певному сенсі використовуєте чергу Telegram для доставки оновлень через вебхук як чергу завдань.
Це погана ідея з усіх причин, описаних вище.
Те, що grammY _може_ приховувати помилки, через які ви можете втратити свої дані, не означає, що ви _маєте_ робити це.
Цей параметр конфігурації не слід використовувати у випадках, коли виконання ваших middleware просто займає надто багато часу.
Витратьте час, щоб правильно вирішити цю проблему, тоді в майбутньому ви та ваші користувачі будуть вам вдячні.
```

2023-04-09 14:07 UTC, deptyped approved these changes

2023-04-09 14:13 UTC, merged