[Ukrainian] Translate `/advanced/middleware.md`
grammyjs/website pull request #691
Opened 2023-03-12 18:17 UTC by Nazar-Ant

2023-03-23 16:32 UTC, deptyped requested changes

2023-03-23 16:32 UTC, deptyped commented on site/docs/uk/advanced/middleware.md
> +Це лише підклас, тому `class Bot extends Composer`.
```suggestion
Насамперед кожен екземпляр `Bot` є екземпляром `Composer`.
Він є підкласом, тому `class Bot extends Composer`.
```

2023-03-23 16:32 UTC, deptyped commented on site/docs/uk/advanced/middleware.md
> +Наприклад, `filter` просто викликає `use` з деяким розгалуженням middleware, тоді як `on` просто знову викликає `filter` з деякою предикатною функцією, яка відповідає оновленням відповідному [запиту
```suggestion
Наприклад, `filter` просто викликає `use` з деяким розгалуженням middleware, тоді як `on` просто знову викликає `filter` з деякою предикатною функцією, яка відповідає оновленням відповідного [запиту фільтрування](../guide/filter-queries.md).
```

2023-03-23 16:32 UTC, deptyped commented on site/docs/uk/advanced/middleware.md
> +Тому наразі ми можемо обмежитися розглядом `use`, а решта піде саме з нього.
```suggestion
Тому наразі ми можемо обмежитися розглядом `use`, решта методів походить саме з нього.
```

2023-03-23 16:32 UTC, deptyped commented on site/docs/uk/advanced/middleware.md
> +Різниця може здатися незначною, але зачекайте до наступного підрозділу, щоб дізнатися, чому вона має чудові наслідки.
```suggestion
Різниця може здатися незначною, але зачекайте до наступного підрозділу, щоб дізнатися, чому вона має значні наслідки.
```

2023-03-23 16:32 UTC, deptyped commented on site/docs/uk/advanced/middleware.md
> +Ви можете інсталювати більше middleware на екземпляр `Composer` навіть після встановлення десь самого `Composer`.
```suggestion
Ви можете встановити додаткові middleware на екземпляр `Composer` навіть після того, як десь вже встановили сам `Composer`.
```

2023-03-23 16:32 UTC, deptyped commented on site/docs/uk/advanced/middleware.md
> +У цьому немає нічого вражаючого, але це вже головна відмінність від популярних конкуруючих фреймворків, які просто ігнорують наступні операції.
```suggestion
`A`, `B` і `C` будуть виконані.
Це означає, що коли ви встановили екземпляр `Composer`, ви все ще можете викликати `use` на ньому, і ці middleware теж буде виконано.
У цьому немає нічого вражаючого, але це вже головна відмінність від популярних конкуруючих фреймворків, які просто ігнорують такі операції.
```

2023-03-23 16:32 UTC, deptyped commented on site/docs/uk/advanced/middleware.md
> +Давайте подивимося на цей фрагмент:
```suggestion
Напевно вам цікаво, де саме тут використовується структура дерева.
Давайте розглянемо цей фрагмент:
```

2023-03-23 16:32 UTC, deptyped commented on site/docs/uk/advanced/middleware.md
> +Потім це дерево буде проходити кожне оновлення в глибинному порядку, отже фактично проходячи від `A` до `L` у лінійному порядку, подібно до того, що ви знаєте з інших систем.
```suggestion
Кожне оновлення буде обходити це дерево в глибину, отже фактично проходячи від `A` до `L` у лінійному порядку, подібно до того, як це відбувається в інших системах.
```

2023-03-23 16:32 UTC, deptyped commented on site/docs/uk/advanced/middleware.md
> +## Конкатенація викликів `use`
```suggestion
## Поєднання викликів `use`
```

2023-03-23 16:32 UTC, deptyped commented on site/docs/uk/advanced/middleware.md
> +Стає цікавіше, як тільки, наприклад, `filter` вступає в дію.
```suggestion
Стає цікавіше, як тільки в гру вступає, наприклад, `filter`.
```

2023-03-23 16:32 UTC, deptyped commented on site/docs/uk/advanced/middleware.md
> +Гляньте:
```suggestion
Тільки погляньте:
```

2023-03-23 16:32 UTC, deptyped commented on site/docs/uk/advanced/middleware.md
> +Однак `filter` повертає екземпляр `Composer`, який ми доповнюємо викликом `use` у 3-му рядку, тому `B` все ще перекривається умовою `1`, навіть якщо його встановлено в зовсім іншому виклику `use`.
```suggestion
У 3-му рядку ми реєструємо `A` за предикатною функцією `1`.
`A` буде виконуватися лише для оновлень, які відповідають умові `1`.
Однак `filter` повертає екземпляр `Composer`, який ми доповнюємо викликом `use` у 3-му рядку, тому `B` теж знаходиться за предикатною функцією `1`, навіть якщо його встановлено вже в іншому виклику `use`.
```

2023-03-23 16:32 UTC, deptyped commented on site/docs/uk/advanced/middleware.md
> +`A` тепер виконуватиметься на гілці паралельних обчислень.
```suggestion
Особливим випадком тут є `fork`, оскільки він запускає два конкурентних обчислення, тобто які можуть чергуватися в event loop.
Замість повернення екземпляра `Composer`, створеного базовим викликом `use`, він повертає `Composer`, який відображає розгалужене обчислення.
Це дозволяє створювати короткі шаблони: наприклад, `bot.fork().on(":text").use(/* A */)`.
`A` виконуватиметься на паралельний гілці обчислень.
```

2023-03-24 12:36 UTC, deptyped approved these changes

2023-03-24 15:26 UTC, LWJerri approved these changes

2023-03-24 15:26 UTC, LWJerri commented on site/docs/uk/advanced/middleware.md
> +const bot = new Bot("<токен>");
```suggestion
const bot = new Bot("");
```

2023-03-24 15:26 UTC, LWJerri commented on site/docs/uk/advanced/middleware.md
> +const bot = new Bot("<токен>"); // підклас класу `Composer`
```suggestion
const bot = new Bot(""); // підклас класу `Composer`
```

2023-03-24 15:26 UTC, LWJerri commented on site/docs/uk/advanced/middleware.md
> +Навпаки, grammY зберігає вказане вами дерево: один кореневий вузол `composer` має п’ять дочірніх елементів: `A`, `B`, `D`, `H`, `J`, а дочірній `B` має ще один дочірній елемент: `C`.
```suggestion
Навпаки, grammY зберігає вказане вами дерево: один кореневий вузол `composer` має пʼять дочірніх елементів: `A`, `B`, `D`, `H`, `J`, а дочірній `B` має ще один дочірній елемент: `C`.
```

2023-03-24 15:26 UTC, LWJerri commented on site/docs/uk/advanced/middleware.md
> +Пам’ятаєте, як виклики `bot.on()` можна об’єднувати, щоб об’єднати запити фільтрування за допомогою логічної операції І?
```suggestion
Памʼятаєте, як виклики `bot.on()` можна обʼєднувати, щоб обʼєднати запити фільтрування за допомогою логічної операції І?
```

2023-03-25 05:30 UTC, merged