[Ukrainian] Translate `/advanced/scaling.md`
grammyjs/website pull request #693
Opened 2023-03-13 07:44 UTC by Nazar-Ant

2023-03-24 16:01 UTC, LWJerri approved these changes

2023-03-24 16:01 UTC, LWJerri commented on site/docs/uk/advanced/scaling.md
> +const bot = new Bot("<token>");
```suggestion
const bot = new Bot("");
```

2023-03-24 16:01 UTC, LWJerri commented on site/docs/uk/advanced/scaling.md
> +bot.on("message", (ctx) => ctx.reply("Got your message."));
```suggestion
bot.on("message", (ctx) => ctx.reply("Отримав ваше повідомлення."));
```

2023-03-25 10:14 UTC, deptyped requested changes

2023-03-25 10:14 UTC, deptyped commented on site/docs/uk/advanced/scaling.md
> +В ідеалі, ми також хотіли б обмежити одночасність деяким фіксованим числом, щоб обмежити максимальне навантаження на сервер.
```suggestion
Щоб досягти максимальної швидкості реагування, ми також хотіли б отримувати нові повідомлення, поки повідомлення Боба та Аліси ще обробляються.
В ідеалі, ми також хотіли б обмежити кількість одночасно оброблюваних повідомлень деяким фіксованим числом, щоб обмежити максимальне навантаження на сервер.
```

2023-03-25 10:14 UTC, deptyped commented on site/docs/uk/advanced/scaling.md
> +Паралельна обробка не входить до базового пакету grammy.
```suggestion
Паралельна обробка не входить до базового пакету grammY.
```

2023-03-25 10:14 UTC, deptyped commented on site/docs/uk/advanced/scaling.md
> +## Паралелізм важкий
```suggestion
## Паралелізм складний
```

2023-03-25 10:14 UTC, deptyped commented on site/docs/uk/advanced/scaling.md
> +Паралелізм - це складно, тому перегляньте [підрозділ нижче](#%D0%BF%D0%B0%D1%80%D0%B0%D0%BB%D0%B5%D0%BB%D1%96%D0%B7%D0%BC-%D0%B2%D0%B0%D0%B6%D0%BA%D0%B8%D0%B8), щоб дізнатися, про що слід пам'ятати п
```suggestion
Паралелізм - це складно, тому перегляньте [підрозділ нижче](#паралелізм-складнии), щоб дізнатися, про що слід пам'ятати при використанні цього плагіну.
```

2023-03-25 10:14 UTC, deptyped commented on site/docs/uk/advanced/scaling.md
> +Це означає, що ви все одно повинні знати про деякі наслідки паралелізму, зверніть увагу на [підрозділ нижче](#%D0%BF%D0%B0%D1%80%D0%B0%D0%BB%D0%B5%D0%BB%D1%96%D0%B7%D0%BC-%D0%B2%D0%B0%D0%B6%D0%BA%D0%
```suggestion
Це означає, що ви все одно повинні знати про деякі наслідки паралелізму, зверніть увагу на [підрозділ нижче](#паралелізм-складнии).
```

2023-03-25 10:14 UTC, deptyped commented on site/docs/uk/advanced/scaling.md
> +> Набагато легше уникнути конфклікта в першу чергу.
```suggestion
> Набагато легше насамперед уникнути небезпечного запису.
```

2023-03-25 10:14 UTC, deptyped commented on site/docs/uk/advanced/scaling.md
> +Тоді він уникне вищезгаданого стану гонки, сповільнивши ті й тільки ті оновлення, які могли б спричинити колізію.
```suggestion
Однак ми не хочемо цього, тому що боти Telegram набагато частіше стикаються із зіткненнями паралельних запитів на один і той самий ключ сесії.
Отже, ми повинні переконатися, що оновлення, які отримують доступ до одних і тих же даних сесії, обробляються послідовно, щоб уникнути цього небезпечного стану гонки.

Плагін для конкурентності (runner) постачається з middleware `sequentialize()`, який гарантує, що оновлення, які конфліктують, обробляються послідовно.
Ви можете налаштувати його за допомогою тієї самої функції, яку ви використовуєте для визначення ключа сесії.
Тоді він уникне вищезгаданого стану гонки, сповільнивши виключно ті оновлення, які могли б спричинити колізію.
```

2023-03-25 10:14 UTC, deptyped commented on site/docs/uk/advanced/scaling.md
> +bot.on("message", (ctx) => ctx.reply("Отримав ваше повідомлення."));
```suggestion
// Упорядкуємо дані перед доступом до даних сесії!
bot.use(sequentialize(getSessionKey));
bot.use(session({ getSessionKey }));

// Додаємо звичайний middleware, тепер з підтримкою безпечних сесій.
bot.on("message", (ctx) => ctx.reply("Отримав ваше повідомлення."));
```

2023-03-25 10:14 UTC, deptyped commented on site/docs/uk/advanced/scaling.md
> +bot.on("message", (ctx) => ctx.reply("Отримав ваше повідомлення."));
```suggestion
// Упорядкуємо дані перед доступом до даних сесії!
bot.use(sequentialize(getSessionKey));
bot.use(session({ getSessionKey }));

// Додаємо звичайний middleware, тепер з підтримкою безпечних сесій.
bot.on("message", (ctx) => ctx.reply("Отримав ваше повідомлення."));
```

2023-03-25 10:14 UTC, deptyped commented on site/docs/uk/advanced/scaling.md
> +bot.on("message", (ctx) => ctx.reply("Отримав ваше повідомлення."));
```suggestion
// Упорядкуємо дані перед доступом до даних сесії!
bot.use(sequentialize(getSessionKey));
bot.use(session({ getSessionKey }));

// Додаємо звичайний middleware, тепер з підтримкою безпечних сесій.
bot.on("message", (ctx) => ctx.reply("Отримав ваше повідомлення."));
```

2023-03-25 10:14 UTC, deptyped commented on site/docs/uk/advanced/scaling.md
> +Приєднуйтесь до [чату Telegram](https://t.me/grammyjs), щоб обговорити, як використовувати плагін для конкурентності (runner) з вашим ботом.
```suggestion
Приєднуйтесь до [чату Telegram](https://t.me/grammyjs), щоб обговорити використання плагіну для конкурентності (runner) для вашого бота.
```

2023-03-25 10:17 UTC, deptyped requested changes

2023-03-25 10:17 UTC, deptyped commented on site/docs/uk/advanced/scaling.md
> +> Примітка: ви можете спробувати використовувати транзакції бази даних для ваших сеансів, але тоді ви зможете лише виявити конфлікт, а не запобігти йому.
```suggestion
> Примітка: ви можете спробувати використовувати транзакції бази даних для сесій, але тоді ви зможете лише виявити конфлікт, а не запобігти йому.
```

2023-03-30 14:52 UTC, deptyped approved these changes

2023-03-30 14:59 UTC, merged