[Ukrainian] Translate `/advanced/reliability.md`
grammyjs/website pull request #694
Opened 2023-03-13 08:28 UTC by Nazar-Ant

2023-03-24 16:40 UTC, LWJerri approved these changes

2023-03-24 16:40 UTC, LWJerri commented on site/docs/uk/advanced/reliability.md
> +const bot = new Bot("<токен>");
```suggestion
const bot = new Bot("");
```

2023-03-24 16:40 UTC, LWJerri commented on site/docs/uk/advanced/reliability.md
> +const bot = new Bot("<токен>");
```suggestion
const bot = new Bot("");
```

2023-03-24 16:40 UTC, LWJerri commented on site/docs/uk/advanced/reliability.md
> +const bot = new Bot("<token>");
```suggestion
const bot = new Bot("");
```

2023-03-24 16:40 UTC, LWJerri commented on site/docs/uk/advanced/reliability.md
> +const bot = new Bot("<токен>");
```suggestion
const bot = new Bot("");
```

2023-03-24 16:40 UTC, LWJerri commented on site/docs/uk/advanced/reliability.md
> +const bot = new Bot("<токен>");
```suggestion
const bot = new Bot("");
```

2023-03-24 16:40 UTC, LWJerri commented on site/docs/uk/advanced/reliability.md
> +Решта цього розділу присвячена тому, як поводиться grammy за таких незвичних обставин і як впоратися з цими ситуаціями.
```suggestion
Решта цього розділу присвячена тому, як поводиться grammY за таких незвичних обставин і як впоратися з цими ситуаціями.
```

2023-03-24 16:40 UTC, LWJerri commented on site/docs/uk/advanced/reliability.md
> +Якщо ви використовуєте [плагін для конкурентності (runner)](../plugins/runner.md) у паралельному режимі, наступний виклик `getUpdates` може бути виконано до того, як ваші middleware оброблять перше о
```suggestion
Якщо ви використовуєте [плагін для конкурентності (runner)](../plugins/runner.md) у паралельному режимі, наступний виклик `getUpdates` може бути виконано до того, як ваші middleware оброблять перше оновлення поточної пачки.
```

2023-03-24 21:13 UTC, deptyped requested changes

2023-03-24 21:13 UTC, deptyped commented on site/docs/uk/advanced/reliability.md
> +Якщо дуже важливо запобігти цьому, вам слід скористатися джерелами та поглиначами пакету плагіна для конкурентності (runner) для створення власного конвеєра оновлень, який спершу пропускатиме всі оно
```suggestion
Якщо дуже важливо запобігти цьому, вам слід скористатися джерелами та поглиначами з пакету плагіна для конкурентності (runner) для створення власного способу обробки оновлень, який спершу пропускатиме всі оновлення через чергу повідомлень.
```

2023-03-24 21:13 UTC, deptyped commented on site/docs/uk/advanced/reliability.md
> +   Ви фактично запустите два різних екземпляри плагіну для конкурентності (runner).
```suggestion
1. Вам потрібно створити [поглинач оновлень](https://deno.land/x/grammy_runner/mod.ts?s=UpdateSink), який буде поміщати оновлення у чергу, і запустити один runner, який буде обслуговувати цю чергу повідомлень.
2. Після цього вам треба створити [джерело оновлень](https://deno.land/x/grammy_runner/mod.ts?s=UpdateSource), яке буде отримувати оновлення з цієї черги повідомлень.
   Таким чином, ви фактично запустите два окремих екземпляри плагіну для конкурентності (runner).
```

2023-03-25 05:50 UTC, Nazar-Ant commented on site/docs/uk/advanced/reliability.md
> +1. По суті, вам потрібно створити [поглинач](https://deno.land/x/grammy_runner/mod.ts?s=UpdateSink), який поміщає оновлення у чергу, і запустити одну чергу, яка буде обслуговувати тільки вашу чергу п
```suggestion
1. По суті, вам потрібно створити [обробник (sink)](https://deno.land/x/grammy_runner/mod.ts?s=UpdateSink), який поміщає оновлення у чергу, і запустити одну чергу, яка буде обслуговувати тільки вашу чергу повідомлень.
```

2023-03-25 05:50 UTC, Nazar-Ant commented on site/docs/uk/advanced/reliability.md
> +2. Після цього вам доведеться створити [джерело](https://deno.land/x/grammy_runner/mod.ts?s=UpdateSource), яке знову витягне оновлення з черги повідомлень.
```suggestion
2. Після цього вам доведеться створити [джерело оновлень](https://deno.land/x/grammy_runner/mod.ts?s=UpdateSource), яке знову витягне оновлення з черги повідомлень.
```

2023-03-25 09:40 UTC, deptyped approved these changes

2023-03-25 13:59 UTC, merged