[Ukrainian] Translate `/advanced/flood.md`
grammyjs/website pull request #695
Opened 2023-03-13 08:48 UTC by Nazar-Ant

2023-03-23 18:02 UTC, deptyped requested changes

2023-03-23 18:02 UTC, deptyped commented on site/docs/uk/advanced/flood.md
> +Цей плагін так само простий у налаштуванні, але набагато краще бориться з переповненням.
```suggestion
Цей плагін так само простий у налаштуванні, але набагато краще бореться з надмірною кількістю запитів.
```

2023-03-23 18:02 UTC, deptyped commented on site/docs/uk/advanced/flood.md
> +У деяких випадках може мати сенс використовувати обидва варіанти.
```suggestion
У деяких випадках може мати сенс використовувати обидва плагіни.
```

2023-03-23 18:06 UTC, deptyped requested changes

2023-03-23 18:06 UTC, deptyped commented on site/docs/uk/advanced/flood.md
> +Насправді немає жодної вагомої причини використовувати [плагін для повторення запитів](./plugins/auto-retry.md) замість [плагіну для обмеження запитів](./plugins/transformer-throttler.md).
```suggestion
Насправді немає жодної вагомої причини використовувати [плагін для повторення запитів (`auto-retry`)](./plugins/auto-retry.md) замість [плагіну для обмеження запитів (`transformer-throttler`)](./plugins/transformer-throttler.md).
```

2023-03-24 12:39 UTC, deptyped approved these changes

2023-03-24 14:35 UTC, LWJerri approved these changes

2023-03-24 14:35 UTC, LWJerri commented on site/docs/uk/advanced/flood.md
> +Ба більше, оскільки запити можуть виконуватися кілька разів, ваш сервер буде споживати більше оперативної пам'яті та пропускної здатності, ніж потрібно.
```suggestion
Ба більше, оскільки запити можуть виконуватися кілька разів, ваш сервер буде споживати більше оперативної памʼяті та пропускної здатності, ніж потрібно.
```

2023-03-24 14:40 UTC, merged