[Ukrainian] Translate `/advanced/transformers.md`
grammyjs/website pull request #696
Opened 2023-03-13 16:18 UTC by Nazar-Ant

2023-03-24 16:57 UTC, LWJerri approved these changes

2023-03-24 16:57 UTC, LWJerri commented on site/docs/uk/advanced/transformers.md
> +grammy також надає вам зворотну інформацію.
```suggestion
grammY також надає вам зворотну інформацію.
```

2023-03-24 16:57 UTC, LWJerri commented on site/docs/uk/advanced/transformers.md
> +const bot = new Bot<MyContext, MyApi>("<токен>");
```suggestion
const bot = new Bot<MyContext, MyApi>("");
```

2023-03-24 18:35 UTC, deptyped requested changes

2023-03-24 18:35 UTC, deptyped commented on site/docs/uk/advanced/transformers.md
> +grammy також надає вам зворотну інформацію.
```suggestion
grammY також надає вам можливість робити протилежне.
```

2023-03-24 18:35 UTC, deptyped commented on site/docs/uk/advanced/transformers.md
> +- обʼєкт payload, що відповідає методу.
```suggestion
- обʼєкт вмісту запиту, що відповідає методу.
```

2023-03-24 18:35 UTC, deptyped commented on site/docs/uk/advanced/transformers.md
> +Замість того, щоб використовувати `next` як останній аргумент для виклику наступного middleware, ви отримуєте `prev` як перший аргумент для виклику вищих перетворювачів.
```suggestion
Замість того, щоб використовувати `next` як останній аргумент для виклику наступного middleware, ви отримуєте `prev` як перший аргумент для виклику наступних перетворювачів.
```

2023-03-24 18:35 UTC, deptyped commented on site/docs/uk/advanced/transformers.md
> +Зауважте, що `Payload<M, R>` посилається на обʼєкт payload, який має відповідати даному методу, а `ApiResponse<ApiCallResult<M, R>>` є повертаємим типом викликаного методу.
```suggestion
Зауважте, що `Payload<M, R>` посилається на обʼєкт вмісту запиту, який має відповідати даному методу, а `ApiResponse<ApiCallResult<M, R>>` це тип результату, що повертається викликаним методом.
```

2023-03-24 18:35 UTC, deptyped commented on site/docs/uk/advanced/transformers.md
> +Наприклад, [плагін для інтерактивних меню](../plugins/menu.md) встановлює перетворювач для перетворення вихідних екземплярів меню на правильний payload.
```suggestion
Наприклад, [плагін для інтерактивних меню](../plugins/menu.md) встановлює перетворювач для перетворення вихідних екземплярів меню на відповідний вміст запиту.
```

2023-03-24 18:35 UTC, deptyped commented on site/docs/uk/advanced/transformers.md
> +- реалізації [обмеження переповнення](../plugins/transformer-throttler.md),
```suggestion
- реалізації [обмеження запитів](../plugins/transformer-throttler.md),
```

2023-03-24 18:35 UTC, deptyped commented on site/docs/uk/advanced/transformers.md
> +- імітування запитів API під час тестування,
```suggestion
- імітування запитів до API під час тестування,
```

2023-03-24 18:35 UTC, deptyped commented on site/docs/uk/advanced/transformers.md
> +Зауважте, однак, що повторний виклик API може мати дивні побічні ефекти: якщо ви викликаєте `endDocument` і передаєте екземпляр потоку читання в `InputFile`, то потік буде прочитано при першій спробі
```suggestion
Зауважте, однак, що повторний виклик API може мати дивні побічні ефекти: якщо ви викликаєте `sendDocument` і передаєте екземпляр потоку читання в `InputFile`, то потік буде прочитано при першій спробі запиту.
```

2023-03-25 09:40 UTC, deptyped approved these changes

2023-03-25 14:00 UTC, merged