[Ukrainian] Translate `/advanced/deployment.md`
grammyjs/website pull request #698
Opened 2023-03-13 17:00 UTC by Nazar-Ant

2023-03-20 14:05 UTC, Nazar-Ant commented on site/docs/uk/advanced/deployment.md
> +3. Перегляньте параметри конфігурації `run` ([довідка API](https://deno.land/x/grammy_runner/mod.ts?s=run)) і переконайтеся, що вони відповідають вашим потребам, або навіть розгляньте можливість ство
Залишу це тут до тих пір, доки не прийде час review
```suggestion
3. Перегляньте параметри конфігурації `run` ([довідка API](https://deno.land/x/grammy_runner/mod.ts?s=run)) і переконайтеся, що вони відповідають вашим потребам, або навіть розгляньте можливість створення власного runner'а з [джерелами (source)](https://deno.land/x/grammy_runner/mod.ts?s=UpdateSource) та [поглиначами (sink)](https://deno.land/x/grammy_runner/mod.ts?s=UpdateSink).
```

2023-03-23 18:53 UTC, deptyped requested changes

2023-03-23 18:53 UTC, deptyped commented on site/docs/uk/advanced/deployment.md
> +2. Використовуйте `await` для всіх `Promise` і встановіть **лінтинг** з правилами, які забезпечують це, щоб ви ніколи не забували.
```suggestion
2. Використовуйте `await` для всіх `Promise` і встановіть **лінтинг** з правилами, які забезпечують це, щоб ви ніколи про це не забували.
```

2023-03-23 18:53 UTC, deptyped commented on site/docs/uk/advanced/deployment.md
> +1. Надсилайте файли, передаючи шлях або `Buffer` замість потоку, або принаймні переконайтеся, що ви [знаєте підводні камені](./transformers.md#випадки-використання-перетворювачів).
```suggestion
1. Надсилайте файли, передаючи шлях або `Buffer` замість потоку, або принаймні переконайтеся, що ви [знаєте про можливі підводні камені](./transformers.md#випадки-використання-перетворювачів).
```

2023-03-23 18:53 UTC, deptyped commented on site/docs/uk/advanced/deployment.md
> +3. Використовуйте [плагін `transformer-throttler`](../plugins/transformer-throttler.md), щоб уникнути перевищення ліміту швидкості.
```suggestion
3. Використовуйте [плагін `transformer-throttler`](../plugins/transformer-throttler.md), щоб уникнути перевищення ліміту кількості запитів.
```

2023-03-23 18:53 UTC, deptyped commented on site/docs/uk/advanced/deployment.md
> +4. **Необовʼязково**. Розгляньте можливість використання [плагіна `auto-retry`](../plugins/auto-retry.md) для автоматичного оброблення помилок, викликаних невдалими запитами, та повторного надсилання
```suggestion
4. **Необовʼязково**. Розгляньте можливість використання [плагіна `auto-retry`](../plugins/auto-retry.md) для автоматичного оброблення помилок, викликаних перевищенням ліміту кількості запитів, та повторного надсилання таких запитів.
```

2023-03-23 18:53 UTC, deptyped commented on site/docs/uk/advanced/deployment.md
> +### Тривале опитування
```suggestion
### Тривале опитування (long polling)
```

2023-03-23 18:53 UTC, deptyped commented on site/docs/uk/advanced/deployment.md
> +2. [Використовуйте `sequentialize` з тією самою функцією вирішувача ключів сеансів, що і middleware сеансу.](./scaling.md#паралелізм-важкий)
```suggestion
2. [Використовуйте `sequentialize` з тією самою функцією для отримання ключу сесії, що і в плагіні сесій.](./scaling.md#паралелізм-важкий)
```

2023-03-23 18:53 UTC, deptyped commented on site/docs/uk/advanced/deployment.md
> +3. Перегляньте параметри конфігурації `run` ([довідка API](https://deno.land/x/grammy_runner/mod.ts?s=run)) і переконайтеся, що вони відповідають вашим потребам, або навіть розгляньте можливість ство
```suggestion
3. Перегляньте параметри конфігурації `run` ([довідка API](https://deno.land/x/grammy_runner/mod.ts?s=run)) і переконайтеся, що вони відповідають вашим потребам, або навіть розгляньте можливість зібрати власний runner зі своїм [джерелом оновлень](https://deno.land/x/grammy_runner/mod.ts?s=UpdateSource) та їх [обробником](https://deno.land/x/grammy_runner/mod.ts?s=UpdateSink).
```

2023-03-23 18:53 UTC, deptyped commented on site/docs/uk/advanced/deployment.md
> +4. Подумайте про реалізацію [graceful shutdown](./reliability.md#graceful-shutdown), щоб зупинити бота, коли ви захочете його вимкнути, тобто перейти на нову версію.
```suggestion
4. Подумайте про реалізацію [graceful shutdown](./reliability.md#graceful-shutdown), щоб завершити обробку поточних оновлень перш ніж ви зупините бота, наприклад, для його оновлення.
```

2023-03-23 18:53 UTC, deptyped commented on site/docs/uk/advanced/deployment.md
> +   Замість цього розгляньте можливість використання системи черг завдань.
```suggestion
   Замість цього розгляньте можливість використання черги завдань.
```

2023-03-23 18:53 UTC, deptyped commented on site/docs/uk/advanced/deployment.md
> +3. Якщо ви налаштували параметр `getSessionKey` для вашого сеансу, [використовуйте `sequentialize` з тією ж функцією вирішувача ключів сеансів, що і middleware сеансу](./scaling.md#паралелізм-важкий)
```suggestion
3. Якщо ви змінювали параметр `getSessionKey` для плагіну сесій, [використовуйте `sequentialize` з тією ж функцією для отримання ключу сесії](./scaling.md#паралелізм-важкий).
```

2023-03-23 18:53 UTC, deptyped commented on site/docs/uk/advanced/deployment.md
> +   Подумайте про те, щоб надихнутися цими [обʼєктами оновлення](https://core.telegram.org/bots/webhooks#testing-your-bot-with-updates), наданими командою Telegram.
```suggestion
   Скористайтеся цими [обʼєктами оновлення](https://core.telegram.org/bots/webhooks#testing-your-bot-with-updates), наданими командою Telegram, для натхнення.
```

2023-03-24 05:47 UTC, Nazar-Ant commented on site/docs/uk/advanced/deployment.md
> +### Тривале опитування
Нащо тут це уточнення? Думаю, читач спочатку прочитає про ці види роботи бота в посібнику, тому вже розрізнятиме їх.

2023-03-24 05:50 UTC, Nazar-Ant commented on site/docs/uk/advanced/deployment.md
> +3. Перегляньте параметри конфігурації `run` ([довідка API](https://deno.land/x/grammy_runner/mod.ts?s=run)) і переконайтеся, що вони відповідають вашим потребам, або навіть розгляньте можливість ство
Точно не треба залишити тут оригінальний термін? Ми ж наче обговорювали, що при першій згадці на сторінці залишимо оригінальний термін поруч з перекладом

2023-03-24 15:32 UTC, LWJerri approved these changes

2023-03-24 15:32 UTC, LWJerri commented on site/docs/uk/advanced/deployment.md
> +### Тривале опитування
I'm agree with @deptyped.

2023-03-24 15:32 UTC, LWJerri commented on site/docs/uk/advanced/deployment.md
> +1. [Використовуєте плагін для конкурентності (runner).](../plugins/runner.md)
```suggestion
1. [Використовуйте плагін для конкурентності (runner).](../plugins/runner.md)
```

2023-03-25 09:29 UTC, deptyped approved these changes

2023-03-25 14:00 UTC, merged