[Ukrainian] Translate `/plugins/session.md`
grammyjs/website pull request #711
Opened 2023-03-16 14:29 UTC by Nazar-Ant

There is an untranslated anchor on line 326 because I can't predict how it will be translated yet. Since I'm working on two more plugins, I'll take the plugin to which the anchor refers to and translate it after they're done.

2023-03-19 13:28 UTC, Nazar-Ant commented on site/docs/uk/plugins/session.md
> +Переконайтеся, що ви розумієте наслідки такої конфігурації, прочитавши [цю статтю](../guide/deployment-types.md) й особливо [цю](./runner.md#sequential-processing-where-necessary).
```suggestion
Переконайтеся, що ви розумієте наслідки такої конфігурації, прочитавши [цю статтю](../guide/deployment-types.md) й особливо [цю](./runner.md#послідовна-обробка-там-де-це-необхідно).
```

2023-03-20 17:14 UTC, Nazar-Ant commented on site/docs/uk/plugins/session.md
> +Відвідайте [це](https://github.com/grammyjs/storages/tree/main/packages#grammy-storages), щоб переглянути список підтримуваних на даний момент адаптерів та отримати інструкції щодо їх використання.
```suggestion
Відвідайте [цей репозиторій](https://github.com/grammyjs/storages/tree/main/packages#grammy-storages), щоб переглянути список підтримуваних на даний момент адаптерів та отримати інструкції щодо їх використання.
```

2023-04-11 15:26 UTC, LWJerri requested changes

2023-04-12 04:37 UTC, Nazar-Ant commented on site/docs/uk/plugins/session.md
> +> [Стрибайте вниз](#як-використовувати-сесіі), якщо ви знаєте, як працюють сесії.
літера " ї " не працюватиме в посиланнях

2023-04-12 04:40 UTC, Nazar-Ant commented on site/docs/uk/plugins/session.md
> +Зверніть увагу, що нам також потрібно [налаштувати тип контексту](../guide/context.md#налаштування-обєкта-контексту), щоб зробити сесію доступним у ньому.
Я повиправляю посилання, коли закінчемо переклад. Це через те, що на початку перекладу ми використовували інший апостроф. Зі старим апострофом по слово "обʼєкт" має бути "об-єкт". Поки що можна не звертати на це увагу

2023-04-12 04:50 UTC, Nazar-Ant commented on site/docs/uk/plugins/session.md
> +Він не потребує жодних налаштувань - вся автентифікація здійснюється за допомогою вашого токена бота.
Ці слова відрізняються лише однією літерою. Варіант літерою "в" використовується вікіпедією, і цей варіант мені більше до вподоби. Почекаємо думки @deptyped

2023-04-12 10:59 UTC, deptyped commented on site/docs/uk/plugins/session.md
> +> Безкоштовне сховище призначене для використання в проєктах хобі.
Мені здається, переклад "в хобі проєктах" вдаліший, але потрібен дефіс.
```suggestion
> Безкоштовне сховище призначене для використання в хобі-проєктах.
```

2023-04-19 21:09 UTC, deptyped requested changes

2023-04-19 21:09 UTC, deptyped commented on site/docs/uk/plugins/session.md
> +У коді плагіна просто постійно очікуйте на `ctx.session`: якщо буде передано обʼєкт, який не є `Promise`, він буде просто обчислений для себе; отже, ви фактично пишете код лише для лінивих сесій, про
```suggestion
У коді плагіна просто постійно очікуйте на `ctx.session`: якщо буде передано обʼєкт, який не є `Promise`, буде повернуто той самий обʼєкт; отже, ви фактично пишете код лише для лінивих сесій, проте автоматично підтримуєте строгі сесії.
```

2023-04-19 21:09 UTC, deptyped commented on site/docs/uk/plugins/session.md
> +Ви можете вибрати будь-які номери JavaScript як версії.
```suggestion
Ви можете вибрати будь-які числа, які є в JavaScript, як версії.
```

2023-04-20 15:16 UTC, deptyped approved these changes

2023-04-20 15:28 UTC, merged