[Ukrainian] Translate `/plugins/fluent.md`
grammyjs/website pull request #717
Opened 2023-03-19 16:28 UTC by Nazar-Ant

2023-03-21 09:36 UTC, Nazar-Ant commented on site/docs/uk/plugins/fluent.md
> +Він демонструє три важливі особливості Fluent, а саме: **терміни**, **змінні підстановки**, які також відомі як _вставні обʼєкти_, та **множини**.
```suggestion
Він демонструє три важливі особливості Fluent, а саме: **терміни**, **підставлення змінних** та **множинність**.
```

2023-03-31 00:47 UTC, deptyped requested changes

2023-03-31 00:47 UTC, deptyped commented on site/docs/uk/plugins/fluent.md
> +І останній вираз _на рядкях з 5-го по 9-й_ визначає **селектор**, який дуже схожий на вираз `switch`, який приймає результат спеціальної функції `NUMBER`, застосованої до змінної `applesCount`, і виб
```suggestion
І останній вираз _на рядках з 5-го по 10-й_ визначає **селектор**, який дуже схожий на вираз `switch`, який приймає результат спеціальної функції `NUMBER`, застосованої до змінної `applesCount`, і вибирає одне з трьох можливих повідомлень для перекладу на основі значення, що відповідає результату.
```

2023-03-31 00:47 UTC, deptyped commented on site/docs/uk/plugins/fluent.md
> +`welcome` - це **ідентифікатор повідомлення**, який використовуватиметься для посилання на його зміст під час відтворення.
```suggestion
`welcome` - це **ідентифікатор повідомлення**, який використовуватиметься для посилання на його зміст під час рендерингу.
```

2023-03-31 00:47 UTC, deptyped commented on site/docs/uk/plugins/fluent.md
> +Конструкція `{-bot-name}` посилається на попередньо визначений термін і буде замінена його значенням при відтворенні.
```suggestion
Конструкція `{-bot-name}` посилається на попередньо визначений термін і буде замінена його значенням під час рендерингу.
```

2023-03-31 00:47 UTC, deptyped commented on site/docs/uk/plugins/fluent.md
> +Передусім, вам потрібно налаштувати бота на використання flavor для контексту Fluent.
```suggestion
Передусім, вам потрібно налаштувати бота на використання flavor для контексту з плагіну.
```

2023-03-31 00:47 UTC, deptyped commented on site/docs/uk/plugins/fluent.md
> +  // щоб відтворити повідомлення, вказавши його ідентифікатор та додаткові параметри:
```suggestion
  // щоб зробити рендеринг повідомлення, вказавши його ідентифікатор та додаткові параметри:
```

2023-03-31 00:47 UTC, deptyped commented on site/docs/uk/plugins/fluent.md
> +## Відтворення локалізованих повідомлень
```suggestion
## Рендеринг локалізованих повідомлень
```

2023-03-31 00:47 UTC, deptyped commented on site/docs/uk/plugins/fluent.md
> +Чудово, тепер у нас є все необхідне для відтворення наших повідомлень!
```suggestion
Чудово, тепер у нас є все необхідне для рендерингу наших повідомлень!
```

2023-03-31 00:47 UTC, deptyped commented on site/docs/uk/plugins/fluent.md
> +Звичайно, ви побачите власне ім'я замість " Slava".
```suggestion
Звичайно, ви побачите власне ім'я замість "Slava".
```

2023-03-31 00:47 UTC, deptyped commented on site/docs/uk/plugins/fluent.md
> +Спробуйте змінити значення змінної `applesCount`, щоб побачити, як зміниться відтворюване повідомлення!
```suggestion
Спробуйте змінити значення змінної `applesCount`, щоб побачити, як зміниться рендер повідомлення!
```

2023-03-31 00:47 UTC, deptyped commented on site/docs/uk/plugins/fluent.md
> +Тепер давайте подивимося, як це повідомлення може бути відтворене ботом.
```suggestion
Тепер давайте подивимося, як зробити рендеринг повідомлення вижче за допомогою бота.
```

2023-03-31 05:12 UTC, Nazar-Ant commented on site/docs/uk/plugins/fluent.md
> +Тепер давайте подивимося, як це повідомлення може бути відтворене ботом.
Тут під словом "вижче" мається на увазі "вищенаведене"?

```suggestion
Тепер давайте подивимося, як зробити рендеринг вищенаведеного повідомлення за допомогою бота.
```

2023-03-31 10:34 UTC, deptyped approved these changes

2023-04-01 00:37 UTC, LWJerri approved these changes

2023-04-01 04:21 UTC, merged