[Ukrainian] Translate `/plugins/i18n.md`
grammyjs/website pull request #723
Opened 2023-03-21 16:20 UTC by Nazar-Ant

2023-03-31 01:02 UTC, deptyped requested changes

2023-03-31 01:02 UTC, deptyped commented on site/docs/uk/plugins/i18n.md
> +Наприклад, якщо ви повторно використовуєте ім'я користувача у багатьох повідомленнях, то може бути нудно передавати всюди контекст перекладу `{ name: ctx.from.first_name }`.
```suggestion
Наприклад, якщо ви повторно використовуєте ім'я користувача у багатьох повідомленнях, то може бути досить втомливо передавати всюди контекст перекладу `{ name: ctx.from.first_name }`.
```

2023-03-31 10:34 UTC, deptyped approved these changes

2023-04-01 00:38 UTC, LWJerri approved these changes

2023-04-01 04:21 UTC, merged