[Ukranian] Translate `/hosting/comparison.md`
grammyjs/website pull request #724
Opened 2023-03-22 04:54 UTC by LWJerri

2023-03-22 05:42 UTC, Nazar-Ant commented on site/docs/uk/hosting/comparison.md
> +Тому спільнота grammY збирає свої досвіди на цій сторінці.
Хоча в оригіналі написано `experiences`, краще буде написати так, що у спільноти один досвід, а не багато.

```suggestion
Тому спільнота grammY збирає свій досвід на цій сторінці.
```

2023-03-22 05:45 UTC, Nazar-Ant commented on site/docs/uk/hosting/comparison.md
> +Замість цього, ви можете звернутися до компанії, щоб запустити бота в хмарі.
```suggestion
Для того, щоб бот був онлайн 24 години на день, потрібно протягом усього дня тримати компʼютер запущеним.
Як [зазначено у вступі](../guide/introduction.html#як-підтримувати-роботу-бота), вам, імовірно, не захочеться робити це на своєму ноутбуці або домашньому компʼютері.
Замість цього, ви можете звернутися до компанії, щоб запустити бота у хмарі.
```

2023-03-22 05:47 UTC, Nazar-Ant commented on site/docs/uk/hosting/comparison.md
> +У нас є дві таблиці порівнянь: одна для хостингу [безсерверного](#безсервернии-хостинг-serverless) типу та інша для [VPS](#vps).
```suggestion
У нас є дві таблиці порівнянь: одна для хостингу [безсерверного](#безсервернии-хостинг-serverless) типу й інша для [VPS](#vps).
```

2023-03-22 05:48 UTC, Nazar-Ant commented on site/docs/uk/hosting/comparison.md
> +### Безсерверний хостинг (Serverless)
```suggestion
### Безсерверний хостинг (serverless)
```

2023-03-22 05:56 UTC, Nazar-Ant commented on site/docs/uk/hosting/comparison.md
> +Тому ми рекомендуємо використовувати інший тип хостингу для більш складних ботів, наприклад, [VPS](#vps).
```suggestion
Однак це має недолік у тому, що ваш бот за замовчуванням не має доступу до постійного сховища, як-от локальна файлова система.
Замість цього вам часто доведеться мати окрему базу даних і підключатися до неї, якщо вам потрібно зберігати дані на постійній основі.
Тому ми рекомендуємо використовувати інший тип хостингу для більш складних ботів: наприклад, [VPS](#vps).
```

2023-03-22 13:46 UTC, Nazar-Ant approved these changes

2023-03-23 12:55 UTC, deptyped requested changes

2023-03-23 12:55 UTC, deptyped commented on site/docs/uk/hosting/comparison.md
> +Зазвичай ви можете отримати до нього доступ за допомогою [SSH](https://en.wikipedia.org/wiki/Secure_Shell).
```suggestion
Зазвичай ви можете отримати до нього доступ за допомогою [SSH](https://uk.wikipedia.org/wiki/SSH).
```

2023-03-23 12:55 UTC, deptyped commented on site/docs/uk/hosting/comparison.md
> +| ГБ-ч         | використання памʼяті          | гігабайт-години                                 | Один гігабайт, використаний протягом однієї години.          |
```suggestion
| ГБ-с         | використання памʼяті          | гігабайт-секунди                                | Один гігабайт, що використовується протягом однієї секунди.  |
| ГБ-ч         | використання памʼяті          | гігабайт-години                                 | Один гігабайт, що використовується протягом однієї години.   |
```

2023-03-23 13:00 UTC, merged