[Ukranian] Translate `/hosting/cloudflare-workers.md`
grammyjs/website pull request #725
Opened 2023-03-22 04:54 UTC by LWJerri

2023-03-22 06:29 UTC, Nazar-Ant commented on site/docs/uk/hosting/cloudflare-workers.md
> +Цей посібник допоможе вам розмістити ваш Telegram-бот на Cloudflare Workers.
```suggestion
[Cloudflare Workers](https://workers.cloudflare.com/) - це загальнодоступна безсерверна обчислювальна платформа, яка пропонує зручне та просте рішення для запуску JavaScript на [межі мережі](https://en.wikipedia.org/wiki/Edge_computing).
Маючи здатність обробляти HTTP трафік та базуючись на [Service Worker API](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API), розробка ботів Telegram стає легкою справою.
Крім того, ви можете розробляти [вебдодатки](https://core.telegram.org/bots/webapps) на межі мережі, і все це безкоштовно у межах певних лімітів.

Цей посібник допоможе вам розмістити вашого бота Telegram на Cloudflare Workers.
```

2023-03-22 06:33 UTC, Nazar-Ant commented on site/docs/uk/hosting/cloudflare-workers.md
> +Щоб продовжити, переконайтеся, що у вас є [аккаунт Cloudflare](https://dash.cloudflare.com/login) з налаштованою піддоменою [workers](https://dash.cloudflare.com/?account=workers) налаштуваннями.
```suggestion
Щоб продовжити, переконайтеся, що у вас є [обліковий запис Cloudflare](https://dash.cloudflare.com/login) з [налаштованим](https://dash.cloudflare.com/?account=workers) піддоменом worker'ів.
```

2023-03-22 06:35 UTC, Nazar-Ant commented on site/docs/uk/hosting/cloudflare-workers.md
> +## Creating Your Bot
```suggestion
## Створення вашого бота
```

2023-03-22 06:38 UTC, Nazar-Ant commented on site/docs/uk/hosting/cloudflare-workers.md
> +// Див. https://developers.cloudflare.com/workers/platform/environment-variables/#secrets-on-deployed-workers
Я всюди писав без скорочень. Думаю, тоді варто й тут писати без скорочень

```suggestion
// Дивіться https://developers.cloudflare.com/workers/platform/environment-variables/#secrets-on-deployed-workers
```

2023-03-22 06:42 UTC, Nazar-Ant commented on site/docs/uk/hosting/cloudflare-workers.md
> +account_id = 'ваш ідентифікатор облікового запису' # Отримайте його з панелі керування Cloudflare.
```suggestion
account_id = 'ідентифікатор вашого облікового запису' # Отримайте його з панелі керування Cloudflare.
```

2023-03-22 06:43 UTC, Nazar-Ant commented on site/docs/uk/hosting/cloudflare-workers.md
> +name = 'my-bot' # Назва вашого бота, яка зʼявиться в URL-адресі вебхука, наприклад: https://my-bot.my-subdomain.workers.dev
Тут "наприклад" не потрібен, навіть якщо він є в оригіналі

```suggestion
name = 'my-bot' # Назва вашого бота, яка зʼявиться в URL-адресі вебхука: https://my-bot.my-subdomain.workers.dev
```

2023-03-22 06:44 UTC, Nazar-Ant commented on site/docs/uk/hosting/cloudflare-workers.md
> +main = "src/index.js"  # Основний файл робітника.
Ми поки не дійшли згоди як писати "worker", тому що не обговорювали це, тому я всюди писав наступним чином

```suggestion
main = "src/index.js"  # Основний файл worker'а.
```

2023-03-22 06:45 UTC, Nazar-Ant commented on site/docs/uk/hosting/cloudflare-workers.md
> +Після цього ви можете розгорнути за допомогою наступної команди:
```suggestion
Після цього ви можете розгорнути бота за допомогою наступної команди:
```

2023-03-22 06:46 UTC, Nazar-Ant commented on site/docs/uk/hosting/cloudflare-workers.md
> +Якщо він відповідає, це означає, що все працює!
```suggestion
Якщо він відповідає, значить все працює!
```

2023-03-22 06:46 UTC, Nazar-Ant commented on site/docs/uk/hosting/cloudflare-workers.md
> +## Відлагодження вашого бота
```suggestion
## Налагодження вашого бота
```

2023-03-22 06:47 UTC, Nazar-Ant commented on site/docs/uk/hosting/cloudflare-workers.md
> +Для тестування та відлагодження бота ви можете запустити локальний або віддалений сервер розробки перед розгортанням бота в продакшн.
```suggestion
Для тестування та налагодження бота ви можете запустити локальний або віддалений сервер розробки перед розгортанням бота у production.
```

2023-03-22 06:48 UTC, Nazar-Ant commented on site/docs/uk/hosting/cloudflare-workers.md
> +Після запуску сервера розробки ви можете протестувати свого бота, надсиланням зразкових оновлень до нього за допомогою інструментів, таких як `curl`, [Insomnia](https://insomnia.rest) або [Postman](h
```suggestion
Після запуску сервера розробки ви можете протестувати свого бота, надсилаючи приклади оновлень до нього за допомогою певних інструментів, як-от `curl`, [Insomnia](https://insomnia.rest) або [Postman](https://postman.com).
```

2023-03-22 14:54 UTC, Nazar-Ant approved these changes

2023-03-23 12:27 UTC, deptyped requested changes

2023-03-23 13:00 UTC, merged