[Ukranian] Translate `/hosting/vercel.md`
grammyjs/website pull request #731
Opened 2023-03-22 04:54 UTC by LWJerri

2023-03-22 14:03 UTC, Nazar-Ant commented on site/docs/uk/hosting/vercel.md
> +У цьому посібнику ви дізнаєтесь, як розгорнути свого бота на [Vercel](https://vercel.com/) за допомогою [Vercel Serverless Functions](https://vercel.com/docs/concepts/functions/serverless-functions),
```suggestion
У цьому посібнику ви дізнаєтесь, як розгорнути свого бота на [Vercel](https://vercel.com/) за допомогою [Vercel Serverless Functions](https://vercel.com/docs/concepts/functions/serverless-functions); передбачається, що у вас вже є обліковий запис [Vercel](https://vercel.com).
```

2023-03-22 14:03 UTC, Nazar-Ant commented on site/docs/uk/hosting/vercel.md
> +Єдиним передумовою для початку роботи з **Vercel Serverless Functions** є переміщення вашого коду до каталогу `api/`, як показано нижче.
```suggestion
Єдинj. передумовою для початку роботи з **Vercel Serverless Functions** є переміщення вашого коду до каталогу `api/`, як показано нижче.
```

2023-03-22 14:06 UTC, Nazar-Ant commented on site/docs/uk/hosting/vercel.md
> +Якщо ви використовуєте TypeScript, то вам, напевно, захочеться встановити `@vercel/node` як dev-залежність, але це необовʼязково для слідування цьому посібнику.
```suggestion
Якщо ви використовуєте TypeScript, то вам, напевно, захочеться встановити `@vercel/node` як залежність розробки (`dev dependency`), але це необовʼязково для слідування цьому посібнику.
```

2023-03-22 14:07 UTC, Nazar-Ant commented on site/docs/uk/hosting/vercel.md
> +Для нашої структури прикладу, його вміст буде:
```suggestion
Для прикладу наданої вище структури його вміст буде:
```

2023-03-22 14:09 UTC, Nazar-Ant commented on site/docs/uk/hosting/vercel.md
> +Якщо ви хочете дізнатися більше про файл конфігурації vercel.json, див. [документацію](https://vercel.com/docs/project-configuration).
```suggestion
Якщо ви хочете дізнатися більше про файл конфігурації vercel.json, дивіться [документацію](https://vercel.com/docs/project-configuration).
```

2023-03-22 14:10 UTC, Nazar-Ant commented on site/docs/uk/hosting/vercel.md
> +## В Панелі управління Vercel
```suggestion
## У панелі керування Vercel
```

2023-03-22 14:11 UTC, Nazar-Ant commented on site/docs/uk/hosting/vercel.md
> +Припускаючи, що у вас вже є обліковий запис в Vercel, який підключений до GitHub, додайте новий проєкт та виберіть репозиторій свого бота.
```suggestion
Припускаючи, що у вас вже є обліковий запис у Vercel, який підключений до GitHub, додайте новий проєкт та виберіть репозиторій свого бота.
```

2023-03-22 14:11 UTC, Nazar-Ant commented on site/docs/uk/hosting/vercel.md
> +- Директорія виводу: `build`
```suggestion
- Каталог виведення: `build`
```

2023-03-22 14:12 UTC, Nazar-Ant commented on site/docs/uk/hosting/vercel.md
> +## Налаштування Webhook
```suggestion
## Налаштування вебхуку
```

2023-03-22 14:14 UTC, Nazar-Ant commented on site/docs/uk/hosting/vercel.md
> +`HOST_URL` трохи заплутано, оскільки потрібно використовувати домен вашого додатку **Vercel з маршрутом до коду боту**, наприклад, `https://appname.vercel.app/api/bot`.
```suggestion
`HOST_URL` трохи заплутано, оскільки потрібно використовувати домен вашого **застосунку Vercel з маршрутом до коду бота**: наприклад, `https://appname.vercel.app/api/bot`.
```

2023-03-23 12:20 UTC, deptyped requested changes

2023-03-23 12:20 UTC, deptyped commented on site/docs/uk/hosting/vercel.md
> +> Якщо ви хочете використовувати безкоштовний тарифний план Vercel, ваші конфігурації `memory` та `maxDuration` можуть бути схожими з тими, що наведені вище, щоб не обмежувати їх.
```suggestion
> Якщо ви хочете використовувати безкоштовний тарифний план Vercel, ваші конфігурації `memory` та `maxDuration` мають виглядати так, як показано вище, щоб не виходити за межі безкоштовних лімітів. 
```

2023-03-23 12:20 UTC, deptyped commented on site/docs/uk/hosting/vercel.md
> +Якщо ви хочете дізнатися більше про файл конфігурації vercel.json, дивіться [документацію](https://vercel.com/docs/project-configuration).
```suggestion
Якщо ви хочете дізнатися більше про файл конфігурації `vercel.json`, дивіться [документацію Vercel](https://vercel.com/docs/project-configuration).
```

2023-03-23 12:20 UTC, deptyped commented on site/docs/uk/hosting/vercel.md
> +У файлі `tsconfig.json` ми повинні вказати каталог виведення як `build/`, а наш кореневий каталог як `api/`.
```suggestion
У файлі `tsconfig.json` ми повинні вказати каталог виведення збірки як `build/`, а кореневий каталог як `api/`.
```

2023-03-23 12:20 UTC, deptyped commented on site/docs/uk/hosting/vercel.md
> +`HOST_URL` трохи заплутано, оскільки потрібно використовувати домен вашого **застосунку Vercel з маршрутом до коду бота**: наприклад, `https://appname.vercel.app/api/bot`.
```suggestion
`HOST_URL` потребує особливої уваги, оскільки потрібно використовувати домен вашого **застосунку Vercel з маршрутом до коду бота**: наприклад, `https://appname.vercel.app/api/bot`.
```

2023-03-23 12:57 UTC, deptyped approved these changes

2023-03-23 13:00 UTC, merged