[Ukranian] Translate `/hosting/vps.md`
grammyjs/website pull request #732
Opened 2023-03-22 04:54 UTC by LWJerri

2023-03-22 14:21 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +У цьому керівництві ви дізнаєтесь про різні методи запуску вашого бота на VPS, тримаючи його онлайн 24/7, зробивши його автоматичним запуском при запуску вашого VPS і перезавантаженням у разі збоїв.
```suggestion
У цьому посібнику ви дізнаєтеся про різні методи запуску вашого бота на VPS, підтримання його в онлайні 24/7, автоматичний запуск при завантаженні вашого VPS і перезапуск при збоях.
```

2023-03-22 14:21 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +systemd - це потужний менеджер служб, який передвстановлений в багатьох дистрибутивах Linux, переважно на основі Debian.
```suggestion
systemd - це потужний менеджер служб, який передвстановлений у багатьох дистрибутивах Linux, переважно на основі Debian.
```

2023-03-22 14:22 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +<full_runtime_path> <options> <full_entry_file_path>
```suggestion
<повний шлях до середовища виконання> <параметри> <повний шлях до файлу входу>
```

2023-03-22 14:23 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +# Node.js приклад:
```suggestion
# Приклад для Deno:
# /home/user/.deno/bin/deno --allow-all /home/user/bot1/mod.ts

# Приклад для Node.js:
```

2023-03-22 14:23 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +1. Перейдіть до директорії служб:
```suggestion
1. Перейдіть до каталогу служб:
```

2023-03-22 14:24 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +2. Відкрийте ваш новий файл служби з редактором:
```suggestion
2. Відкрийте ваш новий файл служби за допомогою редактора:
```

2023-03-22 14:25 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +> Також зверніть увагу, що якщо Deno встановлено для іншого користувача, а не root, вам може знадобитися вказати це в розділі служби, наприклад, `User=<the_user>`.
```suggestion
> Також зверніть увагу, що якщо Deno встановлено для іншого користувача, а не root, вам може знадобитися вказати це в розділі служби: наприклад, `User=<імʼя користувача>`.
```

2023-03-22 14:25 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +> Для отримання додаткової інформації про файлові одиниці відвідайте [цей сайт](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembl
```suggestion
> Для отримання додаткової інформації про файли служб відвідайте [цей сайт](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_working-with-systemd-unit-files_configuring-basic-system-settings).
```

2023-03-22 14:26 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +#### запуск
```suggestion
#### Запуск
```

2023-03-22 14:26 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +systemctl start <service_name>
```suggestion
systemctl start <назва служби>
```

2023-03-22 14:27 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +> Приклад: `systemctl start bot1`
```suggestion
> Наприклад, `systemctl start bot1`
```

2023-03-22 14:29 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +#### Запунити
```suggestion
#### Зупинення
```

2023-03-22 14:30 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +## PM2 (Тільки Node.js)
```suggestion
## PM2 (тільки для Node.js)
```

2023-03-22 14:31 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +PM2 - це менеджер процесів-демонів для Node.js, який допоможе вам керувати та тримати ваш додаток в режимі онлайн 24/7.
```suggestion
PM2 - це менеджер демонів процесів для Node.js, який допоможе вам керувати та тримати ваш застосунок у режимі онлайн 24/7.
```

2023-03-22 14:31 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +### Управління додатками
```suggestion
### Управління застосунками
```

2023-03-22 14:31 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +> `<app_name>` може бути будь-яким ідентифікатором для вашого додатку, наприклад: `bot1`.
```suggestion
> `<app_name>` може бути будь-яким ідентифікатором для вашого додатку: наприклад, `bot1`.
```

2023-03-22 14:32 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +> `<entry_point>` повинен бути шляхом до вашого файлу index (який запускає вашого бота).
```suggestion
> `<entry_point>` повинен бути шляхом до вашого файлу входу, який запускає вашого бота.
```

2023-03-22 14:34 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +Перезапуск додатку передбачає його зупинку та знову запуск.
```suggestion
Перезапуск додатку передбачає його зупинку та повторний запуск.
```

2023-03-22 14:34 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +#### перезавантаження (reload)
```suggestion
#### Перезавантаження
```

2023-03-22 14:35 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +Це рекомендується для безстійких додатків.
```suggestion
Це рекомендується для застосунків, які не мають стану.
```

2023-03-22 14:36 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +При видаленні ви запиняєте ваш додаток та видаляєте всі логи та метрики.
```suggestion
При видаленні ви зупиняєте ваш застосунок та видаляєте всі логи та метрики.
```

2023-03-22 14:37 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +Для більшої інформації, будь ласка, відвідайте це посилання <https://pm2.keymetrics.io/docs>.
```suggestion
Для отримання додаткової інформації, будь ласка, відвідайте це посилання <https://pm2.keymetrics.io/docs>.
```

2023-03-22 14:40 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +ExecStart=<start_command>
```suggestion
ExecStart=<команда запуску>
```

2023-03-22 14:42 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +systemctl enable <service_name>
```suggestion
systemctl enable <назва служби>
```

2023-03-22 14:42 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +systemctl status <service_name>
```suggestion
systemctl status <назва служби>
```

2023-03-22 14:42 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +systemctl stop <service_name>
```suggestion
systemctl stop <назва служби>
```

2023-03-22 14:42 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +systemctl disable <service_name>
```suggestion
systemctl disable <назва служби>
```

2023-03-22 14:43 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +pm2 start --name <app_name> <entry_point>
```suggestion
pm2 start --name <назва застосунку> <файл входу>
```

2023-03-22 14:44 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +pm2 restart <app_name>
```suggestion
pm2 restart <назва застосунку>
```

2023-03-22 14:44 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +pm2 reload <app_name>
```suggestion
pm2 reload <назва застосунку>
```

2023-03-22 14:44 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +pm2 stop <app_name>
```suggestion
pm2 stop <назва застосунку>
```

2023-03-22 14:45 UTC, Nazar-Ant commented on site/docs/uk/hosting/vps.md
> +pm2 del <app_name>
```suggestion
pm2 del <назва застосунку>
```

2023-03-23 11:49 UTC, deptyped requested changes

2023-03-23 11:49 UTC, deptyped commented on site/docs/uk/hosting/vps.md
> +2. Ви також повинні мати повний шлях до вашого файлу входу.
```suggestion
2. Ви також повинні мати повний шлях до файлу, який є точкою входу вашого застосунку.
```

2023-03-23 11:49 UTC, deptyped commented on site/docs/uk/hosting/vps.md
> +> Також зверніть увагу, що якщо Deno встановлено для іншого користувача, а не root, вам може знадобитися вказати це в розділі служби: наприклад, `User=<імʼя користувача>`.
```suggestion
> Також зверніть увагу, що якщо Deno встановлено для іншого користувача, а не root, вам може знадобитися додати `User=<імʼя користувача>` в розділі `[Service]`.
```

2023-03-23 11:49 UTC, deptyped commented on site/docs/uk/hosting/vps.md
> +> Замініть `<назва служби>` на назву файла, який містить вашу службу.
```suggestion
> Замініть `<назва служби>` на назву файла служби, яку ви створили.
```

2023-03-23 11:49 UTC, deptyped commented on site/docs/uk/hosting/vps.md
> +#### Перевірка логів
```suggestion
#### Перегляд журналювання
```

2023-03-23 11:49 UTC, deptyped commented on site/docs/uk/hosting/vps.md
> +#### Скасування запуску при завантаженні
```suggestion
#### Вимкнення запуску при завантаженні
```

2023-03-23 11:49 UTC, deptyped commented on site/docs/uk/hosting/vps.md
> +### Просунута інформація
```suggestion
### Додаткова інформація
```

2023-03-23 12:58 UTC, deptyped approved these changes

2023-03-23 13:00 UTC, merged