[Ukranian] Translate `/resources/faq.md`
grammyjs/website pull request #735
Opened 2023-03-22 12:08 UTC by LWJerri

2023-03-22 17:23 UTC, deptyped requested changes

2023-03-22 17:23 UTC, deptyped commented on site/docs/uk/resources/faq.md
> +:::
```suggestion
::: tip Передача сутностей замість форматування
Ви можете попередньо розібрати сутності для Telegram і вказати `entities` при надсиланні повідомлення.
Тоді текст вашого повідомлення може бути звичайним текстом без форматування.
Таким чином, вам не доведеться турбуватися про екранування незвичайних символів.
Може здаватися, що це потребує більше коду, але це набагато надійніше і більш безпечне рішення цієї проблеми.
А головне, що це значно простіше завдяки плагіну [parse-mode](../plugins/parse-mode.md).
:::
```

2023-03-22 17:23 UTC, deptyped commented on site/docs/uk/resources/faq.md
> +Поговоріть з [@BotFather](https://t.me/BotFather), щоб дізнатися, який токен у бота.
```suggestion
### 401 Unauthorized

Ваш токен бота неправильний.
Можливо, ви вважаєте, що він правильний.
Але це не так.
Зверніться до [@BotFather](https://t.me/BotFather), щоб дізнатися токен вашого боту.
```

2023-03-22 17:23 UTC, deptyped commented on site/docs/uk/resources/faq.md
> +  Підказка: Порівняйте поля `status` старого і нового учасника чату.
```suggestion
### 403 Forbidden: bot was blocked by the user

Ймовірно, ви намагалися надіслати повідомлення користувачеві, однак виникла ця помилка.

Коли користувач блокує вашого бота, ви не зможете надсилати йому повідомлення або іншим чином взаємодіяти з ним, за винятком випадків, коли ваш бот був запрошений до групового чату, учасником якого є цей заблокований користувач.
Telegram робить це для захисту своїх користувачів.
Ви не можете нічого з цим зробити.

Але ви можете:

- Обробити цю помилку і, наприклад, видалити дані користувача з вашої бази даних.
- Ігнорувати помилку.
- Обробляти оновлення `my_chat_member` через `bot.on("my_chat_member")`, щоб отримувати сповіщення, коли користувач блокує вашого бота.
  Порада: Порівняйте поля `status` старого і нового учасника чату.
```

2023-03-22 17:23 UTC, deptyped commented on site/docs/uk/resources/faq.md
> +Ви можете запитати нас в [груповому чаті](https://t.me/grammyjs) (або в [російськомовному груповому чаті](https://t.me/grammyjs_ru)).
```suggestion
### 404 Not found

Якщо це відбувається під час запуску бота, це означає, що токен бота неправильний.
Зверніться до [@BotFather](https://t.me/BotFather), щоб дізнатися токен вашого боту.

Якщо ваш бот працює нормально більшість часу, але раптом ви отримуєте помилку 404, це означає, що ви робите дещо незвичайне.
Ви можете задати нам питання в [англомовному](https://t.me/grammyjs) або [російськомовному](https://t.me/grammyjs_ru) групових чатах.
```

2023-03-22 17:23 UTC, deptyped commented on site/docs/uk/resources/faq.md
> +Зверніться до [@BotFather](https://t.me/BotFather), щоб зробити це.
```suggestion
### 409 Conflict: terminated by other getUpdates request

Ви помилково запустили бота двічі під час тривалого опитування.
Ви можете запустити лише один екземпляр бота.

Якщо ви вважаєте, що запустили бота лише один раз, ви можете просто змінити токен вашого бота.
Це зупинить всі інші екземпляри бота.
Зверніться до [@BotFather](https://t.me/BotFather), щоб це зробити.
```

2023-03-22 18:14 UTC, deptyped approved these changes

2023-03-23 13:03 UTC, Nazar-Ant commented on site/docs/uk/resources/faq.md
> +Якщо у цьому ЧаПи немає відповіді на ваше запитання, також ознайомтеся з [ЧаПи про ботів](https://core.telegram.org/bots/faq), створеним командою Telegram.
1. "У цих частих питаннях"
2. "ознайомтеся з частими питаннями, створеними командою ТГ"

```suggestion
Якщо у цих ЧаПи немає відповіді на ваше запитання, ознайомтеся з [ЧаПи про ботів](https://core.telegram.org/bots/faq), створеними командою Telegram.
```

2023-03-23 13:05 UTC, Nazar-Ant commented on site/docs/uk/resources/faq.md
> +   Якщо це так, то він знаходиться в об'єкті для необов'язкових опцій під назвою `other`.
```suggestion
   Якщо це так, то він знаходиться в об'єкті необов'язкових параметрів під назвою `other`.
```

2023-03-23 13:06 UTC, Nazar-Ant commented on site/docs/uk/resources/faq.md
> +   Передайте `{ назва_параметру: значення }` у цьому місці і це спрацює.
```suggestion
   Передайте `{ назва_параметру: значення }` у цьому місці, тоді це спрацює.
```

2023-03-23 13:14 UTC, Nazar-Ant commented on site/docs/uk/resources/faq.md
> +4. Зверніться за допомогою до нас у [груповий чат](https://t.me/grammyjs).
```suggestion
4. Звернутися по допомогу до нас у [груповий чат](https://t.me/grammyjs).
```

2023-03-23 13:20 UTC, Nazar-Ant commented on site/docs/uk/resources/faq.md
> +grammY розробляється в першу чергу для Deno, але вона так само добре підтримує Node.js.
```suggestion
grammY розробляється в першу чергу для Deno, але так само добре підтримує Node.js.
```

2023-03-23 13:24 UTC, LWJerri commented on site/docs/uk/resources/faq.md
> +> Він розповів про свої 10 причин жалітись про Node.js у цьому [відео](https://youtu.be/M3BM9TB-8yA).
That's not exactly what we need. The original video is on behalf of the founder of Node.js, where he talks about 10 reasons and regrets about Node.js and about Deno.

2023-03-23 13:25 UTC, deptyped commented on site/docs/uk/resources/faq.md
> +5. Можна попросити Telegram збільшити ліміти, але це дуже малоймовірно, якщо ви не виконали кроки 1-3.
2-й крок загубився

```suggestion
5. Можна попросити Telegram збільшити ліміти, але це дуже малоймовірно, якщо ви не виконали кроки з 1-го по 3-й.
```

2023-03-23 13:27 UTC, LWJerri commented on site/docs/uk/resources/faq.md
> +> Він розповів про свої 10 причин жалітись про Node.js у цьому [відео](https://youtu.be/M3BM9TB-8yA).
The original video has Russian subtitles. We can ask the user to include them and that's it.

2023-03-23 13:30 UTC, Nazar-Ant approved these changes

2023-03-23 13:39 UTC, LWJerri commented on site/docs/uk/resources/faq.md
> +5. Можна попросити Telegram збільшити ліміти, але це дуже малоймовірно, якщо ви не виконали 1-й та 3-й крок.
```suggestion
5. Можна попросити Telegram збільшити ліміти, але це дуже малоймовірно, якщо ви не виконали кроки з 1-го по 3-й.
```

2023-03-23 13:42 UTC, merged