[Ukrainian] Translate `/plugins/router.md`
grammyjs/website pull request #738
Opened 2023-03-23 06:06 UTC by Nazar-Ant

2023-03-23 06:46 UTC, Nazar-Ant commented
Поки що використовуються скорочені назви місяців. Пропоную використати назви місяців у родовому відмінку. Тоді на запитання "Якого місяця ви народилися?" (наразі питання інше, але ми його також змінемо) будуть наступні варіанти відповіді: січня, лютого, березня, квітня тощо. Якщо користувач запустить змінений таким чином приклад коду, то отримає нормальне повідомлення "Ваш день народження <число>-го (23-го, наприклад) <місяць> (березня, наприклад)" замість "... 23 Черв"

2023-03-31 00:40 UTC, deptyped requested changes

2023-04-01 00:38 UTC, LWJerri approved these changes

2023-04-01 16:56 UTC, LWJerri requested changes

2023-04-01 16:56 UTC, LWJerri commented on site/docs/uk/plugins/router.md
> +Наприклад, поєднання цих двох концепцій дозволяє створювати форми у вигляді інтерфейсу чату.
```suggestion
Наприклад, поєднання цих двох концепцій дозволяє створювати форми у вигляді інтерфейсу чата.
```

2023-04-01 16:56 UTC, LWJerri commented on site/docs/uk/plugins/router.md
> +Щоб обчислити кількість днів, бот повинен знати місяць і день місяця дня народження: наприклад, місяць - червень, день місяця - 15-й.
```suggestion
Щоб обчислити кількість днів, бот повинен знати місяць і день дня народження: наприклад, місяць - червень, день - 15-й.
```

2023-04-01 16:56 UTC, LWJerri commented on site/docs/uk/plugins/router.md
> +вашого дня народження у вигляді числа!",
```suggestion
"Будь ласка, надішліть мені день \
вашого народження у вигляді числа!",
```

2023-04-01 16:56 UTC, LWJerri commented on site/docs/uk/plugins/router.md
> +вашого дня народження у вигляді числа!",
```suggestion
"Будь ласка, надішліть мені день \
вашого народження у вигляді числа!",
```

2023-04-01 16:56 UTC, LWJerri commented
Actually, the translation itself is a bit confusing, but the @deptyped has to say what he thinks

2023-04-02 08:02 UTC, Nazar-Ant commented on site/docs/uk/plugins/router.md
> +Щоб обчислити кількість днів, бот повинен знати місяць і день місяця дня народження: наприклад, місяць - червень, день місяця - 15-й.
Може краще так?

```suggestion
Щоб обчислити кількість днів, бот повинен знати місяць і число дня народження: наприклад, місяць - червень, число - 15-е.
```

2023-04-02 08:03 UTC, Nazar-Ant commented on site/docs/uk/plugins/router.md
> +вашого дня народження у вигляді числа!",
Тут можна так, як і в попередньому зауважені

```suggestion
"Будь ласка, надішліть мені число \
вашого дня народження у вигляді!",
```

2023-04-02 08:05 UTC, Nazar-Ant commented on site/docs/uk/plugins/router.md
> +вашого дня народження у вигляді числа!",
```suggestion
"Будь ласка, надішліть мені число \
вашого дня народження!",
```

2023-04-02 08:05 UTC, Nazar-Ant commented on site/docs/uk/plugins/router.md
> +вашого дня народження у вигляді числа!",
```suggestion
"Будь ласка, надішліть мені число \
вашого дня народження!",
```

2023-04-02 17:18 UTC, deptyped commented on site/docs/uk/plugins/router.md
> +Щоб обчислити кількість днів, бот повинен знати місяць і день місяця дня народження: наприклад, місяць - червень, день місяця - 15-й.
Використовувати "день", як мені здається, краще, але потрібно не повторюватися, щоб не було "день дня народження". Може такий варіант?
```suggestion
Щоб обчислити кількість днів, бот повинен знати дату дня народження — місяць і день: наприклад, місяць - червень, день місяця - 15-й.
```

2023-04-02 18:03 UTC, Nazar-Ant commented on site/docs/uk/plugins/router.md
> +Щоб обчислити кількість днів, бот повинен знати місяць і день місяця дня народження: наприклад, місяць - червень, день місяця - 15-й.
@deptyped тире заміни на двокрапку, а минулу двокрапку заміни на кому

2023-04-02 18:05 UTC, Nazar-Ant commented on site/docs/uk/plugins/router.md
> +Щоб обчислити кількість днів, бот повинен знати місяць і день місяця дня народження: наприклад, місяць - червень, день місяця - 15-й.
Виправив пунктуацію

```suggestion
Щоб обчислити кількість днів, бот повинен знати дату дня народження, а саме місяць і день, наприклад, місяць - червень, день місяця - 15-й.
```

2023-04-11 15:26 UTC, LWJerri requested changes

2023-04-12 04:34 UTC, Nazar-Ant commented on site/docs/uk/plugins/router.md
> +    "Надішліть /birthday, щоб дізнатися, як довго вам доведеться чекати.",
```suggestion
    "Надішліть /birthday, щоб дізнатися, як довго вам доведеться чекати свого дня народження.",
```

2023-04-12 04:34 UTC, Nazar-Ant commented on site/docs/uk/plugins/router.md
> +    "Надішліть /birthday, щоб дізнатися, як довго вам доведеться чекати.",
```suggestion
    "Надішліть /birthday, щоб дізнатися, як довго вам доведеться чекати свого дня народження.",
```

2023-04-12 12:53 UTC, LWJerri approved these changes

2023-04-20 15:17 UTC, deptyped approved these changes

2023-04-20 15:29 UTC, merged