[Ukrainian] Translate `/plugins/parse-mode.md`
grammyjs/website pull request #744
Opened 2023-03-23 12:28 UTC by Nazar-Ant

2023-04-01 17:18 UTC, LWJerri requested changes

2023-04-01 17:18 UTC, LWJerri commented on site/docs/uk/plugins/parse-mode.md
> +// Встановлює режим форматування за замовчуванням для `ctx.reply`
```suggestion
// Встановлюємо режим форматування за замовчуванням для `ctx.reply`
```

2023-04-01 17:18 UTC, LWJerri commented on site/docs/uk/plugins/parse-mode.md
> +// Встановлює режим форматування за замовчуванням для `ctx.reply`
```suggestion
// Встановлюємо режим форматування за замовчуванням для `ctx.reply`
```

2023-04-01 17:18 UTC, LWJerri commented on site/docs/uk/plugins/parse-mode.md
> +// Встановлює режим форматування за замовчуванням для `ctx.reply`
```suggestion
// Встановлюємо режим форматування за замовчуванням для `ctx.reply`
```

2023-04-02 18:17 UTC, deptyped approved these changes

2023-04-03 08:39 UTC, LWJerri approved these changes

2023-04-03 11:40 UTC, merged