[Ukrainian] Translate `/plugins/chat-members.md`
grammyjs/website pull request #745
Opened 2023-03-23 13:59 UTC by Nazar-Ant

2023-03-24 17:02 UTC, LWJerri approved these changes

2023-03-24 17:18 UTC, deptyped requested changes

2023-03-24 17:18 UTC, deptyped commented on site/docs/uk/plugins/chat-members.md
> +Відстежуйте учасників груп і каналів та скаладйте їхній перелік.
```suggestion
Відстежуйте учасників груп і каналів та переглядайте їх список.
```

2023-03-24 17:18 UTC, deptyped commented on site/docs/uk/plugins/chat-members.md
> +Однак, наразі Telegram Bot API не надає жодного методу, який би дозволяв отримати цю інформацію.
```suggestion
Однак, наразі Telegram Bot API не надає методів для отримання цієї інформації.
```

2023-03-24 17:18 UTC, deptyped commented on site/docs/uk/plugins/chat-members.md
> +Це означає, що вам також потрібно вказати будь-які інші події, які ви хочете отримувати.
```suggestion
Це означає, що вам також потрібно вказати всі інші оновлення, які ви також хотіли б отримувати.
```

2023-03-24 17:18 UTC, deptyped commented on site/docs/uk/plugins/chat-members.md
> +На допомогу приходить цей плагін: він автоматично прослуховує події `chat_member` і зберігає всі обʼєкти `ChatMember`.
```suggestion
На допомогу приходить цей плагін: він автоматично обробляє оновлення `chat_member` і зберігає всі обʼєкти `ChatMember`.
```

2023-03-25 09:39 UTC, deptyped approved these changes

2023-03-25 14:02 UTC, merged