[Ukrainian] Translate `/plugins/ratelimiter.md`
grammyjs/website pull request #749
Opened 2023-03-23 15:19 UTC by Nazar-Ant

2023-03-24 16:59 UTC, LWJerri approved these changes

2023-03-24 17:57 UTC, deptyped requested changes

2023-03-24 17:57 UTC, deptyped commented on site/docs/uk/plugins/ratelimiter.md
> +## Налаштовуваність
```suggestion
## Налаштування
```

2023-03-24 17:57 UTC, deptyped commented on site/docs/uk/plugins/ratelimiter.md
> +  Значення за замовчуванням - `MEMORY_STORE`, яке використовує вбудований у памʼять [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), але ви також можете вк
```suggestion
  Значення за замовчуванням - `MEMORY_STORE`, для якого використовується [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) у памʼяті для зберігання даних, але ви також можете вказати клієнт Redis. [Докладніше про storageClient](#про-storageclient).
```

2023-03-24 17:57 UTC, deptyped commented on site/docs/uk/plugins/ratelimiter.md
> +- `onLimitExceeded` - функція, яка описує, що робити, якщо користувач перевищив ліміт; за замовчуванням ігнорує зайві запити.
```suggestion
- `onLimitExceeded` - функція, яка описує, що робити, якщо користувач перевищив ліміт; за замовчуванням ігнорує надмірні запити.
```

2023-03-24 17:57 UTC, deptyped commented on site/docs/uk/plugins/ratelimiter.md
> +Ви можете завантажити клієнт Redis з [ioredis](https://github.com/luin/ioredis) або [redis](https://deno.land/x/redis), якщо ви використовуєте Deno.
```suggestion
Ви можете використовувати клієнт Redis з [ioredis](https://github.com/luin/ioredis) або [redis](https://deno.land/x/redis), якщо ви використовуєте Deno.
```

2023-03-24 17:57 UTC, deptyped commented on site/docs/uk/plugins/ratelimiter.md
> +ratelimiter не залежить від драйверів.
```suggestion
ratelimiter не залежить від якогось конкретного драйверу.
```

2023-03-24 17:57 UTC, deptyped commented on site/docs/uk/plugins/ratelimiter.md
> +- Прийняття [налаштувань за замовчуванням](#налаштування-за-замовчуванням).
```suggestion
- Використання [налаштувань за замовчуванням](#налаштування-за-замовчуванням).
```

2023-03-24 17:57 UTC, deptyped commented on site/docs/uk/plugins/ratelimiter.md
> +- Передача власного обʼєкта з вашими налаштуваннями ([ручне налаштування](#ручне-налаштування)).
```suggestion
- Використання [ручного налаштування](#ручне-налаштування) з передачею власного обʼєкта з налаштуваннями.
```

2023-03-24 17:57 UTC, deptyped commented on site/docs/uk/plugins/ratelimiter.md
> +Цей фрагмент демонструє найпростіший спосіб використання ratelimiter, який полягає у прийнятті поведінки за замовчуванням:
```suggestion
Цей фрагмент демонструє найпростіший спосіб використання ratelimiter, який полягає у використанні налаштувань за замовчуванням:
```

2023-03-24 17:57 UTC, deptyped commented on site/docs/uk/plugins/ratelimiter.md
> +> Примітка: щоб уникнути переповнення серверів Telegram, `onLimitExceeded` виконується лише один раз у кожному `timeFrame`.
```suggestion
> Примітка: щоб уникнути надмірних запитів до серверів Telegram, `onLimitExceeded` виконується лише один раз у кожному `timeFrame`.
```

2023-03-25 09:38 UTC, deptyped approved these changes

2023-03-25 14:03 UTC, merged