[Ukrainian] Translate `/hostring/firebase.md`
grammyjs/website pull request #757
Opened 2023-03-25 14:48 UTC by LWJerri

2023-03-26 07:05 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +1. Перейдіть до [Firebase панелі управління](https://console.firebase.google.com/) та натисніть **додати проєкт**.
У Firebase немає українсього перекладу

```suggestion
1. Перейдіть до [панелі управління Firebase](https://console.firebase.google.com/) та натисніть **Add project**.
```

2023-03-26 07:05 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +3. Натисніть **продовжити**.
```suggestion
3. Натисніть **Continue**.
```

2023-03-26 07:05 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +5. Натисніть **створити проєкт**.
```suggestion
5. Натисніть **Create Project**.
```

2023-03-26 07:07 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +2. За допомогою команди `cd` перейдіть до директорії свого проєкту.
```suggestion
2. За допомогою команди `cd` перейдіть до каталогу свого проєкту.
```

2023-03-26 07:07 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +4. Виберіть `use existing project` та оберіть проєкт, який ви створили на кроці 1.
```suggestion
4. Виберіть `use existing project` та оберіть проєкт, який ви створили на 1-у кроці.
```

2023-03-26 07:08 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +6. Необовʼязково, ви можете вибрати ESLint.
```suggestion
6. За потреби ви можете вибрати ESLint.
```

2023-03-26 07:08 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +   Якщо ви використовуєте інший менеджер пакетів, наприклад `yarn` або `pnpm`, ви можете відхилити запит.
```suggestion
   Якщо ви використовуєте інший менеджер пакетів, наприклад, `yarn` або `pnpm`, ви можете відхилити запит.
```

2023-03-26 07:09 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +   В іншому випадку, проєкт може не запуститися.
```suggestion
   Інакше проєкт може не запуститися.
```

2023-03-26 07:09 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +Це значно швидше, ніж деплоїти кожну зміну на Firebase.
```suggestion
Це значно швидше, ніж розгортати кожну зміну на Firebase.
```

2023-03-26 07:10 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +Якщо він не вибраний, перейдіть до нього за допомогою клавіш зі стрілками та виберіть його, використовуючи `пробіл`.
```suggestion
Якщо він не вибраний, перейдіть до нього за допомогою клавіш зі стрілками та виберіть його, використовуючи пробіл.
```

2023-03-26 07:12 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +Це локальний URL вашої хмарної функції.
Ми завжди писали так, тому вважаю, що маємо продовжувати

```suggestion
Це локальна URL-адреса вашої хмарної функції.
```

2023-03-26 07:12 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +Існує кілька сервісів, таких як [localtunnel](https://localtunnel.me) або [ngrok](https://ngrok.com), які можуть вам у цьому допомогти. У цьому прикладі ми будемо використовувати localtunnel.
```suggestion
Існує кілька сервісів, таких як [localtunnel](https://localtunnel.me) або [ngrok](https://ngrok.com), які можуть вам у цьому допомогти.
У цьому прикладі ми будемо використовувати localtunnel.
```

2023-03-26 07:14 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +localtunnel повинен надати вам унікальний URL, наприклад, `https://modern-heads-sink-80-132-166-120.loca.lt`.
```suggestion
localtunnel повинен надати вам унікальну URL-адресу, наприклад, `https://modern-heads-sink-80-132-166-120.loca.lt`.
```

2023-03-26 07:14 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +Наприклад, відкрийте нову вкладку у своєму браузері та відвідайте цей URL:
```suggestion
Наприклад, відкрийте нову вкладку у своєму браузері та відвідайте цю адресу:
```

2023-03-26 07:14 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +Замініть `<BOT_TOKEN>` на свій дійсний токен бота та `<WEBHOOK_URL>` на власний URL, який ви отримали від localtunnel.
```suggestion
Замініть `<BOT_TOKEN>` на свій дійсний токен бота та `<WEBHOOK_URL>` на власну URL-адресу, яку ви отримали від localtunnel.
```

2023-03-26 07:15 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +Ваш бот готовий для тестування в розгорнутому середовищі.
```suggestion
Наразі ваш бот готовий для тестування розгортання.
```

2023-03-26 07:16 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +Firebase CLI надасть вам URL до вашої функції одразу після того, як розгортання буде завершено.
```suggestion
Firebase CLI надасть вам URL-адресу вашої функції одразу після того, як розгортання буде завершено.
```

2023-03-26 07:17 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +Для отримання докладнішої інформації ви можете звернутися до кроку 8 в [посібнику початку роботи](https://firebase.google.com/docs/functions/get-started?hl=ru#deploy-functions-to-a-production-environ
```suggestion
Для отримання докладнішої інформації ви можете звернутися до 8-го кроку в [посібнику початку роботи](https://firebase.google.com/docs/functions/get-started?hl=ru#deploy-functions-to-a-production-environment).
```

2023-03-26 07:17 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +Для цього відкрийте нову вкладку в браузері і відвідайте цей URL:
```suggestion
Для цього відкрийте нову вкладку в браузері і відвідайте цю адресу:
```

2023-03-26 07:19 UTC, Nazar-Ant commented on site/docs/uk/hosting/firebase.md
> +Перейдіть до Telegram та спостерігайте за відповідями!
У `supabase.md` ми використовували такий переклад, а оригінальне речення однакове, тож і у нас має бути той самий переклад

```suggestion
Перейдіть до Telegram та подивіться, як бот відповідає на повідомлення!
```

2023-03-26 09:48 UTC, LWJerri commented on site/docs/uk/hosting/firebase.md
> +Якщо він не вибраний, перейдіть до нього за допомогою клавіш зі стрілками та виберіть його, використовуючи `пробіл`.
We need here put пробіл in backtics.

2023-03-26 14:39 UTC, Nazar-Ant approved these changes

2023-03-31 00:33 UTC, deptyped requested changes

2023-03-31 10:22 UTC, merged