Update on Deta information
grammyjs/website pull request #787
Opened 2023-06-03 06:03 UTC by Nazar-Ant

I was looking into hosting on Deta for my new project and noticed that its documentation describes that it supports most web frameworks and even Deno, but this is not listed on the grammY website. There was a question mark on the grammys website, though, so you probably knew about this feature but didn't check it out, right? If that's true, I can check it out on my own project to make sure.

2023-06-03 07:29 UTC, dcdunkan commented
Just a note:

> There was a question mark on the grammY website, though, so you probably knew about this feature but didn't check it out, right?

I don't why it was a question mark, but I don't think that was the reason. Deta (**deta.sh**) only supported Node.js and Python apps. They recently announced that they are moving to deta.space, a new, better platform (they gave the old users time to migrate their apps - until June 1). And the new Deta (deta.space) apps currently supports more languages, as you said, including Deno.

2023-06-03 08:20 UTC, Nazar-Ant commented
@dcdunkan I see. So eventually deta.sh will disappear altogether and be completely replaced by deta.spase?

2023-06-03 08:28 UTC, dcdunkan commented
As far as I understand, yes. See https://deta.space/from-cloud and their announcement: https://deta.space/blog/introducing-space.

2023-06-15 19:44 UTC, KnorpelSenf commented
What are we going to do with this?

2023-06-16 04:33 UTC, Nazar-Ant commented
@KnorpelSenf Who are you addressing?)

2023-06-16 05:31 UTC, KnorpelSenf commented
Anyone who has an answer to my question

2023-06-16 08:19 UTC, roj1512 commented
@KnorpelSenf I think we can close this. Correct me if I’m wrong @dcdunkan @Nazar-Ant.

2023-06-16 08:27 UTC, Nazar-Ant commented
@roj1512 Do you think this change is unnecessary?

2023-06-16 08:27 UTC, roj1512 commented
This change is for deta.space, right?

2023-06-16 08:28 UTC, roj1512 commented
And the comparison talks about deta.sh?

2023-06-16 08:36 UTC, dcdunkan commented
I didn't mean to close this @roj1512. The whole section about Deta needs to be updated. The links should be changed to https://deta.space and the information should be updated as well.

2023-06-16 08:37 UTC, roj1512 commented
So merge these as is and update the rest in another PQ or do everything in this PQ?

2023-06-16 08:38 UTC, dcdunkan commented
> So merge these as is and update the rest in another PQ or do everything in this PQ?

That's for you guys to decide. As you like.

2023-06-16 08:38 UTC, roj1512 approved these changes

2023-06-16 08:39 UTC, roj1512 commented
I think you need to resolve the conflicts.

2023-06-16 08:41 UTC, Nazar-Ant commented
conflicts are resolved

2023-06-16 08:41 UTC, roj1512 commented
Thanks!

2023-06-16 09:20 UTC, CikiMomogi requested changes

2023-06-16 09:20 UTC, CikiMomogi commented on site/docs/hosting/comparison.md
> +| Deta                   | Free       | No paid plans yet                                                                                          | No specific limits
404
```suggestion
| Deta                   | Free       | No paid plans yet                                                                                          | No specific limits                                                                      | ✅                                                                                                      | ✅                                             | ✅                                                | Deno is supported by a [custom application](https://deta.space/docs/en/build/quick-starts/custom) ([example](https://github.com/deta/starters/tree/main/deno-app)). |
```

2023-06-17 20:52 UTC, roj1512 approved these changes

2023-06-18 21:06 UTC, LWJerri approved these changes

2023-06-20 20:17 UTC, habemuscode approved these changes

2023-06-23 10:11 UTC, CikiMomogi approved these changes

2023-06-23 11:02 UTC, merged