Use --- not — because it will be rendered correctly
grammyjs/website pull request #805
Opened 2023-06-18 16:34 UTC by KnorpelSenf

2023-06-18 16:39 UTC, KnorpelSenf commented
It's currently inconsistent

2023-06-18 17:57 UTC, roj1512 commented
What do you mean? Isn’t this PQ ready?

2023-06-18 17:59 UTC, KnorpelSenf commented
Yes, it is ready. I was adding additional information why this change was necessary.

2023-06-18 19:13 UTC, roj1512 commented
Is it translatable?

2023-06-18 20:44 UTC, KnorpelSenf commented
Yes. I do not know the rules for em dashes in other languages.

For example, — is never used in German, only – is found.

2023-06-19 07:05 UTC, roj1512 approved these changes

2023-06-23 11:00 UTC, roj1512 commented
@habemuscode Any changes to be made in Spanish?

2023-06-23 11:00 UTC, roj1512 commented
@Nazar-Ant Any changes to be made in Ukrainian?

2023-06-23 16:56 UTC, Nazar-Ant commented
@roj1512 Yes, we decided to also use a triple hyphen to represent dashes. This is something @LWJerri is working on.

2023-06-25 04:17 UTC, LWJerri commented on site/docs/uk/guide/introduction.md
> +---------------------------        вашому боту          ------------------------------------                  ---------------------------------
@Nazar-Ant, @roj1512, can I do this?

2023-06-25 04:18 UTC, LWJerri commented on site/docs/uk/guide/middleware.md
> +(ctx, next) => ...    |---------------нижчий проміжний обробник відносно X
And here?

2023-06-25 04:26 UTC, LWJerri approved these changes

2023-06-25 04:27 UTC, LWJerri commented
> 🚀 Deployed on https://64920538f6001c1dc38e48fa--grammy.netlify.app

@KnorpelSenf, why we don't have a fresh build?

2023-06-25 05:16 UTC, CikiMomogi commented
> > rocket Deployed on https://64920538f6001c1dc38e48fa--grammy.netlify.app
> 
> @KnorpelSenf, why we don't have a fresh build?

The conflicts must be resolved first.

2023-06-25 05:44 UTC, CikiMomogi commented
Oops the branch was changed. Sorry my bad.

2023-06-25 09:32 UTC, LWJerri commented
@CikiMomogi, I think changes for long dash doesn't apply to code block's.

2023-06-25 09:36 UTC, LWJerri commented
> @CikiMomogi, I think changes for long dash doesn't apply to code block's.

1. https://6497d2cb7a500b538129bdf4--grammy.netlify.app/uk/guide/middleware.html#%D1%81%D1%82%D0%B5%D0%BA-%D0%BF%D1%80%D0%BE%D0%BC%D1%96%D0%B6%D0%BD%D0%B8%D1%85-%D0%BE%D0%B1%D1%80%D0%BE%D0%B1%D0%BD%D0%B8%D0%BA%D1%96%D0%B2
2. https://6497d2cb7a500b538129bdf4--grammy.netlify.app/uk/guide/introduction.html#%D1%8F%D0%BA-%D0%BF%D1%96%D0%B4%D1%82%D1%80%D0%B8%D0%BC%D1%83%D0%B2%D0%B0%D1%82%D0%B8-%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D1%83-%D0%B1%D0%BE%D1%82%D0%B0

Scroll down and find tables.

2023-06-25 09:37 UTC, LWJerri commented
OMG, I missed open updated links, xDDD.....

2023-06-25 09:40 UTC, LWJerri commented
![image](https://github.com/grammyjs/website/assets/50290430/2092b0af-af86-4d2b-8671-d8f75010d541)

Incorrect long dash render. (https://github.com/grammyjs/website/blob/fix-conflict-triple-dash/site/docs/uk/guide/middleware.md, 77-85 lines).

2023-06-25 09:43 UTC, CikiMomogi commented
> @CikiMomogi, I think changes for long dash doesn't apply to code block's.

Indeed. All characters written inside the code block will be rendered as they are.

2023-06-25 09:45 UTC, LWJerri commented
> > @CikiMomogi, I think changes for long dash doesn't apply to code block's.
> 
> Indeed. All characters written inside the code block will be rendered as they are.

Oh, okay, thanks.

2023-06-25 17:45 UTC, Nazar-Ant requested changes

2023-06-25 17:53 UTC, Nazar-Ant commented on site/docs/uk/guide/introduction.md
> +_________        вашому боту          ____________                  ___________
Що тут не так було?

2023-06-25 20:47 UTC, habemuscode approved these changes

2023-06-25 21:12 UTC, LWJerri commented on site/docs/uk/guide/introduction.md
> +_________        вашому боту          ____________                  ___________
> Що тут не так було?

https://6497d2cb7a500b538129bdf4--grammy.netlify.app/uk/guide/introduction.html#%D1%8F%D0%BA-%D0%BF%D1%96%D0%B4%D1%82%D1%80%D0%B8%D0%BC%D1%83%D0%B2%D0%B0%D1%82%D0%B8-%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D1%83-%D0%B1%D0%BE%D1%82%D0%B0

2023-06-26 00:24 UTC, LWJerri commented on site/docs/uk/guide/middleware.md
> +(ctx, next) => ...    |———нижчий проміжний обробник відносно X
Fix it.

2023-06-26 00:25 UTC, LWJerri commented on site/docs/uk/guide/deployment-types.md
> +|            |     —         ні.          —>    |           |
Fix it.

2023-06-26 10:10 UTC, roj1512 approved these changes

2023-06-26 10:10 UTC, merged