Added a note in menu docs
grammyjs/website pull request #830
Opened 2023-06-26 15:59 UTC by adithyagenie

Fixes grammyjs/menu#39

2023-07-07 14:20 UTC, KnorpelSenf requested changes
What does it mean that it “does not work?” How can this be fixed? I do not understand what you're trying to document here (and I wrote the plugin)

2023-07-07 18:46 UTC, adithyagenie commented on site/docs/plugins/menu.md
> +> Note that using [dynamic buttons](#dynamic-ranges) which generate based on the payload might not work.
I meant buttons created by dynamic ranges, that was poor wording. My bad.

2023-07-07 18:50 UTC, adithyagenie commented
> What does it mean that it “does not work?”

I meant that it might produce undesirable results, as the menu will be re-rendered partially with some other payload than what was used to render it initially.

I am not really that capable to writing documentations that well. Apologies.

2023-07-08 23:05 UTC, KnorpelSenf commented
Do you think #869 works well?

2023-07-10 10:23 UTC, adithyagenie commented
Yes, #869 is fine! I'll close this PR now.

2023-07-10 10:23 UTC, closed without merging