[Portuguese] translate context.md
grammyjs/website pull request #906
Opened 2023-08-23 21:49 UTC by kr4t0z

2023-08-30 21:55 UTC, roziscoding requested changes

2023-08-30 21:55 UTC, roziscoding commented on site/docs/pt/guide/context.md
> +| `ctx.from`            | Obtém o autor da mensagem, consulta de callback ou outras coisas                                    |
```suggestion
| `ctx.from`            | Obtém o autor da mensagem, callback query ou outras coisas                                    |

```

2023-08-30 21:55 UTC, roziscoding commented on site/docs/pt/guide/context.md
> +Ainda, se quiser, pode ignorar `ctx.message`, `ctx.channelPost`, `ctx.editedMessage`, etc e simplesmente usar sempre `ctx.msg` no lugar.
```suggestion
Ainda, se preferir, você pode ignorar `ctx.message`, `ctx.channelPost`, `ctx.editedMessage`, etc e simplesmente usar sempre `ctx.msg` no lugar.

```

2023-08-30 21:55 UTC, roziscoding commented on site/docs/pt/guide/context.md
> +É por isso que os métodos são coletivamente chamados _verificações has_.
```suggestion
É por isso que os métodos são coletivamente chamados de _verificações has_.

```

2023-08-30 21:55 UTC, roziscoding commented on site/docs/pt/guide/context.md
> +Note que você normalmente deve usar [filter queries](./filter-queries) e métodos similares.
```suggestion
Note que normalmente é melhor usar [filter queries](./filter-queries) e métodos similares.

```

2023-08-30 21:55 UTC, roziscoding commented on site/docs/pt/guide/context.md
> +Você pode notar duas coisas que não são ideais sobre isso:
```suggestion
É possível notar duas coisas que não são ideais aqui:

```

2023-08-30 21:55 UTC, roziscoding commented on site/docs/pt/guide/context.md
> +Por baixo dos panos, o contexto _já conhece o identificador do chat_ (nomeadamente `ctx.msg.chat.id`), então ele te dá o método `reply` para apenas enviar uma mensagem de volta para o mesmo chat.
```suggestion
Por baixo dos panos, o contexto _já conhece o identificador do chat_ (ou seja, `ctx.msg.chat.id`), então ele te dá o método `reply` para apenas enviar uma mensagem de volta para o mesmo chat.

```

2023-08-30 21:55 UTC, roziscoding commented on site/docs/pt/guide/context.md
> +Este último pode ser usado para fazer uma mensagem como resposta:
```suggestion
Este último pode ser usado para enviar uma mensagem como resposta:

```

2023-08-30 21:55 UTC, roziscoding commented on site/docs/pt/guide/context.md
> +Naturalmente, todos os outros métodos em `ctx.api` têm atalhos com os valores pré-preenchidos corretos, como `ctx.replyWithPhoto` para responder com uma foto, ou `ctx.exportChatInviteLink` para obter
```suggestion
Naturalmente, todos os outros métodos em `ctx.api` têm atalhos com os valores pré-preenchidos corretos, como `ctx.replyWithPhoto` para responder com uma foto, ou `ctx.exportChatInviteLink` para obter um link de convite para o chat correspondente.

```

2023-08-30 21:55 UTC, roziscoding commented on site/docs/pt/guide/context.md
> +Note que você pode não querer reagir sempre no mesmo bate-papo.
```suggestion
Note que você pode não querer reagir sempre no mesmo chat.

```

2023-08-30 21:55 UTC, roziscoding commented on site/docs/pt/guide/context.md
> +Por exemplo, se você receber uma mensagem da Alice e quiser reagir enviando uma mensagem para o Bob, então você não pode usar `ctx.reply` porque sempre enviará mensagens para o bate-papo com a Alice.
```suggestion
Por exemplo, se você receber uma mensagem da Alice e quiser reagir enviando uma mensagem para o Bob, então você não pode usar `ctx.reply` porque sempre enviará mensagens para o chat com a Alice.

```

2023-08-30 21:55 UTC, roziscoding commented on site/docs/pt/guide/context.md
> +Em vez disso, chame `ctx.api.sendMessage` e especifique o identificador do bate-papo do Bob.
```suggestion
Em vez disso, chame `ctx.api.sendMessage` e especifique o identificador do chat do Bob.

```

2023-08-30 21:55 UTC, roziscoding commented on site/docs/pt/guide/context.md
> +Se você fizer `ctx.nomeDaSuaPropriedadePersonalizada = seuValorPersonalizado` dentro de um handler assim, então a propriedade `ctx.nomeDaSuaPropriedadePersonalizada` estará disponível nos handlers re
```suggestion
Se você fizer `ctx.nomeDaSuaPropriedadePersonalizada = seuValorPersonalizado` dentro de um handler, a propriedade `ctx.nomeDaSuaPropriedadePersonalizada` estará disponível nos handlers restantes também.

```

2023-08-30 21:55 UTC, roziscoding commented on site/docs/pt/guide/context.md
> +const BOT_DEVELOPER = 123456; // identificador do bate-papo do desenvolvedor do bot
```suggestion
const BOT_DEVELOPER = 123456; // identificador do chat do desenvolvedor do bot

```

2023-08-30 21:57 UTC, KnorpelSenf commented on site/docs/pt/guide/context.md
> +  // Será `indefinido` se a mensagem recebida não tiver nenhum texto de mensagem,
Smells like AI to me

2023-10-16 10:38 UTC, roziscoding approved these changes

2023-10-16 10:46 UTC, roziscoding commented
Why the fuck are lint and fmt failing?

2023-10-16 10:54 UTC, CikiMomogi commented
Try update the dependencies and run "npm run docs:fmt"

2023-10-16 10:56 UTC, CikiMomogi commented
Oh wait, you already done that. 😅
In that case, update your deno.

2023-10-16 11:14 UTC, roziscoding commented
Lint is still failing, but the file has the same structure as the one on main.
What am I missing? 🤔

2023-10-16 20:34 UTC, KnorpelSenf commented
@roziscoding from https://github.com/grammyjs/website/actions/runs/6532773242/job/17736607570?pr=906#step:4:33 you can see

```
docs/pt/guide/README.md:1 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "![grammY](/images/grammY.webp)"]
```

2023-10-16 20:36 UTC, KnorpelSenf commented
… so you have to do it like in https://raw.githubusercontent.com/grammyjs/website/main/site/docs/guide/README.md and set

```
<!-- markdownlint-disable first-line-heading -->
```

2023-10-18 11:09 UTC, merged