[Portuguese] translate deployment-types.md
grammyjs/website pull request #931
Opened 2023-10-26 20:50 UTC by kr4t0z

2023-10-27 00:46 UTC, roziscoding requested changes

2023-10-27 00:46 UTC, roziscoding commented on site/docs/pt/guide/deployment-types.md
> +Todos os bots que usam grammY podem ser convertidos para um middleware de vários frameworks web, incluindo `express`, `koa`/`oak`, e mais.
```suggestion
Todos os bots que usam o grammY podem ser convertidos para um middleware de vários frameworks web, incluindo `express`, `koa`/`oak`, e mais.
```

2023-10-27 00:46 UTC, roziscoding commented on site/docs/pt/guide/deployment-types.md
> +Para que possa suportar diferente tipos de frameworks web, grammY adota o conceito de **adaptadores**.
```suggestion
Para que possa suportar diferentes tipos de frameworks web, o grammY adota o conceito de **adaptadores**.
```

2023-10-27 00:46 UTC, roziscoding commented on site/docs/pt/guide/deployment-types.md
> +The second parameter passed to `webhookCallback` ([Referência da API](https://deno.land/x/grammy/mod.ts?s=webhookCallback)) define o adaptador de framework usado para se comunicar com o framework web
```suggestion
O segundo parâmetro passado para `webhookCallback` ([Referência da API](https://deno.land/x/grammy/mod.ts?s=webhookCallback)) define o adaptador de framework usado para se comunicar com o framework web.
```

opa kk

2023-10-27 00:46 UTC, roziscoding commented on site/docs/pt/guide/deployment-types.md
> +Pela maneira que essa abordagem funciona, nós geralmente precisamos de um adaptador para cada framework mas já que alguns frameworks compartilham uma interface similar, existem adaptadores que são co
```suggestion
Por conta de como essa abordagem funciona, nós geralmente precisamos de um adaptador para cada framework, mas já que alguns frameworks compartilham uma interface similar, existem adaptadores que são conhecidos por funcionar em múltiplos frameworks.
```

2023-10-27 00:46 UTC, roziscoding commented on site/docs/pt/guide/deployment-types.md
> +   Por exemplo, chamar `sendMessage` não vai te dar acesso a mensagem enviada.
```suggestion
   Por exemplo, chamar `sendMessage` não vai te dar acesso à mensagem enviada.
```

2023-10-27 00:46 UTC, roziscoding commented on site/docs/pt/guide/deployment-types.md
> +4. Note também que os tipos no grammY não refletirão nas consequências de um callback de webhook performado!
```suggestion
4. Note também que os tipos no grammY não refletirão as consequências de um callback de webhook executado!
```

essa frase fica mto normal em inglês mas horrível em pt-br, acho que assim fica menos pior, mas ainda achei estranha
queria mto uma terceira opinião aqui kk

2023-10-27 00:46 UTC, roziscoding commented on site/docs/pt/guide/deployment-types.md
> +   Por exemplo, eles indicam que você sempre vai receber um objeto de resposta, então é sua próprio responsabilidade garantir que você não vai fazer besteira enquanto utiliza esse detalhe de optmizaç
```suggestion
   Por exemplo, eles indicam que você sempre vai receber um objeto de resposta, então é sua própria responsabilidade garantir que você não vai fazer besteira enquanto utiliza esse detalhe de optmização de performance.
```

2023-10-27 00:46 UTC, roziscoding commented on site/docs/pt/guide/deployment-types.md
> +Passe a funcão que determina se você vai ou não utilizar o resposta de webhook para a dada requisição, identificada por método.
```suggestion
Passe a funcão que determina se você vai ou não utilizar a resposta de webhook para a dada requisição, de acordo com o método.
```

2023-10-27 00:46 UTC, roziscoding commented on site/docs/pt/guide/deployment-types.md
> +Quando o Telegram envia um update de um chat do seu bot, ele vai esperar você terminar a requisição antes de entregar o próximo update que pertence ao chat.
```suggestion
Quando o Telegram envia um update de um chat ao seu bot, ele vai esperar você terminar a requisição antes de entregar o próximo update que pertence ao chat.
```

2023-10-27 00:46 UTC, roziscoding commented on site/docs/pt/guide/deployment-types.md
> +O Telegram garantir que o seu bot recebe todos os updates.
```suggestion
O Telegram garante que o seu bot receberá todos os updates.
```

2023-10-27 00:46 UTC, roziscoding commented on site/docs/pt/guide/deployment-types.md
> +Se o seu middleware terminar antes disso, a função `webhookCallback` vai responder ao webhookd automaticamente.
```suggestion
Se o seu middleware terminar antes disso, a função `webhookCallback` vai responder ao webhook automaticamente.
```

2023-10-27 00:46 UTC, roziscoding commented on site/docs/pt/guide/deployment-types.md
> +Você pode observar seu começar a spammar usuários enquanto tenta tratar todos esses updates (Que são na verdade o mesmo toda vez).
```suggestion
Você pode observar seu bot começar a spammar usuários enquanto tenta tratar todos esses updates (que são na verdade o mesmo toda vez).
```

2023-10-27 00:46 UTC, roziscoding commented on site/docs/pt/guide/deployment-types.md
> +Entretanto, como o antigo update ainda está sendop processado, dois updates que seriam previamente processados sequencialmente, são repentinamente processados em paralelo.
```suggestion
Entretanto, como o antigo update ainda está sendo processado, dois updates que seriam previamente processados sequencialmente são repentinamente processados em paralelo.
```

2023-10-27 00:46 UTC, roziscoding commented on site/docs/pt/guide/deployment-types.md
> +Essa resposta é mais fácil de dizer do que implementar.
```suggestion
Essa resposta é mais fácil de falar do que de fazer.
```

acho legal usar o ditado em si

2023-10-27 20:46 UTC, roziscoding approved these changes

2023-10-27 20:47 UTC, roziscoding commented
só arruma o que o fmt tá pedindo pls

2023-10-28 23:35 UTC, kr4t0z commented on site/docs/pt/guide/deployment-types.md
> +> Note que na verdade, a conexão seria mantida por horas.
```suggestion

> Note que na verdade, a conexão seria mantida por horas.
```

2023-10-28 23:36 UTC, kr4t0z commented on site/docs/pt/guide/deployment-types.md
> +bot.start()
```suggestion
bot.start();
```

2023-10-28 23:42 UTC, merged