[Portuguese] translate plugins/README.md
grammyjs/website pull request #943
Opened 2023-11-09 01:59 UTC by Salv4d

2023-11-10 15:26 UTC, roziscoding requested changes
Sugeri algumas alterações pequenas mas no geral ficou muito bom!
Valeu demais pela contribuição! 😄

2023-11-10 15:26 UTC, roziscoding commented on site/docs/pt/plugins/README.md
> +Alguns plugins já são **built-in** na lib grammY porque assumimos que muitos bots vão utilizá-los.
```suggestion
Alguns plugins já são **built-in** na lib central do grammY porque assumimos que muitos bots vão utilizá-los.
```

acho que fica legal pra dar mais a entender que estamos falando do core

2023-11-10 15:26 UTC, roziscoding commented on site/docs/pt/plugins/README.md
> +Eles são instalados da `@grammyjs/*`no npm, e publicados sob a organização [@grammyjs](https://github.com/grammyjs) no GitHub.
```suggestion
Eles são instalados da `@grammyjs/* `no npm, e publicados sob a organização [@grammyjs](https://github.com/grammyjs) no GitHub.
```

2023-11-10 15:26 UTC, roziscoding commented on site/docs/pt/plugins/README.md
> +## Overview
```suggestion
## Visão Geral
```

traduzimos assim em outros pontos

2023-11-10 15:26 UTC, roziscoding commented on site/docs/pt/plugins/README.md
> +Nós compilamos um overview objetivo com descrições curtas para cada plugin.
```suggestion
Nós compilamos uma visão geral objetiva com descrições curtas para cada plugin.
```

2023-11-10 15:26 UTC, roziscoding commented on site/docs/pt/plugins/README.md
> +| [Sessions](./session)                      | _built-in_                                         | Grava dados do usuário no seu database                  |
```suggestion
| [Sessions](./session)                      | _built-in_                                         | Grava dados do usuário no seu banco de dados            |
```

2023-11-10 15:26 UTC, roziscoding commented on site/docs/pt/plugins/README.md
> +| [Media Groups](./media-group)              | _built-in_                                         | Simplifica o envio de albums e a edição de media        |
```suggestion
| [Media Groups](./media-group)              | _built-in_                                         | Simplifica o envio de albums e a edição de mídia        |
```

2023-11-10 15:26 UTC, roziscoding commented on site/docs/pt/plugins/README.md
> +| [Inline Queries](./inline-query)           | _built-in_                                         | Facilita a construção de resultados para queries inline |
```suggestion
| [Inline Queries](./inline-query)           | _built-in_                                         | Facilita a construção de resultados para inline queries |
```
não traduzimos "inline queries", então rola de deixar igual ao original mesmo

2023-11-10 15:26 UTC, roziscoding commented on site/docs/pt/plugins/README.md
> +| [Chat Members](./chat-members)             | [`chat-members`](./chat-members)                   | Rastreie que usuário entrou no chat                     |
```suggestion
| [Conversations](./conversations)           | [`conversations`](./conversations)                 | Cria poderosas interfaces conversacionais e diálogos    |
| [Chat Members](./chat-members)             | [`chat-members`](./chat-members)                   | Rastreia que usuário entrou no chat                     |
```

2023-11-10 15:26 UTC, roziscoding commented on site/docs/pt/plugins/README.md
> +| [Hydration](./hydrate)                     | [`hydrate`](./hydrate)                             | Executa métodos em objetos retornados de chamados de API|
```suggestion
| [Hydration](./hydrate)                     | [`hydrate`](./hydrate)                             | Executa métodos em objetos retornados de chamadas de API|
```

2023-11-10 15:26 UTC, roziscoding commented on site/docs/pt/plugins/README.md
> +Bom, tudo que reluz é ouro, certo?
```suggestion
Tudo que reluz é ouro, certo?
```

2023-11-10 15:26 UTC, roziscoding commented on site/docs/pt/plugins/README.md
> +Plugins Middleware são plugins conectados a um bot como---um, você adivinhou---middleware.
```suggestion
Plugins Middleware são plugins conectados a um bot como um---bom, você adivinhou---middleware.
```

2023-11-10 15:26 UTC, roziscoding commented on site/docs/pt/plugins/README.md
> +### Type I: Plugins Middleware
```suggestion
### Tipo I: Plugins Middleware
```

2023-11-10 15:26 UTC, roziscoding commented on site/docs/pt/plugins/README.md
> +### Type II: Plugins Transformadores
```suggestion
### Tipo II: Plugins Transformadores
```

2023-11-10 15:26 UTC, roziscoding commented on site/docs/pt/plugins/README.md
> +A [transformer function](../advanced/transformers) is the opposite of middleware!
```suggestion
```

2023-11-11 00:30 UTC, Salv4d commented on site/docs/pt/plugins/README.md
> +Eles são instalados da `@grammyjs/*`no npm, e publicados sob a organização [@grammyjs](https://github.com/grammyjs) no GitHub.
Apliquei em um novo commit :smile:

2023-11-11 00:30 UTC, Salv4d commented on site/docs/pt/plugins/README.md
> +## Overview
Apliquei em um novo commit :smile:

2023-11-11 00:30 UTC, Salv4d commented on site/docs/pt/plugins/README.md
> +Nós compilamos um overview objetivo com descrições curtas para cada plugin.
Apliquei em um novo commit :smile:

2023-11-11 00:30 UTC, Salv4d commented on site/docs/pt/plugins/README.md
> +| [Sessions](./session)                      | _built-in_                                         | Grava dados do usuário no seu database                  |
Apliquei em um novo commit :smile:

2023-11-11 00:30 UTC, Salv4d commented on site/docs/pt/plugins/README.md
> +| [Media Groups](./media-group)              | _built-in_                                         | Simplifica o envio de albums e a edição de media        |
Apliquei em um novo commit :smile:

2023-11-11 00:30 UTC, Salv4d commented on site/docs/pt/plugins/README.md
> +| [Inline Queries](./inline-query)           | _built-in_                                         | Facilita a construção de resultados para queries inline |
Apliquei em um novo commit :smile:

2023-11-11 00:30 UTC, Salv4d commented on site/docs/pt/plugins/README.md
> +| [Chat Members](./chat-members)             | [`chat-members`](./chat-members)                   | Rastreie que usuário entrou no chat                     |
Apliquei em um novo commit :smile:

2023-11-11 00:31 UTC, Salv4d commented on site/docs/pt/plugins/README.md
> +| [Hydration](./hydrate)                     | [`hydrate`](./hydrate)                             | Executa métodos em objetos retornados de chamados de API|
Apliquei em um novo commit :smile:

2023-11-11 00:31 UTC, Salv4d commented on site/docs/pt/plugins/README.md
> +Bom, tudo que reluz é ouro, certo?
Apliquei em um novo commit :smile:

2023-11-11 00:31 UTC, Salv4d commented on site/docs/pt/plugins/README.md
> +Plugins Middleware são plugins conectados a um bot como---um, você adivinhou---middleware.
Apliquei em um novo commit :smile:

2023-11-11 00:31 UTC, Salv4d commented on site/docs/pt/plugins/README.md
> +### Type I: Plugins Middleware
Apliquei em um novo commit :smile:

2023-11-11 00:31 UTC, Salv4d commented on site/docs/pt/plugins/README.md
> +### Type II: Plugins Transformadores
Apliquei em um novo commit :smile:

2023-11-11 00:31 UTC, Salv4d commented on site/docs/pt/plugins/README.md
> +A [transformer function](../advanced/transformers) is the opposite of middleware!
Apliquei em um novo commit :smile:

2023-11-12 10:47 UTC, roziscoding commented
@Salv4d pode rodar um `deno fmt` nesse arquivo, por favor? Não consigo rodar porque não tenho permissão na sua branch 😅

2023-11-12 12:20 UTC, Salv4d commented
> @Salv4d pode rodar um `deno fmt` nesse arquivo, por favor? Não consigo rodar porque não tenho permissão na sua branch 😅 

Já tinha rodado localmente, tem alguma configuração ou só instalar o deno e rodar (foi o que eu fiz)?

2023-11-12 12:32 UTC, roziscoding commented
Kkkk putz, my bad. Vou rodar na branch `pt` inteira. Obrigado! 😄

2023-11-12 12:33 UTC, merged