Hosting: Supabase Edge Functions fix url to supabase cloud functions.
grammyjs/website pull request #983
Opened 2024-01-12 16:55 UTC by sultanby

According to https://supabase.com/docs/guides/functions/deploy link to deploy supabase edge functions has been changed from 
https://api.telegram.org/bot<BOT_TOKEN>/setWebhook?url=https://<PROJECT_NAME>.functions.supabase.co/telegram-bot?secret=<BOT_TOKEN> 
to 
https://api.telegram.org/bot<BOT_TOKEN>/setWebhook?url=https://<PROJECT_REFERENCE_ID>.supabase.co/functions/v1/telegram-bot?secret=<BOT_TOKEN>
Here is the fix for all languages (en, zh, uk, es, id) where outdated url was present.

2024-01-13 00:47 UTC, KnorpelSenf commented
Thanks for the fix. How did you obtain the translations?

2024-01-13 14:00 UTC, sultanby commented
@KnorpelSenf about uk i asked a friend, for es and id translations i used dictionary for word 'reference' and for zh i used google translator. I can remove wrong translation if necessary.

2024-01-13 14:07 UTC, KnorpelSenf commented
Alrighty, please leave them in. I'll ping our translators to have a quick look, but I guess then we can merge :)

2024-01-13 14:08 UTC, KnorpelSenf approved these changes

2024-01-13 14:44 UTC, niusia-ua requested changes

2024-01-13 14:44 UTC, niusia-ua commented on site/docs/uk/hosting/supabase.md
> +Замініть `<ідентифікатор-проєкту>` ідентифікатором вашого проекту Supabase.
```suggestion
Замініть `<ідентифікатор-проєкту>` ідентифікатором вашого проєкту Supabase.
```

2024-01-13 14:45 UTC, niusia-ua approved these changes

2024-01-25 21:01 UTC, roj1512 approved these changes
Thank you!

2024-01-25 21:01 UTC, merged