Fix reaction docs
grammyjs/website pull request #984
Opened 2024-01-18 09:57 UTC by KnorpelSenf

2024-01-18 14:46 UTC, roj1512 approved these changes

2024-01-20 08:19 UTC, niusia-ua commented on site/docs/guide/context.md
> +| `ctx.reactions`       | Gets the reactions from an update in a [way that is easy to work with](./reactions#inspecting-how-reactions-changed |
```suggestion
| `ctx.reactions`       | Gets the reactions from an update in a [way that is easy to work with](./reactions#inspecting-how-reactions-changed) |
```

2024-01-30 01:30 UTC, quadratz requested changes

2024-01-30 01:30 UTC, quadratz commented on site/docs/zh/guide/reactions.md
> +  const message = reaction``.message_id;
```suggestion
  const message = reaction.message_id;
```

2024-02-06 00:16 UTC, merged

2024-02-06 00:17 UTC, KnorpelSenf commented
@roj1512 remember to dismiss any pending reviews when you want to merge. Otherwise, auto-merge won't kick in.